@node
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@conversionCode=tei
@conversionMethod=literal
@converter=Dirk Roorda (Text-Fabric)
@description=this is TEI attribute id
@descriptionTf=Edition
@editor=Jan Bloemendal
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@language=la
@schema=TEI + translatin
@sourceFormat=TEI
@teiVersion=not specified
@title=Translatin (drama, 1500-1750))
@valueType=str
@version=0.0.1
@writtenBy=Text-Fabric
@dateWritten=2024-12-23T11:44:46+00:00Z

1849753	front
main
personae.
incipit
argumentum.
scena-i.
scena-ii.
scena-iii.
scena-iv.
scena-v.
scena-vi.
scena-vii.
scena-viii.
scena-ix.
scena-x.
scena-xi.
scena-xii.
scena-xlll.
scena-xiv.
scena-xv.
scena-xvi.
scena-xvii.
scena-xviii.
scena-xix.
scena-xx.
back
front
main
personae-dramatis.
argumentum-dramatis.
personae.-calumnia-cum-geniis-suis-justitia-divina-cum-suis
scena-i.
i-prae-meisque-subditis-nostri-refer
scena-ii.
scena-iii.
scena-iv.
scena-v.
scena-est-musica-per-totum.
scena-i.-1
scena-ii.-1
scena-iii.-1
scena-iv.-1
scena-tota-est-musica.
scena-v.-1
personae.-golo-sigefridus-duo-filii-golonis.
personae.-golo-sigefridus-filii-golonis.
scena-vi.
i.-at-si-deinde-fama-quam-jussae-necis
i.-ergo-perempta-maneat-ficto-dolo
scena-vii.
personae.-sigefridus-solus.
scena-viii.
personae.-nuncius-chorus.
scena-iii.-2
personae.-genovefa-benoni-filius.
scena-iv.-2
personae.-sigefridus-venatores.-scena-tota-est-musica.
scena-ultima.
back
front
main
personae.-iephte-iudex-hebraeorum-nonus.-iephtias-menulema.-filia.
actus-i.
scena-i.
scena-ii.
chorus
chorus.
incipit-a-se-nobilis-esse
actus-ii.
scena-i.-1
scena-ii.-1
scena-iii.
scena-iv.
scena-v.
scena-vi.
scena-vii.
chorus.complectitur-iephtae-encomium-militare-classicum-de-conflictus
chorus.-vates.
actus-iii.
scena-i.-2
pars-aliqua-texti-laevam-ad-aurem-pulcrius-reg-pulchrius
scena-ii.-2
pars-torsit-in-condensa-primam-et-auspicem
i-reliqua-propere-defer-in-palatium
scena-iii.-1
i-triste-belli-numen-ad-thracas-tuos.
scena-tubarum-intercalaris-sive-exspectatio-reditus-iephtai-cum
scena-iv.-1
i.-menulema-m.-iephte-i-gnata-m.-mi-dulcis-pater.
i.-quis-mea-rigore-membra-connectit-chalybs
i-magne-maeror-matris.-i.-luctus-patris
chorus-militum.
actus-iv.
scena-i.-3
i-nunc-et-aemulare-maioreis-reg-maiores-tuos.
chorus.-chor-quo-quo-tandem-verget-amari
scena-ii.-3
pars-adhuc-lactis-memor-et-mamillae
pars-adhuc-caldis-in-humata-membris.
pars-inaequali-tumulata-campo.
scena-iii.-2
scena-iv.-2
actus-v.
scena-i.-4
pars-moesta-lamentatur-ac-lacrymis-reg-lacrimis-vacat
pars-rabida-prae-furore-lacrymari-reg-lacrimari-nequit.
scena-ii.-4
scena-iii.-3
pars-iam-recepta-ventre-luctando-exitum
scena-iv.-3
i-quidquid-ignis-halat-extremi-rape.
scena-ult.-abbr.
chorus-virginum-sodalium-menulemae-immolatam-iephtiaden-plangentium.
chorus-absistat-passibus-aequis.
pars-renodatos-lacerent-capillos
pars-sinant-densae-fluere-instar-undae
chorus.-1
back
front
main
back
front
main
personae.
prologvs.
tragoidia-sacra.
actvs-primvs.
chorus-ex-pastoribus.
actvs-secvndvs.
chorus-ex-pastoribus-sive-canticum-eorum.
actvs-tertivs.
epilogvs.
back
front
main
prologus-cum-argumento-in-euripum-tragoediam.
personae-dramatis.
chori-lamentantium.
chorus-daemonum-aëriorum.
actus-euripi-primus-b-5v
i5
chorus-primus
actus-euripi-secundus
chorus-secundus-d-5r
actus-euripi-tertlus
chorus-tertius
actus-euripi-quartus
chorus-quartus
actus-euripi-quintus
chorus-daemonum-aëriorum.-1
chorus
chorus-1
chorus-quintus
peroratio
back
front
main
personae.
chorvs.
actvs-primvs.
i-verte-caecis-verte-fumantem-ignibus
chorvs-celebrat
actvs-secvndi
actvs-secvndvs.
i-verte-iura-verte-natura-omnia
chorvs.-1
i-dolor-ventis-equita-proteruis
actvs-tertii-synopsis.
actvs-tertivs.
chorvs.-2
actvs-qvarti
incipit-dulci-sanctos-affatur-amore
actvs-qvartvs.
i-sequere-mucro-sequere-foelicem-impetum
chorvs
chorus.
actvs-qvinti-perioche.
actvs-qvintvs.
chorus.-1
i-pede-fausto-quò-tua-virtus
i-pede-fausto-iuuenis-sancte
i-pede-fausto-quò-tua-virtus-1
chorus.-2
i-pede-fausto-tu-prima-feres
i-pede-fausto-venerande-puer.
i-vince-mortem-vince-tartareos-canes.
chorvs-1
back
front
main
personae.
prologvs.
pars-prima.
pars-ii.
pars-iii.
pars-iiii.
pars-v.
back
front
main
personae.
chorvs.
chorvs
actvs-secvndvs.
chorvs-hebraeorvm
actvs-tertivs.
actus-sub-imis-perfurit-venis-dolor
i-perge-praeco-perge-da-signum-tuba.
chorvs-1
actvs-qvartvs.
i-pede-fausto-dilecte-deo
i-merge-flammis-merge-sceleratam-luem.
chorvs-2
actvs-qvintvs.
chorvs-principvm
back
front
main
chorvs-hebraeorum.
actvs-primvs.
chorvs.
actvs-secvndvs.
actvs-secvndvs.-1
scena-reserunt-nescio.-tantùm-precor
chorvs
actvs-tertivs.
chorvs-1
actvs-qvartvs.
chorvs-chaldaeorvm-principum.
chorvs-2
actvs-qvintvs.
i-fulminatrix-rumpe-iam-nubem-munus
i-sequere-vecors-si-libet-fratrem-tuum.
chorvs-3
back
front
main
personae.
chorvs.
actvs-secvndvs.
i-repete-si-quid-matris-è-gremio-trahis
i-perge-coniux-repete-desertam-domum.
chorvs.-1
actvs-tertivs.
prima-iuuentus-pingit-in-orbem
i.-perge-miles-perge-amborum-caput
chorvs.-2
actvs-qvartvs.
chorvs
actvs-qvintvs.
chorvs-angelorvm-cvm-tvbis
i.-diua-non-fueram-tibi.
i.-quod-tu-efferato-stulte-calcabas-pede.
back
front
main
personae.
chorus.
actvs-primvs.
scena-prima.
pars-est-futuri-doceat-exemplo-hic-senex
actvs-tertivs.
prima-leuat-nouitas-laborem
scena-prima.-1
scena-prima.-2
pars-vna-partem-hîc-seruo.-simulacrum-hoc-tui
back
front
main
actvs-primvs.
i-nunc-tyranne-ciuium-sulca-latus
i-abominande-pasce-martyribus-famem
actvs-secvndvs.
pars-vna-stragis-inter-comites-mali
chorvs.-vasaces.
pars-seruitutis-ista-quam-metuis-quota-est
pars-immite-ligonibus
pars-vepreta-per-horridis
actvs-qvartvs.
i-sequere-princeps-si-preces-procerum-valent
scena-prima.
i-viue-per-me-quod-queo-vlcisci-sat-est.
back
front
main
personae.
prologvs.
i-quaere.-sed-eccum-critiam.-vt-anhelat-verbero.
pars-magna.-nostrae-clarum-familiae-decus
actvs-tertivs.
actvs-qvintvs.
back
front
main
scena-prima.
prima-fortunae-vocat-aura-séque
actvs-tertivs.
actvs-ovartvs.
back
front
main
actus-i.
actus-ii.
actus-iii.
actus-iv.
actus-v.
personae-ludi-omnes-in-unum-chorum-congregatae-gratiarum-actiones-agunt
back
front
main
personae.
pars-prima.
scena-prima.
scena-secunda.
scena-tertia.
scena-quarta.
scena-quinta.
scena-sexta.
scena-septima.
scena-octava.
scena-nona.
scena-decima.
scena-undecima.
pars-secunda.
scena-prima.-1
scena-secunda.-1
scena-tertia.-1
scena-quarta.-1
scena-quinta.-1
scena-sexta.-1
scena-septima.-1
pars-tertia.
scena-prima.-2
scena-secunda.-2
scena-tertia.-2
scena-quarta.-2
scena-quinta.-2
back
front
main
i-oseph-qua-hebraeus-seruiens-aegyptio
protasis-comoediae.
actvs-primi-scena-i.
actvs-primi-scena-ii.
actvs-primi-scena-iii.
actvs-primi-scena-iiii.
actvs-primi-scena-v.
actvs-secvndi-scena-i.
actvs-secvndi-scena-ii.
actvs-secvndi-scena-iii.
epitasis-comoediae.
actvs-tertii.-scena-i.
actvs-tertii-scena-ii.
actvs-qvarti.-scena-i.
actvs-qvarti-scena-ii.
actvs-qvarti-scena-iii.
actvs-qvinti-scena-ii.
actvs-qvinti-scena-iii.
back
front
main
personae-lb
chorvs
chorus
chorus-1
chorus.
back
front
main
prima-habeat-melius-quosque-fecunda-viros.
dramatis-personae.
chorvs-nympharum-actu-secundo-punicarum-actu-quinto.
prologvs.
actus-.i.-scena-.i.
scena-.ii.
scena-.iii.
scena.-iiii.
chorvs.
actus-.ii.-scena-.i.
scena-.ii.-1
scena-iii.
scena-iiii.
chorus-nympharum.
actus.-iii.-scena-.1.
scena-.ii.-2
scena.-iii.
scena-iiii.-1
chorvs.-1
actus.-iiii.-scena.-i.
scena.-ii.
scena.-iii.-1
i-pete-per-vndas-regna-ventis-concitas.
scena.-iiii.-1
chorvs.-2
actus-irarum-stimulis-cupido
actus.-v.-scena-.i.
scena.-ii.-1
i-prospera-contende-littus-alite.
scena.-iii.-2
finis.
back
front
main
personae-dramatis.
prologvs.
actvs-primi
scena-i.
pars-morbidae-parant-senectae-plurimas
scena-ii.
scena-iii.
scena-iiii.
scena-v.
actvs-secvndi
scena-i.-1
scena-ii.-1
scena-iii.-1
scena-iiii.-1
scena-v.-1
actvs-tertii
scena-i.-2
finis.-quod-coeptum-est-prauisque-rationibus
scena-ii.-2
scena-iii.-2
scena-iiii.-2
scena-v.-2
scena-vi.
actvs-qvarti
scena-i.-3
scena-ii.-3
scena-iii.-3
scena-iiii.-3
scena-v.-3
actvs-qvinti
scena-i.-4
scena-ii.-4
scena-iii.-4
scena-iiii.-4
scena-v.-4
scena-vi.-1
scena-vii.
epilogvs.
back
front
main
i-per-beatas-insulas-fausto-pede
i-clarus-hospes-per-liquidum-aethera
i.-uitkomste.
i-nunc-arctâ-compede-innexus-pedem
i.-uitkomste.-1
i-ventoso-turgens-fastu
back
front
main
i-alastor
chorus
chorus-1
chorus-2
chorus-3
actus-primus.
pars-iam-peracta-est-magna.-nec-enim-principes
chorus.
actus-secundus.
pars-nulla-terrae-vacua-nostro-est-numine
chorus.-1
actus-tertius
chorus.-2
actus-quartus.
chorus.-3
actus-quintus.
back
front
main
back
front
main
prologvs.
comoedia-si-prolixa-sit-at-ingens-erat
dramatis-personae.
chorus-quinque-virginum.
actus-i.-scena-i.-trimetri-iambici.
actus-i.-scena-ii.-trimetri.
actus-i.-scena-iii.-ejusdem-rationis.
actus-i.-scena-iv.-tetrametri-acatalectici.
actus-ii.-scena-i.-senarii.
actus-ii.-scena-ii.-acatalectici.
actus-ii.-scena-iii.-senarii.
actus-ii.-scena-iv.-trimetri-iambici.
actus-ii.-scena-v.-tetrametri-acatalectici-cum-catalectiois.
actus-iii.-scena-i.-iamb.-trimetri.
actus-iii.-scena-ii.-trochaici.
actus-iii.-scena-iii.-iambici-acatalectici.
actus-iii.-scena-iv.-senarii.
actus-iii.-scena-v.-ejusdem-rationis.
actus-iii.-scena-vi.-eadem-cum-superioribus.
actus-iii.-scena-vii.-quadrata-anapaestica-catalectica.
actus-iv.-scena-i.-trimetri.
actus-iii.-scena-ii.-octonarii-unus-senarius.
fabula-ita-mundum-hunc-tecum-choragium-esse-quoddam-cogita
actus-iv.-scena-iii.-trimetri.
actus-iv.-scena-iv.-trimetri.
actus-iv.-scena-v.-catalectici-trochaioi.
actus-iv.-scena-vi.-trimetri.
actus-iv.-scena-vii.-iambici-acatalectici-unus-senarius.
actus-iv.-scena-viii.-ejusdem-rationis.
actus-v.-scena-i.-senarii.
actus-v.-scena-ii.-trochaici-tetrametri-catalectici.
actus-v.-scena-iii.-iambici-trimetri
actus-v.-scena-iv.-scazontes-iambici.
actus-v.-scena-v.-scazontes-iambici.
chorus-5.-virginum.-ecclesia.-europus.-africus.
chorus-virginum.
back
front
main
actorvm-nomina
prologvs
argvmentvm-comoediae
actvs-primi-scaena-prima
actvs-primi-scaena-secvnda
actvs-primi-scaena-tertia
actvs-primi-scaena-qvarta
actvs-secvnda-scaena-prima
actvs-secvndi-scaena-secvnda
actvs-secvndi-scaena-tertia
actvs-secvndi-scaena-qvarta
actvs-secvndi-scaena-qvinta
actvs-tertii-scaena-prima
actvs-tertii-scaena-secvnda
actvs-tertii-scaena-tertia
actvs-tertii-scaena-qvarta
i-prae-sequar.
actvs-tertii-scaena-qvinta
actvs-qvarti-scaena-secvnda
i-nunc-et-somnia-irride-posthac-mea.
pars-reliqua.
actvs-qvarti-scaena-tertia
actvs-qvarti-scaena-qvarta
actvs-qvarti-scaena-qvinta
i-sane-iam-quo-uis.
actvs-qvarti-scaena-sexta
actvs-qvarti-scaena-septima
actvs-qvinti-scaena-prima
actvs-qvinti-scaena-secvnda
actvs-qvinti-scaena-tertia
actvs-qvinti-scaena-qvarta
actvs-qvinti-scaena-qvinta
back
front
main
argumentum-comoediae.
prologus.
actus-primus.-scaena-prima.
actus-primi-scaena-ii.
actus-primi-scena-iii.
actus-primi-scaena-iiii.
actus-secundus-scena-i
actus-secundi-scena-ii.
actus-secundi-scena-iii
actus-secundi-scena-iiii.
actus-tertii-scena-prima.
actus-tertii-scena-ii.
actus-tertii-scena-iii.
actus-tertii-scena-iiii.
actus-quartus.
actus-quarti-scena-ii.
actus-iiii-scena-iii.
actus-iiii-scena-iiii.
actus-iiii-scena-v.
actus-iiii-scena-vi.
actus-quintus
actus-v-scena-ii.
actus-v-scena-iii.
actus-v-scena-iiii.
actus-v-scena-v.
i-vise-si-sub-moriae-se-dedere
actus-v-scena-vi.
back
front
main
prologus.
argumentum.
actus-1.
personae.
interlocutores.
actus-primi-scena-prima.
actus-primi-scena-secunda.
actus-primi-scena-tertia.
actus-primi-scena-quarta.
actus-primi-scena-quinta.
actus-secundi-scena-prima.
actus-secundi-scena-secunda.
actus-secundi-scena-tertia.
actus-secundi-scena-quarta.
actus-tertii-scena-prima.
actus-tertii-scena-secunda.
actus-tertij-scena-tertia.
actus-tertij-scena-quarta.
actus-tertij-scena-quinta.
actus-quarti-scena-prima.
actus-quarti-scena-secunda.
actus-quarti-scena-tertia.
i-milites-scitare-quanam-discipuli
actus-quarti-scena-quarta.
actus-quinti-scena-prima.
actus-quinti-scena-secunda.
actus-quinti-scena-tertia.
back
front
main
prologus
actus-primi-scena-sexta.
actus-secundi-scena-prima
back
front
main
comoediae-progressu-multo-clarius.
back
front
main
personae
chorus-discipulorum.
chorus-galileidum.
prologvs.
argvmentvm-actvs-i.
actvs-i.-scena-i.
actvs-i.-scena-ii.
argvmentvm-actvs-ii.
actus-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iiii.
argvmentvm-actvs-iii.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-1111.
actvs-iii.-scena-v.
actus-iii.-scena-vi.
argvmentvm-actvs-iiii.
actvs-iiii.-scena-i.
actvs-iiii.-scena-ii.
actvs-iiii.-scena-iii.
actvs-iiii.-scena-iiii.
actvs-iiii.-scena-v.
actvs-iiii.-scena-vi.
argvmentvm-actvs-v.
actvs-v.-scena-i.
actvs-v.-scena-ii.
back
front
main
actus-primus.
chorus.
actus-secundus.
pars-nulla-nostri-dividi-nec-possumus.
pars-ista-medio-quam-tui-calcant-pedes
chorus
actus-iii.
chorus.-1
actus-iiii.
pars-utra-vincet-magne-te-testor-deus
chorus.-2
actus-quintus.
back
front
main
personae.
chorus-iudaearum-mulierum.
chorus-militum-romanorum.
actus-primus.
chorus-iudaearum-mulierum.-1
pars-tenet-batti-steriles-arenas
actus-secundus.
chorus-iudaearum-mulierum.-2
actus-tertius.
chorus-iudaearum-mulierum.-iesus.
actus-quartus.
pars-maesta-vultu-ac-corde-defixo-stupet
pars-morte-lenta-fruitur-et-quantum-potest
pars-moesta-pars-attonita.-quo-ruitis-viri
chorus-romanorum-militum.
actus-quintus.
back
front
main
interlocutores
strophe-ii.
strophe-iii.
strophe-iv.
strophe-v.
strophe-vi.
strophe-vii.
strophe-viii.
strophe-ix.
strophe-x.
strophe-xi.
strophe-xii.
pars-luminum-cum-facibus-ortivis-vigil
pars-clausa-ritu-siderum-occumbentium
pars-alia-vallum-dum-parant-ascendere
strophe-ii.-1
strophe-iii.-1
pars-morte-parili-gloriam-aequatam-ferunt.
pars-interemto-scuta-detracta-agmini
pars-functa-fato-corpora-antigonâ-duce
back
front
main
dramatis-personae.
prologus
actus-i.
scena-i.
argumentum-scenae.
actus.-i.-scena-ii.
argumentum.
actus-i.-scena-iii.
argumentum.-1
actus-i.-scena-iiii.
argumentum.-2
actus-i.-scena-v.
argumentum.-3
actus-ii.
scena-i.-1
argumentum.-4
actus-ii.-scena-ii.
argumentum.-5
actus-ii.-scena-iii.
argumentum.-6
actus-ii.-scena-iiii.
argumentum.-7
actus-ii.-scena-v.
argumentum.-8
actus-iii.
scena-i.-2
argumentum.-9
actus-iii.-scena-ii.
argumentum.-10
actus-iii.-scena-iii.
argumentum.-11
actus-iii.-scena-iiii.
argumentum.-12
actus-iii.-scena-v.
argumentum.-13
actus-iiii.
scena-i.-3
argumentum.-14
actus-iiii.-scena-ii.
argumentum.-15
actus-iiii.-scena-iii.
argumentum.-16
actus-iiii.-scena-iiii.
argumentum.-17
actus-iiii.-scena-v.
argumentum.-18
actus-v.
scena-i.-4
argumentum.-19
actus-v.-scena-ii.
argumentum.-20
actus-v.-scena-iii.
argumentum.-21
actus-v.-scena-iiii.
argumentum.-22
actus-v.-scena-v.
argumentum.-23
back
front
main
personae-tragoediae
pars-illa-nostri-est-cetera-ipsa-quae-dedit
chorus-senum-flandrorum-profugorum.
prima-fudisti-puerumque-longe
pars-aequoreas-walachrûm-sedes
pars-caerulei-gurgite-ponti
pars-sudantem-proprio-semper
actus-ii.-scena-i.
scena-ii.
chorus.
prima-salutas-obvia-voce
actus.-iii.-scena.-i.
scena.-ii.
chorus
actus-quartus.-scena-i.
scena-ii.-1
scena.-iii.
finis-futuri-primus-est-aevi-gradus
pars-tendat-illac-pars-ad-illa-pars-ad-haec
chorus.-1
actus.-v.
back
front
main
chori-duo-primi-vatum-ac-piorum-tertius-senum-hebraeorum-quartus
pars-flammeum-titanis-immensi-caput
pars-astra-mundo-lapsa-diverso-colit.
chorus-vatum-et-piorum.
actus-secundus.
chorus
actus-tertius.
pars-monte-sensim-assurigt-et-coeli-viam
pars-bethlehemi-vatibus-visum-ferunt
pars-nec-repertum.-dubia-diversi-canunt.
pars-vindicari-posse-contemptu-autumat
chorus-senum-hebraeorum.
actus-quartus.-339
pars-ipse-pompae-dux-cathenati-gregis
chorus-militum-romanorum.
actus-quintus.
prima-secunda-tertia.
prima
pars-una-superest.-impius-binos-solo
prima-1
pars-magna-ferrum-nescia-excepit-sui
pars-ense-saevo-pectus-effossi-iacent
pars-palpitat-pars-una-semineces-adhuc
pars-prole-rapta-frustra-in-absentem-furit.
pars-impotentes-inserit-coelo-manus
pars-astra-voce-incendit-ac-divos-ciet.-361
pars-torpet-obstupetque-pars-terrae-sedet
pars-haeret-uni.-pars-parentem-dividit
pars-ubera-inter-inter-innocuas-dapes
back
front
main
prologvs-in-catharinam.
argvmentvm.
personae-tragoediae.
chorus-duplex.
actvs-primi
scena-.i.
actvs-primi-1
scena-.ii.
actvs.-i.-scena.-iii.
actvs.-i.-scena.-iiii.
actvs.-i.-scena.-v.
actvs-primi-2
scena.-vi.
chorvs-aegyptiarvm.
actvs-secvndi
scena-prima.
actvs.-ii.-scena.-ii.
actvs.-ii.-scena.-iii.
actvs.-ii.-scena.-iiii.
actvs-ii.-scena.v.
chorvs-aegyptiarvm.-1
actvs-tertii
scena-prima.-1
i-refer-ituros-mox-sequemur-proximi.
actvs.-iii.-scena.-ii.
actvs.-iii.-scena.-iii.
actvs.-iii.-scena.-iiii.
chorvs-angelorvm.
actvs-qvarti
scena-prima.-2
actvs-qvarti-1
scena.-ii.
actvs.-iiii.-scena.-iii.
i-nec-timere-caesaris-vim-me-refer.
actvs.-iiii.-scena.-iiii.
actvs.-iiii.-scena.-v.
chorvs-aegyptiarvm.-2
actvs-qvinti
scena-prima.-3
actvs.-v.-scena.-ii.
actvs.-v.-scena.-iii.
actvs.-v.-scena.-iiii.
actvs.-v.-scena.-v.
actvs.-v.-scena.-vi.
actvs.-v.-scena.-vii.
actvs-qvinti-1
scena.-viii.
i-liber-i-foelix-diuûm-numine-tutus
i-foelix-igitur-tutus-celebrisque-potensque
back
front
main
prologvs
prologvs.-7
argvmentvm.
personae-actionis.
chorvs-puellarum-vicissim-angelorum.
actvs.-i.-scena.-ii.
actvs.-i.-11
actvs.-i.-scena.-iii.
actvs.-i.-13
actvs.-i.-scena.-iiii.
actvs.-i.-15
prima-in-me-erit-mißi-satellitis-manus
actvs.-i.-scena.-v.
actvs.-i.-17
actvs.i.-scena.-vi.
chorvs.
actvs-secvndi.
scena-prima.
actvs.-ii-21
actvs.-ii.-scena.-ii.
actvs.-ii.-23
actvs.-ii.-scena.-iii.
actvs.-ii.-scena.-iiii.
actvs.-ii.-25
actvs-ii.-scena.-v.
actvs.-ii.-27
actvs.-ii.-scena.-vi.
actvs.-ii.-scena.-vii.
actvs-ii.-29
chorvs-angelorvm-ad-consolandvm-lavrentivm.
actvs-tertii-scena-i.
actvs.-iiii.-31
actvs.-iii.-scena.-ii.
actvs-iii.-33
actvs.-iii.-scena.-iii.
actvs.-iii.-scena.-iiii.
actvs.-iii.-scena.-v.
actvs.-iii.-scena.-vi.
actvs.-iii.-37
actvs.-iii.-scena.vii.
actvs-tertii-scena.-viii.
actvs.-iii.-39
chorvs.-1
actvs.-iiii.-41
actvs-qvarti-scena-prima.
actvs-iiii.-43
actvs.-iiii.-45
actvs.-iiii.-scena.-ii.
actvs.-iiii.-scena.-iii.
actvs.-iiii.-scena.-iiii.
actvs.-iiii.-49
i-sponsor-poenas-pro-eo-fidus-dato.
actvs.-iiii.-scena.-v.
actvs.-iiii.-51
i-confer-alias-cum-meis-gazis-opes.
actvs-iiii.-scena.vi.
actvs-iiii.-53
chorvs-angelorvm.
actvs.-iiii.-55
actvs-qvinti-scena-prima.
actvs.-v.-57
actvs-qvinti-scena.-ii.
actvs.-v.-59
actvs-qvinti-scena.-iii.
actvs.-v.-scena.-iiii.
actvs.-v.-scena.-v.
actvs.-v.-61
actvs.-v.-scena.-vi.
actvs.-iiii.-63
actvs.-v.-scena.-vii.
actvs.-v.-65
actvs-qvinti-scena.-viii.
actvs-v.-67
actvs-qvinti-scena.-ix.
actvs.-v.-69
actvs.-v.-scena-vltima.
actvs.-v.-71
back
front
main
personae.
scena-prima.-actvs-primvs.
scena-secvnda.
chorvs.
actvs-secvndvs.
chorvs.-1
chorvs.-senex.-del.-nvntivs-mo
scena-secvnda.-1
scena-tertia.
chorvs.-2
pars-ista-nostri.-quod-tamen-solers-acus
chorvs.-3
i-lictor-aude-vinculis-diras-manus
back
front
main
prologvs.
argumentum.
pars-cytharam-pars-pulsat-ebur-parit-alea-multis
i-tu-prior-cur-non-sequar-recalcitrat
actus-secundus.
conclusio.
i-3
i-ij.
i
i-1
i-i
i-iij
i.
i-2
i-4
i-epenumero-pspicua-mentis-indagatione-musarum-anti
back
front
main
ludionum-nomenclaturę
prologvs
actvs-primi.
scena-prima.
actus-primi.-scena-secunda.
actus-primi.-scena-tertia.
actus-primi.-scena-quarta.
chorus-primus.
actus-secundus.-scena-prima.
actus-secundi.-scena-secunda.
chorus.
actus-tertij.-scena-prima.
actus-tertij.-scena-secunda.
actus-tertij.-scena-tertia.
actus-tertij.-scena-quarta.
chorus.-1
actus-quarti.-scena-prima.
actus-quarti.-scena-secunda.
actus-quarti.-scena-tertia
chorus.17
actus-quinti.-scena-prima.
i.-4.
actus-quinti.-scena-secunda.
actus-quinti-scena-tertia.
actus-quinti.-scena-quarta.
actus-quinti-scena-quinta.
back
front
main
interloqvvtores
prologvs
actvs-i.
scena-i.
i-2-135-156.-actvs-i
scena-ii.
scena-iii.
i-3-181-211.-actvs-iii
scena-iiii.
i-4-240-266.-actvs-i-13
actvs-ii.
scena-i.-1
scena-ii.-1
scena-iii.-1
scena-iiii.-1
actvs-iii.
scena-i.-2
scena-ii.-2
scena-iii.-2
scena-iiii.-2
actvs-iiii.
scena-i.-3
scena-ii
actus-v
scena-i.-4
scena-ii.-3
scena-iii.-3
scena-iiii.-3
prima-ferar-truci-turbida-vultu
ieljquum-iure-haeredjtario-cedat-nepotibus.
scena-v.
scena-vi.
scena-vii.
back
front
main
prologus-in-codrum-feliciter-incipit.
argumentum.
back
front
main
back
front
main
actorum-nomina.
chorus-ex-filiis-israelis-polyhydria-ancillae
epilogus.-populus-aegyptius.-demus.
i-ocobela-celatum-mittit-in-aquam-extrahit
i-dentidem-recusans-plagis-caeditur.
i-srael-laetus-canticum-domino-canit.
prologvs.
comoedia
finis-prologi.
actus-primi-scena-prima.
scena-2a.-senarii.
scena-3a.-septenarii-cum-quibusdam-octon.
scena-4a-trimetri.
comoedia-1
scena-5a.-eiusdem-generis-cum-superiorib.
comoedia-2
comoedia-3
scena-6a.-trimetri-vt-superiores.
chorus-i.-ex-pueris-puellis-israelitarum
actus-secundi-scena-prima.
scena-2.-septenarii-octonarii.
scena-3a-trimetri-iambici.
scena-4.-scazontes.
comoedia-4
scena-5a-iamb.-senarii.
comoedia-5
chorus-2.-hexastrophos-filiorum-israelis.
comoedia-6
actus-3.-scena-1a-senarii.
scena-2a-trimetri.
scena-tertia-senarii.
comoedia-7
scena-4a-octonarii-iambici.
comoedia-8
scena-5a-trimetri.
comoedia-9
scena-6a-eiusdem-farinae-versus.
comoedia-10
scena-7.-scazontes.
scena-8.-trochaici-trimetri.
scena-9a-iambici-trimetri.
chorus-tertius.-ex-psalmo-105.
actus-4.-scena-i.-senarii-iamb.
scena-2.-trochaici-senarii.
comoedia-11
scena-3.-trimetri-iambici.
comoedia-12
scena-4.-septenarii.
comoedia-13
scena-5.-trimetri.
scena-6.-eiusdem-generis-cum-superioribus
scena-7.-trimetri-iamb.
scena-8.-similis-farinae-vsus.
scena-9.-octonarii-admistis-septe
comoedia-14
scena-10.-trimetri-iambici.
comoedia-15
scena-ii.-vt-superiores.
comoedia.
scena-xii.
scena-xiii.-eiusdem-generis-vt-sup.
chorus-4.-filiorum-israelis.
actus-5.-scena-i.
scena-2.-trimetri-vt-superiores.
scena-4.-trimetri.
comoedia-16
scena-5.-senarii-iamb.
comoedia-17
scena-6.-eiusdem-generis.
comoedia-18
scena-7.-trimetri.
scena-8.-similis-farinae.
scena-9.
scena-10.-octonarii-vt-supra.
epilogus-seu-peroratio.
comoedia-19
comoedia-tragica.
back
front
main
personae-dramatis.
chorvs-ex-mvndi-et-carnis-pedisseqvis.
argvmentvm-comoediae.
i-nstruitur-ad-militiam-à-timotheo-suo.
i-llecebrisque.-ille-at-fortiter-resistere.
i-n-campum-militem-vltrò-prouocant.-at-is
prologus-in-militem.
actvs-primi-scena-prima.
argvmentvm.
actvs-primi-scena-secvnda.
argvmentvm.-1
actvs-i.-scena-iii.
argvmentvm.-2
actvs-primi-scena-qyarta
argvmentvm.-3
actvs-primi-scena-qvinta
argvmentvm.-4
chorvs-primvs.
actvs-secvndi-scena-prima.
argvmentvm.-5
actvs-secvndi-scena-secvnda.
argvmentvm.-6
actvs-secvndi-scena-tertia.
argvmentvm.-7
actvs-secvndi-scena-qvarta.
argvmentvm.-8
actvs-secvndi-scena-qvinta
argvmentvm.-9
actvs-secvndi-scena-sexta.
argvmentvm.-10
chorvs-secvndvs.
actvs-tertii-scena-prima.
argvmentvm.-11
actvs-tertii-scena-secvnda.
argvmentvm.-12
actvs-tertii-scena-tertia.
argvmentvm.-13
actvs-tertii-scena-qvarta.
argvmentvm.-14
actvs-tertii-scena-qvinta.
actvs-tertii-scena-sexta
argvmentvm.-15
chorvs-tertivs-hexastrophos.
actvs-qvarti-scena-prima.
actvs-iiii-scena-secvnda.
actvs-qvarti-scena-tertia.
actvs-iiii-scena-qvarta
chorvs-qvartvs.
actvs-qvinti-scena-prima.
actvs-v-scena-secvnda
actvs-v.-scena-iii.-et-vltima.
epilogus.
back
front
main
prologus-silentium-a-spectatoribus-precatur.
fabula-forte-rudis-praecordia-uestra-iuuabit
actvs-secvndvs.
actvs-qvartvs.
back
front
main
chorvs.
actvs-primvs.
chorvs.-1
actvs-secvndvs
chorvs.-2
actvs-tertivs.
chorvs.-3
actvs-qvartvs.
chorvs.-4
i
actvs-qvintvs
i-2
back
front
main
scena-prima.
actvs-i.-9
chorus.
actvs-i.-11
actvs-i.-13
actvs-ii.
actvs.-ii-15
actvs-ii.-17
chorus.-1
actvs-ii.-19
actvs-iii.
actvs-iii.-21
chorus.-2
actvs-iii.-23
actvs-iii.-25
prima-pube-virescens
actvs-iii.-27
actvs-iiii.
actvs-iiii.-29
actvs-iiii.-31
chorus.-3
actvs-v.-33
actvs-v.
actvs-v.-35
actvs.-v.-37
chorus.-4
actvs-v.-39
back
front
main
chorvs.
chorvs.-1
actvs-secvndvs
chorvs.-2
actvs-tertivs.
chorvs.-3
actvs-qvartvs.
chorvs.-4
actvs-qvintvs.
back
front
main
chorvs-chaldaeorvm.
chorvs-israelitarvm.
actus-primi.-scena-ia.
chorvs-chald.
actvs-2.-biij
chorvs-chald.-1
actvs-3.
chorvs-israelit.
actvs-4.
chorvs-israelit.-1
chorus-iterum-solymé-dilecta-vale
actvs-5.
chorvs-israelit.-plangentivm.
back
front
main
actvs-primvs
chorvs.
actvs-secvndvs
prima-illa-moles-musico-planctu-rotet
actvs-tertivs.
chorvs.-1
actvs-qvartvs.
chorvs.-2
actvs-qvintvs
back
front
main
actvs-primvs
chorvs.
actvs-secvndvs.
chorvs.-1
actvs-tertivs
chorvs.-2
actvs-qvartvs.
chorvs.-3
actvs-qvintvs.
i-iunge-vulpes-laeta-nunc-floret-seges
back
front
main
chorvs.
actvs-primvs.
chorvs.-1
actvs-secvndvs.
chorvs.-2
actvs-tertivs.
chorvs.-3
actvs-qvartvs.
chorvs.-4
actvs-qvintvs
back
front
main
prologus.
personae-dramatis-seu-diverbii-actus-primi
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
actus-i.-scaena-v.
actus-i.-scaena-vi.
actus-i.-scaena-vii.
chorus.
personae-dramatis-in-secundo-actu.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-interiectitia.
actus-ii.-residuum-scaenae-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
chorus.-1
personae-dramatis-actus-tertii.
actus-iii.-scaena-i.
actus-iii.-scaena-interiectitia.
actus-iii.-residuum-scaenae-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
actus-iii.-scaena-vii.
actus-iii.-scaena-viii.
actus-iii.-scaena-interiectitia
actus-iii.-scaena-altera-interiectitia.
actus-iii.-residuum-scaenae-viii.
actus-iii.-scaena-ix.
actus-iii.-scaena-x.
actus-iii.-scaena-xi.
chorus.-2
personae-dramatis-actus-quarti.
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
finis.-super-thronum-davidis-et-super
actus-iv.-scaena-vi.
chorus.-3
dramatis-personae-in-quinto-actu.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scanea-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ix.
actus-v.-scaena-x.
actus-v.-scaena-xi.
actus-v.-scaena-xii.
actus-v.-scaena-xiii.
actus-v.-scaena-xiv.
actus-v.-scaena-xv.
actus-v.-scaena-xvi.
actus-v.-scaena-xvii.
epilogus-per-quemlibet-dicendus-aut-canendus.
back
front
main
dramatis-personae.
prologus-cum-moro-paedium-puer
prologus-in-alutam-cum-moro.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
actus-i.-scaena-v.
actus-i.-scaena-vi.
chorus-ex-bacchidibus-seu-mimallonibus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
chorus-maenadum.
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
chorus-mimallonum.
actus-iv.-scaena-i.
i-paedium-...-pae.-hem.-hei.-atque-vise-si-usquam-appareat
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
chorus.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
back
front
main
prologus.
chorus-bacchidum.
actus-primi.-scena-prima.
actus-i.-scena-ii.
actus-primi-scena-tertia.
actus-primi.-scena-quarta.
chorus-mimallonum.
actus-ii.-scena-i.
actus-secundi.-scena-secunda.
actus-secundi.-scena-tertia.
actus-secundi.-scena-quarta.
chorus-mimallonum.-1
actus-iii-scena-i.
actus-tertij-scena-secunda.
actus-tertij-scena-tertia.
actus-tertij-scena-quarta.
chorus-mimallonum.-2
actus-iiii.-scena-i.
actus-quarti.-scena-secunda.
actus-iiii.-scena-iii.
scena-quarta.-actus-quarti.
actus-quarti-scena-quinta.
chorus-mimallonum.-3
actus-quinti.-scena-prima.
actus-quinti-scena-secunda.
actus-v.-scena-tertia.
actus-quinti-scena-quarta.
actus-quinti-scena-quinta.
actus-quinti-scena-sexta.
actus-quinti-scena-septima.
actus-quinti-scena-octava.
actus-quinti-scena-nona.
actus-quinti.-scaena-decima.
actus-quinti.-scaena-undecima.
back
front
main
dramatis-personae.
prologus-diaboli-duo
prologus.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
chorus.-1
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
actus-iii.-scaena-vii.
actus-iii.-scaena-viii.
actus-iii.-scaena-ix.
actus-iii.-scaena-x.
actus-iii.-scaena-xi.
chorus.-2
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
i-transfer-haec-puer-in-triremen-asiaticam.-pae.-quid-postea
actus-iv.-scaena-viii.
chorus.-3
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ultima.
back
front
main
actores-fabulae.
prologus-dromus-servus
prologus.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
chorus
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
actus-iii.-scaena-vii.
chorus.-1
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
i-differatur-cena-et-ultra-septimam.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
actus-iv.-scaena-viii.
chorus.-2
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
back
front
main
personae-dramatis
prologus-daemones-cum-duobus-amicis
prologus-in-hecastum.
chorus.-versu-sapphico.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus.
pars-atque-sors-mortalibus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
actus-ii.-scaena-vi.
actus-ii.-scaena-vii.
actus-ii.-scaena-viii.
actus-ii.-scaena-ix.
actus-ii.-scaena-x.
chorus.-1
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
actus-iii.-scaena-vii.
chorus.-2
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
chorus.-3
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
scaena-interiectitia.
actus-v.-scaena-viii.
pars-altera.-violenta-nulla-diutina.
actus-v.-scaena-ix.
actus-v.-scaena-x.
actus-v.-scaena-xi.
actus-v.-scaena-xii-interiectitia.
actus-v.-scaena-xiii.
personae-apud-deum-sed-omni-in-gente-qui
back
front
main
dramatis-personae.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
actus-ii.-scaena-vi.
chorus.-1
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
chorus-versu-dimetro.
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
chorvs.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
chorvs.-1
back
front
main
dramatis-personae.
prologus-cum-epilogo-nathanael
prologus.
personae-erunt-tristemque-habebunt-exitum.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus-carmine-trochaico-dimetro.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
actus-ii.-scaena-vi.
actus-ii.-scaena-vii.
actus-ii.-scaena-viii.
actus-ii.-scaena-ix.
actus-ii.-scaena-x.
chorus.
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
actus-iii.-scaena-vii.
chorus.-1
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
actus-iv.-scaena-viii
actus-iv.-scaena-ix.
chorus.-2
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ix.
epilogus.
back
front
main
dramatis-personae.
prologus-stratophilus-thaltibius-praeco
prologus.
finis-prologi.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
actus-ii.-scaena-vi.
actus-ii.-scaena-vii.
actus-ii.-scaena-viii.
actus-ii.-scaena-ix.
chorus-per-familiam.
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
actus-iii.-scaena-vi.
chorus.-1
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
chorus.-2
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ix.
actus-v.-scaena-x.
actus-v.-scaena-xi.
actus-v.-scaena-xii.
actus-v.-scaena-xiii.
actus-v.-scaena-xiiii.
actus-v.-scaena-xv.
back
front
main
personae-dramatis.
prologus-ancilla
prologus
finis-prologi.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
actus-i.-scaena-v
actus-i.-scaena-vi.
actus-i.-scaena-vii.
actus-i.-scaena-viii.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
chorus.-1
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
chorus.-2
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
actus-iv.-scaena-viii.
chorus-seu-hymnus-lazari-morientis.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
back
front
main
dramatis-personae.
prologus-philochrysium
prologus.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
chorus-scholasticorum.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-ii.-scaena-iv.
actus-ii.-scaena-v.
actus-ii.-scaena-vi.
chorus.
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
chorus.-1
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
actus-iv.-scaena-viii.
actus-iv.-scaena-ix.
actus-iv.-scaena-x.
actus-iv.-scaena-xi.
actus-iv.-scaena-xii.
chorus.-iambico-dimetro.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ix.
actus-v.-scaena-ultima.
epilogus-per-gregem.
back
front
main
dramatis-personae.
prologus-cum-morione-dromella-ancilla
chorus-ex-aristippicae-scholae-auditoribus.
prologus-cum-morione.
actus-i.-scaena-i.
actus-i.-scaena-ii.
actus-i.-scaena-iii.
actus-i.-scaena-iv.
actus-i.-scaena-v.
chorus.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
chorus.-1
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iii.-scaena-iv.
actus-iii.-scaena-v.
chorus.-2
actus-iv.-scaena-i.
actus-iv.-scaena-ii.
actus-iv.-scaena-iii.
actus-iv.-scaena-iv.
actus-iv.-scaena-v.
actus-iv.-scaena-vi.
actus-iv.-scaena-vii.
actus-iv.-scaena-viii.
actus-iv.-scaena-ix.
actus-iv.-scaena-x.
chorus.-3
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iv.
actus-v.-scaena-v.
actus-v.-scaena-vi.
actus-v.-scaena-vii.
actus-v.-scaena-viii.
actus-v.-scaena-ix.
actus-v.-scaena-x.
actus-v.-scaena-xi.
actus-v.-scaena-xii.
actus-v.-scaena-xiii.
actus-v.-scaena-xiv.
back
front
main
personae.
chorvs.
actvs-primvs.
chorvs-i.
actvs-secvndvs.
chorvs-secvndvs.
actvs-tertivs.
i-ferrum-et-ignes-lictor-i-mortes-para.
chorvs-tertivs
actvs-qvartvs.
chorvs-qvartvs.
pars-nostri-melior-vulneraque-et-necem
actvs-qvintvs.
back
front
main
personae-dramatis.
chorus-civium-romanorum.
actus-primus
chorus.
actus-secundus.
chorus.-1
actus-tertius.
chorus.-2
actus-quartus.
chorus.-3
actus-quintus.
chorus.-4
back
front
main
finis-petitus-litibus-vestris-adest
pars-occidentis-usque-quo-oceanus-diem
i-dire-frater-infimi-proles-dei
back
front
main
prima-inventa-marte-doctus-plurimum
actus-tertius.
pars-ardet-animo-vindicare-sanguinem
chorus.
pars-castra-peditum-subdita-oxensternio
chorus-procerum-belli.
actus-quintus.
chorus.-1
chorus.-2
chorus.-3
back
front
main
argumentum-est-mali-importuna-celeritas.
back
front
main
chorus-iudaearum.
chorus-susianarum.
finis-tragediae-de-regina-edissa-sive-esther.
back
front
main
actvs-primi
scena-prima.
scena-secvnda.
scena-tertia.
scena-qvarta.
actvs-secvndvs.
scena-prima.-1
scena-secvnda.-1
scena-tertia.-1
scena-qvarta.-1
actvs-tertii
scena-prima.-2
scena-secvnda.-2
scena-tertia.-2
scena-qvarta.-2
actvs-qvarti
scena-prima.-3
scena-secvnda.-3
scena-tertia.-3
scena-qvarta.-3
actvs-qvintvs.
scena-prima.-4
scena-secvnda.-4
scena-tertia.-4
scena-qvarta.-4
scena-qvinta.
peroratio.
back
front
main
back
front
main
peroratio
back
front
main
interlocutores
argumentum-sub-iambis-hyponactiis
back
front
main
personae
codices
prologus
actvs-secvndvs
actvs-tertivs
actvs-qvartvs
actvs-qvintvs
back
front
main
personae.
epilogvs.
actvs-primvs.
actvs-secvndvs.
actvs-tertivs.
epilogvs.-1
back
front
main
dramatis-personae.
prologvs.
actus-i.-scena-ii.
actus-i.-scena-iii.
actus-i.-scena-iv.
actus-i.-scena-v.
actus-ii.-scena-i.
actus-ii.-scena-ii.
actus-ii.-scena-iii.
actus-ii.-scena-iv.
actus-ii.-scena-v.
actus-ii.-scena-vi.
actus-ii.-scena-vii.
actus-ii.-scena-viii.
actus-iii.-scena-i.
actus-iii.-scena-ii.
actus-iii.-scena-iii.
actus-iii.-scena-iv.
actus-iii.-scena-v.
actus-iii.-scena-vi.
actus-iii.-scena-vii.
actus-iv.-scena-i.
actus-iv.-scena-ii.
actus-iv.-scena-iii.
actus-iv.-scena-iiii.
actus-iv.-scena-v.
actus-v.-scena-i.
actus-v.-scena-ill
finis.
back
front
main
chorus-angiorum.
actvs-primvs.
chorus-anglorum.
actvs-secvndvs.
chorus-captivorum.
actvs-tertivs.
chorus.
actvs-qvartvs.
chorus.-1
chorus.-2
chorus.-stuarta.
chorus.-3
chorus.-4
actvs-qvintvs.
back
front
main
prologus-prior
comoedia-risus-inerit
argumentum.
prologus-posterior
dramatis-personae
scena-burdegalae
actus-i-scaena-i
actus-i-scaena-ii
actus-i-scaena-iii
actus-i-scaena-iv
actus-i-scaena-v
actus-i-scaena-vi
actus-i-scaena-viii
actus-ii-scaena-i
actus-ii-scaena-ii
actus-ii-scaena-iii
actus-ii-scaena-v
actus-ii-scaena-vi
actus-ii-scaena-vii
actus-ii-scaena-viii
actus-iii-scaena-i
actus-iii-scaena-ii
actus-iii-scaena-iii
actus-iii-scaena-v
actus-iii-scaena-vi
actus-iii-scaena-vii
actus-iii-scaena-viii
actus-iii-scaena-ix
actus-iii-scaena-x
actus-iii-scaena-xii
actus-iii-scaena-xiii
actus-iv-scaena-i
actus-iv-scaena-ii
actus-iv-scaena-iii
actus-iv-scaena-iv
actus-iv-scaena-v
actus-iv-scaena-vi
actus-iv-scaena-vii
actus-iv-scaena-viii
actus-iv-scaena-ix
i-live-not-but-i-die
i-live-to-love-and-love-to-live
actus-iv-scaena-x
actus-iv-scaena-xi
actus-iv-scaena-xii
actus-v-scaena-i
ile-knock-and-see.-ticke-tocke.-num-hae-theodori-aedes
actus-v-scaena-ii
actus-v-scaena-iii
actus-v-scena-iv
actus-v-scaena-v
actus-v-scaena-vi
actus-v-scaena-ix
i-love-that-sport-alife-but-first-ile-goe-and-pinne-this-foxe-taile-at
actus-v-scaena-x
actus-v-scaena-xi
actus-v-scaena-xii
epilogus
back
front
main
dramatis-personae
chorus.
actus-secundus.
actus-tertius.
actus-quartus.
actus-quintus.
back
front
main
actorvm-nomina.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv-scena-i
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-iv.-scena-v.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
back
front
main
dramatis-personae.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv-scena-ii.
actvs-iv.-scena-iii.
actvs-iv-scena-iv.-ii
actvs-v-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-v.
actvs-v.-scena-vi.
actvs-v.-scena-vii.
back
front
main
actorvm-nomina.
prologvs.
prologvs.-periocha
actvs-i.-scena-i.
i
actvs-i.-scena-ii.
i-2
actvs-i.-scena-iii.-ii
i-3
actvs-i.-scena-v.
i-4
actvs-ii.-scena-i.
i-5
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-v.-iii
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-v-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
back
front
main
actorvm-nomina.
prologvs.
comoediae-periocha.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv-scena-ii.
actvs-iv.-scena-iii.
actvs-iv-scena-iv.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iiii.
actvs-v.-scena-v.
peroratio.
back
front
main
actorvm-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v.-scena-i.
actvs-v-scena-ii.
actvs-v.-scena-iii.
actvs-v.-iv-scena-iv.
back
front
main
actus-1.-scena-1.
actus-1.-scena-2.
actus-1.-scena-3.
actus-1.-scena-4.
actus-2.-scena-1.
actus-2.-scena-2.
actus-2.-scena-3.
actus-3.-scena-1.
actus-3.-scena-3.
actus-4.-scena-i.
actus-4.-scena-3.
actus-5.-scena-1.
actus-5.-scena-2.
actus-5.-scena-3.
actus-5.-scena-4.
finis.
actus-1.
actus-2.
actus-3.
actus-4.
back
front
main
actorum-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.-potiphar.
actvs-ii.-scena-vi.
pars-aequa-amoris-tecum-ac-pariter-fieret-vt
actvs-ii.-scena-vii.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
i.-quis-est-qui-me-hem-here-tun-quoque-hic-eras-lyconide
actvs-iii.-scena.-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-iv.-scena-v.
actvs-iv.-scena-vi.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-vi.
actvs-v.-scena-vii.
actvs-v.-scena-viii.
peroratio.
back
front
main
actorum-nomina.
prologvs.
comoediae-periocha.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv-scena-iii.
actvs-iv.-scena-iv.
actvs-iv.-scena-v.
actvs-v-scena-i.
actvs-v-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-v.
actvs-v-scena-vi.
actvs-v.-scena-vii.
actvs-v.-scena-viii.
peroratio.
peroratio.-64
back
front
main
actorum-nomina.
prologvs.
comoediae-argvmentvm.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iiii.
actvs-i.-scena-v.
actvs-ii.-scena-i.
finis-vah-quot-iam-annos-cum-hoc-colluctatus-sum-malo.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iii.-scena-v.
actvs-iii.-scena-vi.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv-scena-iv.
actvs-iv.-scena-v.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-v.
actvs-v.-scena-vi.
actvs-v.-scena-vii.
peroratio.
back
front
main
actorum-nomina.
prologvs.
comoediae-argumentum.
i-2
actvs-i.-scena-i.
i-3
actvs-i.-scena-ii.
i-4
actvs-i.-scena-iii.
i-5
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-i.-1
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iii.-scena.-v.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv-scenaiv.
actvs-iv-scena-v.
actvs-iv.-scena-vi.
actvs-v-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v-scena-iv.
actvs-v.-scena-v.
actvs-v.-scena-vi.
peroratio.
back
front
main
actorvm-nomina.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v-scenav.
back
front
main
actorvm-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iii.-scena-v.
actvs-iv.-scena-i
actvs-iv.-scena-ii.-actv
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
back
front
main
actorum-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-i.-scena-vi.
actvs-i.-scena-vii.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v-scena-i.
actvs-v.-scena-iii.
actvs-v.-scena-iii.-1
actvs-v.-scena-iv.
actvs-v.-scena-v.
actvs-v.-scena-vi.
actvs-v.-scena-vii.
peroratio.
back
front
main
actorum-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v.-scena-i.
actvs-v-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-v.
peroratio.
back
front
main
actorum-nomina.
prologvs
comoediae-periocha.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-i.-scena-v.
actvs-i.-scena-vi.
actvs-i.-sgena-vii.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.
actvs-ii.-scena-vi.
actvs-ii.-scena-vii.
actvs-ii.-scena-viii.
actvs-iii.-scena-i.
actvs-iii.-scena.-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iii.-scena-v.
actvs-iii.-scena-vii.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv
actvs-iv.-scena-v.
actvs-iv.-scena-vi.
actvs-iv.-scena-vii.
actvs-iv.-scena-viii.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
actvs-v.-scena-v.
i-nunc-vxor-ac-deum-nos-destituisse-clamita.
actvs-v.-scena-vi.
peroratio
back
front
main
actorvm-nomina.
prologvs.
comoediae-periocha.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scenai
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
argumentum-vitae-meae-atque-corporis
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
peroratio.
back
front
main
actorvm-nomina.
actvs-i.-scena-i.
actvs-i.-scena-ii.
i-2
i-3
actvs-i.-scena-iii.
i-4
actvs-i.-scena-iv.
i-5
actvs-i.-scena-v.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v.-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iiii.
back
front
main
actorvm-nomina.
prologvs.
actvs-i.-scena-i.
actvs-i.-scena-ii.
actvs-i.-scena-iii.
actvs-i.-scena-iv.
actvs-ii.-scena-i.
actvs-ii.-scena-ii.
actvs-ii.-scena-iii.
actvs-ii.-scena-iv.
actvs-ii.-scena-v.
actvs-iii.-scena-i.
actvs-iii.-scena-ii.
actvs-iii.-scena-iii.
actvs-iii.-scena-iv.
actvs-iv.-scena-i.
actvs-iv.-scena-ii.
actvs-iv.-scena-iii.
actvs-iv.-scena-iv.
actvs-v-scena-i.
actvs-v.-scena-ii.
actvs-v.-scena-iii.
actvs-v.-scena-iv.
back
front
main
back
front
main
personae.
chorvs-ex-puellis-aegyptijs.
chorvs.
pars-maior-in-simplo-malae-in-duplo-bonae.
i-quem
i-2-cani-
i-3-mendacio
back
front
main
prologvs.
personae-dramatis
actus-i.-scena-i.
scena-ii.
scena-iii.
comoedia
scena-iiii.
chorvs.
actus-ii.-scena-i.
scena-ii.-1
scena-iii.-1
scena-iiii.-1
scena-v.
chorvs-ii.
actus-iii.-scena-i.
scena-ii.-2
scena-iii.-2
scena-iiii.-2
scena-v.-1
scena-vi.
scena-vii.
chorvs-iii.
actus-iiii.-scena-i.
scena-ii.-3
scena-iii.-3
scena-iii.-4
chorvs-iiii.
actus-v.-scena-i.
scena-ii.-4
scena-iii.-5
scena-iiii.-3
scena-v.-2
chorvs-v.
epilogvs.
back
front
main
prologvs
comoediae-quoque-dicam-quam-sint-utiles
chori-musarum-nobilis-docta-assecla
back
front
main
dramatis-personae.
actvs-primi
scena-i.
scena-ii.
actvs-secvndi.
scena-i.-1
scena-ii.-1
scena-iii.
actvs-tertii
scena-i.-2
actvs-qvarti
scena-i.-3
scena-ii.-2
scena-iii.-1
scena-iv.
actvs-qvinti
scena-i.-4
scena-ii.-3
scena-iii.-2
scena-iv.-1
back
front
main
chorus-ex-argiuis-brontes.
actvs-primvs.
chorvs.
actvs-secvndvs.
pars-tortuosos-callida-sibi-fodit-specus
chorvs.-1
actvs-tertivs.
chorvs.-2
actvs-qvartvs.
chorvs.-3
actvs-qvintvs.
i-dea-curru-delata-leui
back
front
main
personae-tragaediae.
actvs-primvs.
scena-prima.
scena-secunda.
scena-tertia.
scena-quarta.
scena-qvinta.
scena-sexta.
chorvs.
actvs-secvndvs.
scena-prima.-1
scena-secunda.-1
scena-tertia.-1
scena-quarta.-1
scena-quinta.
scena-sexta.-1
chorvs.-1
actvs-tertivs.
scena-prima.-2
scena-secunda.-2
scena-tertia.-2
scena-quarta.-2
scena-qvinta.-1
chorvs.-2
actvs-qvartvs.
scena-prima.-3
scena-secunda.-3
scena-tertia.-3
scena-quarta.-3
chorvs.-3
actvs-qvintvs.
scena-prima.-4
scena-secunda.-4
scena-tertia.-4
scena-qvinta.-2
back
front
main
personae.
i.-crispus-caesar-artemius-tribunus
actvs-primvs.
scena-prima.
scena-secunda.
scena-tertia.
scena-quarta.
chorvs.
actvs-secvndvs.
scena-prima.-1
scena-secunda.-1
scena-tertia.-1
scena-quarta.-1
chorvs.-1
finis-triumphi-luctus-est
actvs-tertivs.
scena-prima.-2
scena-secunda.-2
scena-tertia.-2
scena-quarta.-2
fabula-nepotum.-crispe-non-non-hoc-mihi
chorvs.-2
actvs-qvartvs.
scena-prima.-3
scena-secunda
scena-tertia.-3
scena-quarta.-3
scena-qvinta.
chorvs-militvm.
actvs-qvintvs.
scena-prima.-4
scena-secunda.-3
scena-iii.
i
scena-iv.
chorus.-en-regna-qui-tot-inclytus
back
front
main
personae-tragoediae.
i.-duuenuordius-brilensis-praetor.
actvs-i.-scena-i.
scena-ii.
fabula-megara-est-fabula-alecto-soror
scena-iii.
scena-iv.
actvs-ii.-scena-i.
scena-ii.-1
scena-iii.-1
scena-iv
scena-v.
chorvs
actvs-iii.-scena-i.
scena-ii.-2
scena-iii.-2
scena-iv.-1
chorus-gorcomianorum-lunnius-brederodius-n.-pici-fratres
i-mox-atri-carceris-laxa-fores
scena-v.-1
scena-vi.
chorvs-1
actvs-iv.-scena-i.
scena-ii.-3
scena-iii.-3
pars-aedibus-rapere-alterum-certet-meis.
scena-iv.-2
chorvs-2
actvs-v.-scena-i.
scena-ii.-4
scena-iii.-4
scena-iv.-3
back
front
main
personae-tragoediae
chorus-virginum.
chorus-exulum-catholicorum.
actvs-primvs.
scena-i.
scena-ii.
scena-iii.
scena-iv.
scena-v.
scena-vi.
prima-est-salutis-cura-regnorum-altera.
chorus.
actvs-secvndvs
scena-i.-1
scena-ii.-1
scena-iii.-1
scena-iv.-1
scena-v.-1
scena-vi.-1
scena-vii.
chorvs.
actvs-tertivs
scena-i.-2
pars-inde-promat.-brian.-regium-nutum-sequens
scena-ii.-2
scena-iii.-2
scena-iii.-3
scena-v.-2
scena-vi.-2
scena-vii.-1
scena-viii.
chorvs.-1
actvs-qvartvs
scena-i.-3
scena-ii.-3
scena-iii.-4
scena-iv.-2
scena-v.-3
scena-vi.-3
scena-vii.-2
i-lictor-istud-amputa-seni-caput.
scena-viii.-1
chorvs.-2
pars-belgiacas-incolet-oras
pars-italicos-incolet-agros
pars-occiduos-viset-iberos.
actvs-qvintvs.
scena-i.-4
scena-ii.-4
scena-iii.-5
scena-iv.-3
scena-v.-4
scena-vi.-4
scena-vii.-3
scena-viii.-2
scena-ix.
scena-x.
scena-xi.
back
front
main
personae-tragaediae.
argvmentvm.
actvs-primvs.-135
argumentum-actus-primi.
scena-i.
i-4
scena-ii.
i-5
scena-iii.
scena-iv.
scena-v.
scena-vi.
chorus-angelorvm.
chorus.
finis-actus-primi.
actvs-secvndvs.
argumentum-actus-secundi.
scena-i.-1
scena-ii.-1
scena-iii.-1
scena-iv.-1
pars-audienda.-theod.-crimine-in-dubio-licet
scena-v.-1
scena-vi.-1
chorus.-1
finis-actus-secundi.
actvs-tertivs.
argumentum-actus-tertij.
scena-i.-2
scena-ii.-2
scena-iii.-2
scena-iv.-2
scena-v.-2
chorus-angelorvm.-1
chorus-angelorum.
chorus.-2
finis-actus-tertij.
actvs-qvartvs.
argumentum-actus-quarti.
scena-i.-3
scena-ii.-3
scena-iii.-3
scena-iv.-3
scena-v.-3
scena-vi.-2
chorus.-3
finis-actus-quarti.
actvs-qvintvs.
argumentum-actus-quinti.
scena-i.-4
scena-ii.-4
scena-iii.-4
scena-iv.-4
scena-v.-4
scena-vi.-3
back
front
main
prologus
dramatis-personae
personae-mutae
actus-i.-scena-i
actus-i.-scena-ii
actus-i.-scena-iii
actus-i.-scena-iiii.
actus-i.-scena-v.
chorus-asclepiadaeus-glyconico-clausus
actus-ii.-scena-i.
actus-ii.-scena-ii.
actus-ii.-scena-iii.
actus-ii.-scena-iiii.
actus-ii.-scena-v.
actus-ii.-scena-vi
actus-ii.-scena-vii.
chorus-sapphicus
actus-iii.-scena-i.
actus-iii.-scena-ii.
actus-iii.-scena-iii.
actus-iii.-scena-iiii.
actus-iii.-scena-v.
actus-iil.-scena-vi.
actus-iii.-scena-vii.
actus-iii.-scena-viii.
actus-iii.-scena-ix.
actus-iii.-scena-x.
actus-iii.-scena-xi.
chorus-dimeter
actus-iv.-scena-i.
actus-iv.-scena-ii.
actus-iv.-scena-iii.
actus-iv.-scena-iiii.
actus-iv.-scena-v.
actus-iv.-scena-vi.
actus-iv.-scena-vii.
actus-iv.-scena-viii.
actus-iv.-scena-ix.
actus-iv.-scena-x.
actus-iv.-scena-ultima-xi.
chorus-dimeter-ex-psalmo-127-per-totam-raguelis-familiam-decantandus
actus-v.-scena-i.
actus-v.-scena-ii.
actus-v.-scena-iii.
actus-v.-scena-iiii.
actus-v.-scena-v.
actus-v.-scena-vi.
actus-v.-scena-vii.
actus-v.-scena-viii.
epilogus
back
front
main
i.
i.-1
i.-2
i.-3
i-regna-ruinis-involve
i-odii-poenas-persolve
i.-4
i.-5
i.-6
i-serve-romani-senatus
i-adora-romae-fasces
i.-7
i-flamininum-exire-mox-regno-iube
i-servitutem-quaere-romanos-ama
back
front
main
prologus
prima-scena
conclusio
back
front
main
personae
actvs-primvs.
chorvs
actvs-secvndvs
chorvs.
actvs-tertivs
chorvs.-1
actvs-qvartvs
chorvs.-2
actvs-quintvs
back
front
main
prologvs.
i-niquiores-linguals.-ioui-ita-exhibet
actvs-i.-scaena-i.
actus-i.-scaena-ii.
actus-ii.-scaena-i.
actus-ii.-scaena-ii.
actus-ii.-scaena-iii.
actus-iii.-scaena-i.
actus-iii.-scaena-ii.
actus-iii.-scaena-iii.
actus-iiii.-scaena-i.
actus-iiii.-scaena-ii.
actus-iiii.-scaena-iii.
actus-v.-scaena-i.
actus-v.-scaena-ii.
actus-v.-scaena-iii.
actus-v.-scaena-iiii.
actus-v.-scaena-v.
back
front
main
lvdionvm-nomenclatvrae.
scaena-secvnda.
actvs-secvndus
scaena-secvnda.-1
scaena-tertia.
scaena-qvarta.
actvs-tertivs.
scaena-secvnda.-2
scaena-tertia.-1
scaena-qvarta.-1
scaena-qvinta.
actvs-qvartvs.
scaena-secvnda.-3
scaena-tertia.-2
scaena-qvarta.-2
scaena-qvinta.-1
scaena-sexta.
scaena-septima.
scaena-octava.
actvs-quintvs.
scaena-secvnda.-4
pars-bona.-etiam-de-caetero-cavebo-ne
scaena-tertia.-3
scaena-qvarta.-3
prima-relicti-liberi-pariunt-egon
scaena-qvinta-.
i-in-te-sies-uno-immanior
i-iamiam-migrasse-prô-dolor.
i-ite-referte-eadem
i-imo-cruente.-tuos
i-ipsam-etiam-eripis-id
i-iubilat-atque-etiam
i-invictus-hercules-quidem
i-iuppiter-amoveat
i-illud-item-querimur
back
