@node
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@conversionCode=tf
@conversionMethod=provided
@converter=Dirk Roorda (Text-Fabric)
@description=name of part
@descriptionTf=Edition
@editor=Jan Bloemendal
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@language=la
@schema=TEI + translatin
@sourceFormat=TEI
@teiVersion=not specified
@title=Translatin (drama, 1500-1750))
@valueType=str
@version=0.0.1
@writtenBy=Text-Fabric
@dateWritten=2024-12-31T08:21:28+00:00Z

2060688	TEI header
Front
Main
PERSONAE.
INCIPIT
ARGUMENTUM.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
SCENA VII.
SCENA VIII.
SCENA IX.
SCENA X.
SCENA XI.
SCENA XII.
SCENA Xlll.
SCENA XIV.
SCENA XV.
SCENA XVI.
SCENA XVII.
SCENA XVIII.
SCENA XIX.
SCENA XX.
Back
TEI header
Front
Main
PERSONAE DRAMATIS.
ARGUMENTUM DRAMATIS.
ACTUS I
SCENA I.
Personae. Sigefridus cum Ducibus & Milite suo.
SCENA II.
Personae. Genovefa, & caelestes Genii.
SCENA III.
Personae. Benoni. Genovefa; Satyri, Personae mutae.
SCENA IV.
SCENA V.
Pars II*. Monomachia Achillis, & Hectoris exhibetur.
ACTUS II.
SCENA I.
Personae. Sigefridus, Golo, Ephebus Genovefae.
SCENA II.
Personae. Sigefridus, Charilus, & Philindus Ephebi.
SCENA III.
SCENA IV.
SCENA V.
Personae. Golo, Sigefridus, & duo Filii Golonis*.
Personae. Golo, Sigefridus, Filii   Golonis.
SCENA VI.
Personae. Lindus & Rinaldus Venatores.
SCENA VII.
Personae. Sigefridus   solus.
SCENA VIII.
Personae. Nuncius,   Chorus.
SCENA I.
SCENA II.
SCENA III.
Personae. Genovefa, & Benoni   Filius.
SCENA IV.
Personae. Sigefridus, Genovefa, Benoni, Venatores &c.
Back
TEI header
Front
Main
PERSONAE.
ACTUS I.
SCENA I.
SCENA II.
Incipit a se nobilis esse,
ACTUS II.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
SCENA VII.
ACTUS III.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
ACTUS IV.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
ACTUS V.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
Back
TEI header
Front
Main
Back
TEI header
Front
Main
PERSONAE.
PROLOGVS.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
EPILOGVS.
Back
TEI header
Front
Main
PROLOGUS cum argumento in Euripum Tragoediam.
PERSONAE DRAMATIS.
PERORATIO
Back
TEI header
Front
Main
PERSONAE.
ARGVMENTVM HEROICO VERSV REDDITVM.
ACTVS PRIMVS.
ACTVS SECVNDI
ACTVS SECVNDVS.
ACTVS TERTII SYNOPSIS.
ACTVS TERTIVS.
ACTVS QVARTI
Incipit, & dulci sanctos affatur amore:
ACTVS QVARTVS.
ACTVS QVINTI PERIOCHE.
ACTVS QVINTVS.
Back
17 div
TEI header
Front
Main
PERSONAE.
PROLOGVS.
PARS PRIMA.
PARS II.
PARS III.
PARS IIII.
PARS V.
Back
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
11 div
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
12 div
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
 SCENA QVINTA.
 ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
SCENA QVINTA.
SCENA SEXTA.
SCENA SEPTIMA.
ACTVS TERTIVS.
SCENA PRIMA.
 SCENA SECVNDA.
 SCENA TERTIA.
 SCENA QVARTA.
 SCENA QVINTA.
 SCENA SEXTA.
SCENA SEPTIMA.
ACTVS QVARTVS.
SCENA PRIMA.
 SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
SCENA QVINTA.
ACTVS QVINTVS.
SCENA PRIMA.
 SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
 SCENA QVINTA.
Back
40 div
TEI header
Front
Main
 PERSONAE.
ACTVS PRIMVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECVNDA.
 ACTVS TERTIVS
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
 SCENA QVINTA.
 SCENA SEXTA.
ACTVS QVARTVS.
SCENA PRIMA.
 SCENA SECVNDA.
SCENA TERTIA.
ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
 SCENA QVINTA.
SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
 SCENA NONA.
SCENA DECIMA.
Back
35 div
TEI header
Front
Main
PERSONAE.
PROLOGVS.
 ACTVS PRIMVS.
SCENA PRIMA.
 SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
SCENA QVINTA.
SCENA SEXTA.
 ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
 SCENA QVARTA.
SCENA QVINTA.
SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
SCENA NONA.
SCENA DECIMA.
SCENA VNDECIMA.
SCENA DVODECIMA.
 SCENA DECIMATERTIA.
 SCENA DECIMAQVARTA.
SCENA DECIMAQVINTA.
ACTVS TERTIVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
 SCENA QVINTA.
SCENA SEXTA.
 SCENA SEPTIMA.
SCENA OCTAVA.
SCENA NONA.
 ACTVS QVARTVS.
SCENA PRIMA.
 SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
 SCENA QVARTA.
 SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
SCENA NONA.
ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
 SCENA QVARTA.
SCENA QVINTA.
 SCENA SEXTA.
Back
57 div
TEI header
Front
Main
 PERSONAE.
ACTVS PRIMVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
 SCENA QVARTA.
SCENA QVINTA.
 ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
SCENA QVARTA.
SCENA QVINTA.
SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
SCENA NONA.
SCENA DECIMA.
ACTVS TERTIVS.
SCENA PRIMA.
SCENA SECVNDA.
 SCENA TERTIA.
 SCENA QVARTA.
SCENA QVINTA.
 SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
 SCENA NONA.
ACTVS QVARTVS.
SCENA PRIMA.
 SCENA SECVNDA.
SCENA TERTIA.
 SCENA QVARTA.
SCENA QVINTA.
 SCENA SEXTA.
SCENA SEPTIMA.
 SCENA OCTAVA.
SCENA NONA.
SCENA DECIMA.
SCENA VNDECIMA.
SCENA DVODECIMA.
 SCENA DECIMATERTIA.
 SCENA DECIMAQVARTA.
SCENA DECIMAQVINTA.
 ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
 SCENA QVARTA.
 SCENA QVINTA.
 SCENA SEXTA.
SCENA SEPTIMA.
SCENA OCTAVA.
SCENA NONA.
SCENA DECIMA.
SCENA VNDECIMA.
 SCENA DVODECIMA.
Back
62 div
TEI header
Front
Main
ACTUS I.
ACTUS II.
ACTUS III.
ACTUS IV.
ACTUS V.
Back
TEI header
Front
Main
Personae.
Pars Prima.
Scena Prima.
Personae. Mopsus, Ganserellus*.
Scena Secunda.
Personae. Vulpulus, Mopsus, Ganserellus.*
Scena Tertia.
Personae. Accedunt Rosindus, et Cervinus*.
Scena Quarta.
Scena Quinta.
Scena Sexta.
Scena Septima.
Scena Octava.
Personae. Vulpulus, Ganserellus*.
Scena Nona.
Scena Decima.
Personae. Vulpulus, duo Pueri Itali*.
Scena Undecima.
Pars Secunda.
Scena Prima.
Scena Secunda.
Scena Tertia.
Personae. Vulpulus, Rosindus, Cervinus*.
Scena Quarta.
Personae. Vulpulus, Rosindus*.
Scena Quinta.
Scena Sexta.
Personae. Vulpulus, Ganserellus*
Scena Septima.
Pars Tertia.
Scena Prima.
Personae. Vulpulus, Ganserellus*.
Scena Secunda.
Scena Tertia.
Personae. Heribertus, Rosindus, Eustachius, Vulpulus*.
Scena Quarta.
Scena Quinta.
Back
42 div
TEI header
Front
Main
Dramatis personae.
Prologus.
ACTVS PRIMI SCENA I.
ACTVS PRIMI SCENA II.
ACTVS PRIMI SCENA III.
ACTVS PRIMI SCENA IIII.
ACTVS PRIMI SCENA V.
ACTVS SECVNDI SCENA I.
ACTVS SECVNDI SCENA II.
ACTVS SECVNDI SCENA III.
ACTVS TERTII. SCENA I.
ACTVS TERTII SCENA II.
ACTVS QVARTI. SCENA I.
ACTVS QVARTI SCENA II.
ACTVS QVARTI SCENA III.
ACTVS QVINTI SCENA I.
ACTVS QVINTI SCENA II.
ACTVS QVINTI SCENA III.
Back
TEI header
Front
Main
PERSONAE (lb)
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGVS.
Tragoediae argumentum ob oculos subijciet.
Actus .I. Scena .I.
Scena .II.
Scena .III.
Scena. IIII.
Actus .II. Scena .I.
Scena .II.
Scena III.
Scena IIII.
Actus. III. Scena .1.
Scena .II.
Scena. III.
Scena IIII.
Actus. IIII. Scena. I.
Scena. II.
Scena. III.
Scena. IIII.
Actus. V. Scena .I.
Scena. II.
Scena. III.
Back
27 div
TEI header
Front
Main
PERSONAE DRAMATIS.
PROLOGVS.
ACTVS PRIMI
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
ACTVS SECVNDI,
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
ACTVS TERTII,
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
SCENA VI.
ACTVS QVARTI,
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
ACTVS QVINTI,
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
Errata sint uobis. Ite ad parandum iter.
SCENA VI.
SCENA VII.
EPILOGVS.
Back
TEI header
Front
Main
HET EERSTE BEDRYF
DE I. UITKOMSTE
DE II. UITKOMSTE
DE III. UITKOMSTE
DE IV. UITKOMSTE
DE V. UITKOMSTE
DE VI. UITKOMSTE
DE VII. UITKOMSTE
DE VIII. UITKOMSTE
HET TWEEDE BEDRYF
I. UITKOMSTE
II. UITKOMSTE
DE III. UITKOMSTE
IV. UITKOMSTE
HET DERDE BEDRYF
I. UITKOMSTE
DE II. UITKOMSTE
DE III. UITKOMSTE
DE IV. UITKOMSTE
DE V. UITKOMSTE
DE VI. UITKOMSTE
DE VII. UITKOMSTE
DE VIII. UITKOMSTE
DE IX. UITKOMSTE
Back
TEI header
Front
Main
Dramatis personae:
ACTUS PRIMUS.
ACTUS SECUNDUS.
ACTUS TERTIUS
ACTUS QUARTUS.
ACTUS QUINTUS.
Back
TEI header
Front
Main
PERSONAE.
ARGVMENTVM.
Actus. 1.
Scena. 1.
Actus 1. Scena 2.
Actus primi Scena   Tertia.
Actus primi: Scena   Quarta.
Actus secundus:
Scena Prima.
Actus secundus: Scena   Secunda.
Actus secundus. Scena   Tertia.
Actus secundus. Scena   Quarta.
Actus tertius.
Scena prima.
Actus Tertius. Scena   Secunda.
Actus Tertius.Scena   Tertia.
Actus tertius. Scena   Quarta.
Actus Tertius. Scena   Quinta.
Actus tertius. Scena   Sexta.
Actus Quarta.
Scena Prima.
Actus Quarta. Scena   Secunda.
Actus Quartus. Scena   Tertia.
Actus Quartus. Scena   Quarta.
Actus Quartus. Scena   Quinta.
Actus Quintus.
Scena Prima.
Actus Quintus. Scena   Secunda.
Actus Quintus. Scena   Tertia.
Actus Quintus. Scena   Quarta.
Actus Quintus. Scena   Quinta.
Actus Quintus. Scena   Sexta.
Back
TEI header
Front
Main
PROLOGVS.
PERIOCHA.
DRAMATIS PERSONAE.
Actus I. Scena I. Trimetri Iambici.
Actus I. Scena II. Trimetri.
Actus I. Scena III. Ejusdem rationis.
Actus I. Scena IV. Tetrametri Acatalectici.
Actus II. Scena I. Senarii.
Actus II. Scena II. Acatalectici.
Actus II. Scena III. Senarii.
Actus II. Scena IV. Trimetri Iambici.
Actus III. Scena I. Iamb. Trimetri.
Actus III. Scena II. Trochaici.
Actus III. Scena III. Iambici Acatalectici.
Actus III. Scena IV. Senarii.
Actus III. Scena V. Ejusdem rationis.
Actus III. Scena VI. Eadem cum superioribus.
Actus III. Scena VII. Quadrata, Anapaestica, Catalectica.
Actus IV. Scena I. Trimetri.
Actus IV. Scena II. Octonarii, unus Senarius.
Actus IV. Scena III. Trimetri.
Actus IV. Scena IV. Trimetri.
Actus IV. Scena V. Catalectici Trochaioi.
Actus IV. Scena VI. Trimetri.
Actus IV. Scena VIII. Ejusdem rationis.
Actus V. Scena I. Senarii.
Actus V. Scena II. Trochaici Tetrametri Catalectici.
Actus V. Scena III. Iambici Trimetri,
Actus V. Scena IV. Scazontes Iambici.
Actus V. Scena V. Scazontes Iambici.
Back
TEI header
Front
Main
ACTORVM NOMINA
PROLOGVS
ARGVMENTVM COMOEDIAE
ACTVS PRIMI SCAENA PRIMA
ACTVS PRIMI SCAENA SECVNDA
ACTVS PRIMI SCAENA TERTIA
ACTVS PRIMI SCAENA QVARTA
ACTVS SECVNDA SCAENA PRIMA
ACTVS SECVNDI SCAENA SECVNDA
ACTVS SECVNDI SCAENA TERTIA
ACTVS SECVNDI SCAENA QVARTA
ACTVS SECVNDI SCAENA QVINTA
ACTVS TERTII SCAENA PRIMA
ACTVS TERTII SCAENA SECVNDA
ACTVS TERTII SCAENA TERTIA
ACTVS TERTII SCAENA QVARTA
ACTVS TERTII SCAENA QVINTA
ACTVS QVARTI {SCAENA PRIMA}
ACTVS QVARTI SCAENA SECVNDA
ACTVS QVARTI SCAENA TERTIA
ACTVS QVARTI SCAENA QVARTA
ACTVS QVARTI SCAENA QVINTA
ACTVS QVARTI SCAENA SEXTA
ACTVS QVARTI SCAENA SEPTIMA
ACTVS QVINTI [SCAENA PRIMA]
ACTVS QVINTI SCAENA SECVNDA
ACTVS QVINTI SCAENA TERTIA
ACTVS QVINTI SCAENA QVARTA
ACTVS QVINTI SCAENA QVINTA
PERORATIO
Back
TEI header
Front
Main
Argumentum Comoediae.
Prologus.
Actus primus. [scaena prima.]
Actus primi Scaena II.
Actus primi Scena III.
Actus primi Scaena IIII.
Actus secundus [Scena I]
Actus Secundi Scena II.
Actus secundi Scena III
Actus secundi scena IIII.
Actus tertii scena prima.
Actus tertii scena II.
Actus tertii scena III.
Actus tertii Scena IIII.
Actus quartus.
Actus quarti scena II.
Actus IIII scena III.
Actus IIII Scena IIII.
Actus IIII Scena V.
Actus IIII Scena VI.
Actus Quintus
Actus V Scena II.
Actus V Scena III.
Actus V Scena IIII.
Actus V Scena V.
Actus V Scena VI.
Back
TEI header
Front
Main
Prologus.
Argumentum.
Actus 1.
Personae.
Interlocutores.
Actus primi Scena prima.
Actus primi Scena secunda.
Actus primi Scena tertia.
Actus primi Scena quarta.
Actus primi Scena quinta.
Actus secundi Scena prima.
Actus secundi Scena secunda.
Actus secundi Scena tertia.
Actus secundi Scena quarta.
Actus tertii Scena prima.
Actus tertii Scena secunda.
Actus tertij Scena tertia.
Actus tertij Scena quarta.
Actus tertij Scena quinta.
Actus quarti Scena prima.
Actus quarti Scena secunda.
Actus quarti Scena tertia.
Actus quarti Scena quarta.
Actus quinti Scena prima.
Actus quinti Scena secunda.
Actus quinti Scena tertia.
Act. quinti Sce. quarta, & vltima.
Peroratio.
Back
TEI header
Front
Main
Prologus
Actus primi scena sexta.
Actus secundi, scena prima
Back
TEI header
Front
Main
Prologus
Actus primi scena secunda
Back
TEI header
Front
Main
PERSONAE
PROLOGVS.
ARGVMENTVM ACTVS I.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ARGVMENTVM ACTVS II.
ACTUS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IIII.
ARGVMENTVM ACTVS III.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA iiii.
ACTVS III. SCENA V.
ACTUS III. SCENA VI.
ARGVMENTVM ACTVS IIII.
ACTVS IIII. SCENA I.
ACTVS IIII. SCENA II.
ACTVS IIII. SCENA III.
ACTVS IIII. SCENA IIII.
ACTVS IIII. SCENA V.
ACTVS IIII. SCENA VI.
ARGVMENTVM ACTVS V.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
Back
32 div
TEI header
Front
Main
ACTUS PRIMUS.
ACTUS SECUNDUS.
ACTUS III.
ACTUS IIII.
ACTUS QUINTUS.
Back
TEI header
Front
Main
PERSONAE.
ACTUS PRIMUS.
ACTUS SECUNDUS.
ACTUS TERTIUS.
ACTUS QUARTUS.
ACTUS QUINTUS.
Back
TEI header
Front
Main
INTERLOCUTORES
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
Prologus
PERIOCHA
ACTUS I.
SCENA I.
ARGUMENTUM SCENAE.
ACTUS. I. SCENA II.
ARGUMENTUM.
ACTUS I. SCENA III.
ARGUMENTUM.
ACTUS I. SCENA IIII.
ARGUMENTUM.
ACTUS I. SCENA V.
ARGUMENTUM.
ACTUS II.
SCENA I.
ARGUMENTUM.
ACTUS II. SCENA II.
ARGUMENTUM.
ACTUS II. SCENA III.
ARGUMENTUM.
ACTUS II. SCENA IIII.
ARGUMENTUM.
ACTUS II. SCENA V.
ARGUMENTUM.
ACTUS III.
SCENA I.
ARGUMENTUM.
ACTUS III. SCENA II.
ARGUMENTUM.
ACTUS III. SCENA III.
ARGUMENTUM.
ACTUS III. SCENA IIII.
ARGUMENTUM.
ACTUS III. SCENA V.
ARGUMENTUM.
ACTUS IIII.
SCENA I.
ARGUMENTUM.
ACTUS IIII. SCENA II.
ARGUMENTUM.
ACTUS IIII. SCENA III.
ARGUMENTUM.
ACTUS IIII. SCENA IIII.
ARGUMENTUM.
ACTUS IIII. SCENA V.
ARGUMENTUM.
ACTUS V.
SCENA I.
ARGUMENTUM.
ACTUS V. SCENA II.
ARGUMENTUM.
ACTUS V. SCENA III.
ARGUMENTUM.
ACTUS V. SCENA IIII.
ARGUMENTUM.
ACTUS V. SCENA V.
ARGUMENTUM.
Back
TEI header
Front
Main
PERSONAE TRAGOEDIAE
ACTUS PRIMUS.
ACTUS II. SCENA I.
SCENA II.
ACTUS. III. SCENA. I.
SCENA. II.
ACTUS QUARTUS. SCENA I.
SCENA II.
SCENA. III.
ACTUS. V.
Back
15 div
TEI header
Front
Main
 PERSONAE. 
 ACTUS PRIMUS. 
ACTUS SECUNDUS.
ACTUS TERTIUS.
ACTUS QUARTUS. 
ACTUS QUINTUS.
Back
TEI header
Front
Main
PROLOGVS IN CATHARINAM.
ARGVMENTVM.
Personae Tragoediae.
ACTVS PRIMI
SCENA .I.
ACTVS PRIMI,
SCENA .II.
ACTVS. I. SCENA. III.
ACTVS. I. SCENA. IIII.
ACTVS. I. SCENA. V.
ACTVS PRIMI,
SCENA. VI.
ACTVS SECVNDI
SCENA PRIMA.
ACTVS. II. SCENA. II.
ACTVS. II. SCENA. III.
ACTVS. II. SCENA. IIII.
ACTVS II. SCENA.V.
ACTVS TERTII
SCENA PRIMA.
ACTVS. III. SCENA. II.
ACTVS. III. SCENA. III.
ACTVS. III. SCENA. IIII.
ACTVS QVARTI
SCENA PRIMA.
ACTVS QVARTI,
SCENA. II.
ACTVS. IIII. SCENA. III.
ACTVS. IIII. SCENA. IIII.
ACTVS. IIII. SCENA. V.
ACTVS QVINTI
SCENA PRIMA.
ACTVS. V. SCENA. II.
ACTVS. V. SCENA. III.
ACTVS. V. SCENA. IIII.
ACTVS. V. SCENA. V.
ACTVS. V. SCENA. VI.
ACTVS. V. SCENA. VII.
ACTVS QVINTI
SCENA. VIII.
Back
TEI header
Front
Main
PROLOGVS
ARGVMENTVM.
Personae actionis.
ACTVS. I. SCENA. II.
ACTVS. I. SCENA. III.
ACTVS. I. SCENA. IIII.
ACTVS. I. SCENA. V.
ACTVS.I. SCENA. VI.
ACTVS SECVNDI.
SCENA PRIMA.
ACTVS. II. SCENA. II.
ACTVS. II. SCENA. III.
ACTVS. II. SCENA. IIII.
ACTVS II. SCENA. V.
ACTVS. II. SCENA. VI.
ACTVS. II. SCENA. VII.
ACTVS TERTII, SCENA I.
ACTVS. III. SCENA. II.
ACTVS. III. SCENA. III.
ACTVS. III. SCENA. IIII.
ACTVS. III. SCENA. V.
ACTVS. III. SCENA. VI.
ACTVS. III. SCENA.VII.
ACTVS TERTII SCENA. VIII.
ACTVS QVARTI SCENA PRIMA.
ACTVS. IIII. SCENA. II.
ACTVS. IIII. SCENA. III.
ACTVS. IIII. SCENA. IIII.
ACTVS. IIII. SCENA. V.
ACTVS IIII. SCENA.VI.
ACTVS QVINTI SCENA PRIMA.
ACTVS QVINTI SCENA. II.
ACTVS QVINTI SCENA. III.
ACTVS. V. SCENA. IIII.
ACTVS. V. SCENA. V.
ACTVS. V. SCENA. VI.
ACTVS. V. SCENA. VII.
ACTVS QVINTI, SCENA. VIII.
ACTVS QVINTI, SCENA. IX.
ACTVS. V. SCENA VLTIMA.
Back
TEI header
Front
Main
PERSONAE.
SCENA PRIMA. ACTVS PRIMVS.
SCENA SECVNDA.
ACTVS SECVNDVS.
Errata sic condonat, & scelerum pius
ACT. TERT. SCENA. PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
ACT. QVART. SCEN. PRIM.
ACT. V. SCEN. I.
Back
TEI header
Front
Main
PROLOGVS.
Argumentum.
Actus secundus.
Tertius actus
Conclusio.
(2230) Errata siqua sint tolerate aut mungite.
Back
TEI header
Front
Main
PROLOGVS
ACTVS PRIMI.
SCENA PRIMA.
Actus primi. Scena secunda.
Actus primi. Scena tertia.
Actus primi. Scena quarta.
Actus secundus. Scena prima.
Actus secundi. Scena secunda.
Actus secundi. Scena tertia.
Actus tertij. Scena prima.
Actus tertij. Scena secunda.
Actus tertij. Scena tertia.
Actus tertij. Scena quarta.
Actus quarti. Scena prima.
Actus quarti. Scena secunda.
Actus quarti. Scena tertia
Actus quinti. Scena prima.
Actus quinti. Scena secunda.
Actus quinti: Scena tertia.
Actus quinti. Scena quarta.
Actus quinti: Scena quinta.
Back
26 div
TEI header
Front
Main
INTERLOQVVTORES
PROLOGVS
ACTVS I.
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
ACTVS II.
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
 SCENA V.
ACTVS III.
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
ACTVS IIII.
SCENA I.
SCENA II
ACTUS V
SCENA I.
SCENA II.
SCENA III.
SCENA IIII.
SCENA V.
SCENA VI.
SCENA VII.
Back
34 div
TEI header
Front
Main
Prologus in Codrum feliciter incipit.
Argumentum.
Back
TEI header
Front
Main
Back
TEI header
Front
Main
Actorum nomina.
Epilogus. Populus Aegyptius. Demus.
PROLOGVS.
Actus primi Scena prima.
Actus secundi Scena prima.
Scena 2. Septenarii & Octonarii.
Scena 4. Scazontes.
Actus 3. Scena 1a Senarii.
Scena tertia Senarii.
Scena 7. Scazontes.
Scena 8. Trochaici Trimetri.
Actus 4. Scena I. Senarii Iamb.
Scena 2. Trochaici Senarii.
Scena 3. Trimetri Iambici.
Scena 4. Septenarii.
Scena 5. Trimetri.
Scena 6. Eiusdem generis cum superioribus
Scena 7. Trimetri Iamb.
Scena 8. Similis farinae vsus.
Scena 9. Octonarii admistis Septe¬
Scena 10. Trimetri Iambici.
Scena II. Vt superiores.
Scena XII.
Scena XIII. Eiusdem generis vt sup.
Actus 5. Scena I.
Scena 2. Trimetri, vt superiores.
Scena 4. Trimetri.
Scena 5. Senarii Iamb.
Scena 6. Eiusdem generis.
Scena 7. Trimetri.
Scena 8. Similis farinae.
Scena 9.
Scena 10. Octonarii vt supra.
Epilogus, seu Peroratio.
Back
39 div
TEI header
Front
Main
Personae Dramatis.
ARGVMENTVM COMOEDIAE.
Prologus in Militem.
ACTVS PRIMI, SCENA PRIMA.
ARGVMENTVM.
ACTVS PRIMI, SCENA SECVNDA.
ARGVMENTVM.
ACTVS I. SCENA III.
ARGVMENTVM.
ACTVS PRIMI, SCENA QYARTA
ARGVMENTVM.
ACTVS PRIMI, SCENA QVINTA,
ARGVMENTVM.
ACTVS SECVNDI, SCENA PRIMA.
ARGVMENTVM.
ACTVS SECVNDI, SCENA SECVNDA.
ARGVMENTVM.
ACTVS SECVNDI, SCENA TERTIA.
ARGVMENTVM.
ACTVS SECVNDI, SCENA QVARTA.
ARGVMENTVM.
ACTVS SECVNDI, SCENA QVINTA
ARGVMENTVM.
ACTVS SECVNDI, SCENA SEXTA.
ARGVMENTVM.
ACTVS TERTII, SCENA PRIMA.
ARGVMENTVM.
ACTVS TERTII, SCENA SECVNDA.
ARGVMENTVM.
ACTVS TERTII, SCENA TERTIA.
ARGVMENTVM.
ACTVS TERTII, SCENA QVARTA.
ARGVMENTVM.
ACTVS TERTII, SCENA QVINTA.
ACTVS TERTII, SCENA SEXTA,
ARGVMENTVM.
ACTVS QVARTI, SCENA PRIMA.
ACTVS IIII, SCENA SECVNDA.
ACTVS QVARTI, SCENA TERTIA.
ACTVS IIII, SCENA QVARTA
ACTVS QVINTI, SCENA PRIMA.
ACTVS V SCENA SECVNDA
ACTVS V. SCENA III. ET VLTIMA.
Epilogus.
Back
49 div
TEI header
Front
Main
Prologus silentium a spectatoribus precatur.
ACTVS SECVNDVS.
TERTIVS ACTVS
ACTVS QVARTVS.
Back
9 div
TEI header
Front
Main
ACTVS PRIMVS.
ACTVS SECVNDVS
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS
Back
TEI header
Front
Main
ACTVS PRIMI
Scena Prima.
ACTVS II.
ACTVS III.
ACTVS IIII.
ACTVS V.
Back
TEI header
Front
Main
ACTVS PRIMVS
ACTVS SECVNDVS
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
TEI header
Front
Main
Actus primi. Scena Ia.
ACTVS 2. 
ACTVS 3.
ACTVS 4.
ACTVS 5.
Back
TEI header
Front
Main
ACTVS PRIMVS
ACTVS SECVNDVS
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS
Back
TEI header
Front
Main
ACTVS PRIMVS
ACTVS SECVNDVS.
ACTVS TERTIVS
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
TEI header
Front
Main
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS
Back
TEI header
Front
Main
PROLOGUS.
PERSONAE dramatis seu diverbii Actus primi
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS I. SCAENA V.
ACTUS I. SCAENA VI.
ACTUS I. SCAENA VII.
PERSONAE dramatis in secundo Actu.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA interiectitia.
ACTUS II. Residuum SCAENAE III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
PERSONAE dramatis Actus tertii.
ACTUS III. SCAENA I.
ACTUS III. SCAENA interiectitia.
ACTUS III. Residuum SCAENAE I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS III. SCAENA VII.
ACTUS III. SCAENA VIII.
ACTUS III. SCAENA Interiectitia
ACTUS III. SCAENA altera Interiectitia.
ACTUS III. Residuum SCAENAE VIII.
ACTUS III. SCAENA IX.
ACTUS III. SCAENA X.
ACTUS III. SCAENA XI.
PERSONAE dramatis Actus quarti.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
Dramatis PERSONAE in quinto Actu.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCANEA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
ACTUS V. SCAENA X.
ACTUS V. SCAENA XI.
ACTUS V. SCAENA XII.
ACTUS V. SCAENA XIII.
ACTUS V. SCAENA XIV.
ACTUS V. SCAENA XV.
ACTUS V. SCAENA XVI.
ACTUS V. SCAENA XVII.
EPILOGUS, per quemlibet dicendus aut canendus.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS IN ALUTAM cum MORO.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS I. SCAENA V.
ACTUS I. SCAENA VI.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
Prologus.
Actus primi. Scena prima.
ACTUS I. SCENA II.
Actus primi Scena tertia.
Actus primi. Scena quarta.
Actus II. Scena I.
Actus secundi. Scena secunda.
Actus secundi. Scena tertia.
Actus secundi. Scena quarta.
Actus III Scena I.
Actus tertij scena secunda.
Actus tertij Scena tertia.
Actus tertij Scena quarta.
ACTUS IIII. SCENA I.
Actus quarti. Scena secunda.
ACTUS IIII. SCENA III.
Scena quarta. Actus quarti.
Actus quarti Scena quinta.
Actus quinti. Scena prima.
Actus quinti Scena secunda.
Actus V. Scena tertia.
Actus quinti Scena quarta.
Actus quinti Scena quinta.
Actus quinti Scena sexta.
Actus quinti Scena septima.
Actus quinti Scena octava.
Actus quinti Scena nona.
ACTUS quinti. SCAENA decima.
ACTUS quinti. SCAENA undecima.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS III. SCAENA VII.
ACTUS III. SCAENA VIII.
ACTUS III. SCAENA IX.
ACTUS III. SCAENA X.
ACTUS III. SCAENA XI.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA ULTIMA.
Back
TEI header
Front
Main
ACTORES FABULAE.
PROLOGUS.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS III. SCAENA VII.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
Back
TEI header
Front
Main
PERSONAE DRAMATIS,
PROLOGUS in Hecastum.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS II. SCAENA VI.
ACTUS II. SCAENA VII.
ACTUS II. SCAENA VIII.
ACTUS II. SCAENA IX.
ACTUS II. SCAENA X.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS III. SCAENA VII.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
ACTUS V. SCAENA X.
ACTUS V. SCAENA XI.
ACTUS V. SCAENA XII, INTERIECTITIA.
ACTUS V. SCAENA XIII.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS II. SCAENA VI.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS.
Personae erunt tristemque habebunt exitum.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS II. SCAENA VI.
ACTUS II. SCAENA VII.
ACTUS II. SCAENA VIII.
ACTUS II. SCAENA IX.
ACTUS II. SCAENA X.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS III. SCAENA VII.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII
ACTUS IV. SCAENA IX.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
EPILOGUS.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS II. SCAENA VI.
ACTUS II. SCAENA VII.
ACTUS II. SCAENA VIII.
ACTUS II. SCAENA IX.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS III. SCAENA VI.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
ACTUS V. SCAENA X.
ACTUS V. SCAENA XI.
ACTUS V. SCAENA XII.
ACTUS V. SCAENA XIII.
ACTUS V. SCAENA XIIII.
ACTUS V. SCAENA XV.
Back
TEI header
Front
Main
PERSONAE DRAMATIS.
PROLOGUS
(60) Errata quamvis minima, non defenderit.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS I. SCAENA V
ACTUS I. SCAENA VI.
ACTUS I. SCAENA VII.
ACTUS I. SCAENA VIII.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS II. SCAENA IV.
ACTUS II. SCAENA V.
ACTUS II. SCAENA VI.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII.
ACTUS IV. SCAENA IX.
ACTUS IV. SCAENA X.
ACTUS IV. SCAENA XI.
ACTUS IV. SCAENA XII.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
ACTUS V. SCAENA ULTIMA.
EPILOGUS per GREGEM.
Back
TEI header
Front
Main
DRAMATIS PERSONAE.
PROLOGUS cum MORIONE.
ACTUS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS I. SCAENA III.
ACTUS I. SCAENA IV.
ACTUS I. SCAENA V.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS III. SCAENA IV.
ACTUS III. SCAENA V.
ACTUS IV. SCAENA I.
ACTUS IV. SCAENA II.
ACTUS IV. SCAENA III.
ACTUS IV. SCAENA IV.
ACTUS IV. SCAENA V.
ACTUS IV. SCAENA VI.
ACTUS IV. SCAENA VII.
ACTUS IV. SCAENA VIII.
ACTUS IV. SCAENA IX.
ACTUS IV. SCAENA X.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IV.
ACTUS V. SCAENA V.
ACTUS V. SCAENA VI.
ACTUS V. SCAENA VII.
ACTUS V. SCAENA VIII.
ACTUS V. SCAENA IX.
ACTUS V. SCAENA X.
ACTUS V. SCAENA XI.
ACTUS V. SCAENA XII.
ACTUS V. SCAENA XIII.
ACTUS V. SCAENA XIV.
Back
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
TEI header
Front
Main
Personae dramatis.
Actus Primus
Actus secundus.
Actus tertius.
Actus quartus.
Actus quintus.
Back
TEI header
Front
Main
ACTUS I
Scena I
Scena II
ACTVS II
SCENA I
ACTVS III
SCENA I
Scena II
Scena III
Scena IV
ACTVS IV
Scena I
Scena II
ACTVS V
Back
TEI header
Front
Main
 Personae tragoediae.
Actus primus.
 Actus secundus.
Actus tertius.
 Actus quartus.
Actus quintus.
Back
TEI header
Front
Main
Prologus
Actus primi scaena prima
Actus primi scaena secunda
Actus primi scaena tertia
Actus primi scaena quarta
Actus secundi scaena prima
Actus secundi scaena secunda
Actus secundi scaena tertia
Actus secundi scaena quarta
Actus tertii scaena prima
Actus tertii scaena secunda
Actus tertii scaena tertia
Argumentum est mali importuna celeritas.
Actus tertii scaena quarta
Actus tertii scaena quinta
Actus quarti scaena prima
Actus quarti scaena secunda
Actus quarti scaena tertia
Actus quarti scaena quarta
Actus quinti scaena prima
Actus quinti scaena secunda
Actus quinti scaena tertia
Actus quinti scaena quarta
Actus quinti scaena quinta
Actus quinti scaena sexta
Actus quinti scaena septima
Peroratio
Back
TEI header
Front
Main
Personae sive interloquutores huius dramatis.
Actus primus
Actus secundus
Actus tertius
Actus quartus
Actus quintus*
Peroratio
Back
12 div
TEI header
Front
Main
INTERLOQVVTORES.
ACTVS PRIMI
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
ACTVS TERTII
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
Errata dones plurima?
ACTVS QVARTI
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECVNDA.
SCENA TERTIA.
SCENA QVARTA.
SCENA QVINTA.
PERORATIO.
Back
TEI header
Front
Main
Back
5 div
TEI header
Front
Main
PERORATIO
Back
TEI header
Front
Main
Interlocutores
Argumentum sub iambis   hyponactiis
ACTUS PRIMUS
ACTUS SECUNDUS
Back
TEI header
Front
Main
PERSONAE
PROLOGUS
ACTVS SECVNDVS
ACTVS TERTIVS
ACTVS QVARTVS
ACTVS QVINTVS
Back
11 div
TEI header
Front
Main
PERSONAE.
PROLOGVS.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
EPILOGVS.
Back
TEI header
Front
Main
Dramatis personae.
PROLOGVS.
Actus I. Scaena I.
Actus I. Scena II.
Actus I. Scena III.
Actus I. Scena IV.
Actus I. Scena V.
Actus II. Scena I.
Actus II. Scena II.
Actus II. Scena III.
Actus II. Scena IV.
Actus II. Scena V.
Actus II. Scena VI.
Actus II. Scena VII.
Actus II. Scena VIII.
Actus III. Scena I.
Actus III. Scena II.
Actus III. Scena III.
Actus III. Scena IV.
Actus III. Scena V.
Actus III. Scena VI.
Actus III. Scena VII.
Actus IV. Scena I.
Actus IV. Scena II.
Actus IV. Scena III.
Actus IV. Scena IIII.
Actus IV. Scena V.
Actus V. Scena I.
Actus V. Scena II.
Actus V. Scena Ill
Errata quaedam sic corrigantur.
Back
TEI header
Front
Main
TRAGOEDIAE INTERLOCVTORES.
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
TEI header
Front
Main
PROLOGUS PRIOR |
argumentum.
PROLOGUS POSTERIOR
DRAMATIS PERSONAE
personae mutae
ACTUS I, SCAENA i
ACTUS I, SCAENA ii
ACTUS I, SCAENA iii
ACTUS I, SCAENA iv
ACTUS I, SCAENA v
ACTUS I, SCAENA vi
ACT I, SCAENA vii
ACTUS I, SCAENA viii
ACTUS II, SCAENA i
ACTUS II, SCAENA ii
ACTUS II, SCAENA iii
ACT II, SCAENA iv
ACTUS II, SCAENA v
ACTUS II, SCAENA vi
ACTUS II, SCAENA vii
ACTUS II, SCAENA viii
ACTUS III, SCAENA i
ACTUS III, SCAENA ii
ACTUS III, SCAENA iii
ACT III, SCAENA iv
ACTUS III, SCAENA v
ACTUS III, SCAENA vi
ACTUS III, SCAENA vii
ACTUS III, SCAENA viii
ACTUS III, SCAENA ix
ACTUS III, SCAENA x
ACT III, SCAENA xi
ACTUS III, SCAENA xii
ACTUS III, SCAENA xiii
ACTUS IV, SCAENA i
ACTUS IV, SCAENA ii
ACTUS IV, SCAENA iii
ACTUS IV, SCAENA iv
ACTUS IV, SCAENA v
ACTUS IV, SCAENA vi
ACTUS IV, SCAENA vii
ACTUS IV, SCAENA viii
ACTUS IV, SCAENA ix
ACTUS IV, SCAENA x
ACTUS IV, SCAENA xi
ACTUS IV, SCAENA xii
ACTUS V, SCAENA i
ACTUS V, SCAENA ii
ACTUS V, SCAENA iii
ACTUS V, SCENA iv
ACTUS V, SCAENA v
ACTUS V, SCAENA vi
ACTUS V, SCAENA vii
ACTUS V, SCAENA viii
ACTUS V, SCAENA ix |
ACTUS V, SCAENA x
ACTUS V, SCAENA xi
ACTUS V, SCAENA xii
EPILOGUS
Back
TEI header
Front
Main
Dramatis Personae
ACTUS PRIMUS.
ACTUS SECUNDUS.
ACTUS TERTIUS.
ACTUS QUARTUS.
ACTUS QUINTUS.
Back
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV SCENA I
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS IV. SCENA V.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
Back
30 div
TEI header
Front
Main
Dramatis personae.
ARGVMENTVM IN BAPTIsten, Carmine heroico redditum.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV SCENA II.
ACTVS IV. SCENA III.
ACTVS IV SCENA IV. [< II]
ACTVS V SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
ACTVS V. SCENA VII.
Back
34 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS. [= PERIOCHA]
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III. [< II]
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA V. [<III]
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS V SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
Back
24 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
COMOEDIAE PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV SCENA II.
ACTVS IV. SCENA III.
ACTVS IV SCENA IV.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IIII.
ACTVS V. SCENA V.
PERORATIO.
Back
30 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V. SCENA I.
ACTVS V SCENA II.
ACTVS V. SCENA III.
ACTVS V. [< IV] SCENA IV.
Back
28 div
TEI header
Front
Main
 Actorum Nomina.
Actus 1. Scena 1.
Actus 1. Scena 2.
Actus 1. Scena 3.
Actus 1. Scena 4.
Actus 2. Scena 1.
Actus 2. Scena 2.
Actus 2. Scena 3.
Actus 3. Scena 1.
 Actus 3. Scena 2.
Actus 3. Scena 3.
Actus 4. Scena 1.
 Actus 4. Scena 2.
Actus 4. Scena 3.
Actus 5. Scena 1.
Actus 5. Scena 2.
Actus 5. Scena 3.
Actus 5. Scena 4.
Actus 1.
Actus 2.
Actus 3.
Actus 4.
Back
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V. POTIPHAR.
ACTVS II. SCENA VI.
ACTVS II. SCENA VII.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA. IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS IV. SCENA V.
ACTVS IV. SCENA VI.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
ACTVS V. SCENA VII.
ACTVS V. SCENA VIII.
PERORATIO.
Back
39 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
Comoediae Periocha.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV SCENA III.
ACTVS IV. SCENA IV.
ACTVS IV. SCENA V.
ACTVS V SCENA I.
ACTVS V SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V SCENA VI.
ACTVS V. SCENA VII.
ACTVS V. SCENA VIII.
PERORATIO.
PERORATIO. 64
Back
35 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
COMOEDIAE ARGVMENTVM.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IIII.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS III. SCENA V.
ACTVS III. SCENA VI.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV SCENA IV.
ACTVS IV. SCENA V.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
ACTVS V. SCENA VII.
PERORATIO.
Back
35 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
Comoediae argumentum.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS III. SCENA. V.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV SCENAIV.
ACTVS IV SCENA V.
ACTVS IV. SCENA VI.
ACTVS V SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
PERORATIO.
Back
35 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V SCENAV.
Back
28 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS III. SCENA V.
ACTVS IV. SCENA I
ACTVS IV. SCENA II. [< ACTV]
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
Back
28 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS I. SCENA VI.
ACTVS I. SCENA VII.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
ACTVS V. SCENA VII.
PERORATIO.
Back
34 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V. SCENA I.
ACTVS V SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
PERORATIO.
Back
31 div
TEI header
Front
Main
Actorum nomina.
PROLOGVS
COMOEDIAE PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS I. SCENA VI.
ACTVS I. SCENA VII.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V.
ACTVS II. SCENA VI.
ACTVS II. SCENA VII.
ACTVS II. SCENA VIII.
ACTVS III. SCENA I.
ACTVS III. SCENA. II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS III. SCENA V.
ACTVS III. SCENA VII.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV
ACTVS IV. SCENA V.
ACTVS IV. SCENA VI.
ACTVS IV. SCENA VII.
ACTVS IV. SCENA VIII.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
ACTVS V. SCENA V.
ACTVS V. SCENA VI.
PERORATIO
Back
44 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
COMOEDIAE PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENAI
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
Argumentum vitae meae, atque corporis
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
PERORATIO.
Back
25 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS I. SCENA V.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V. SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IIII.
Back
29 div
TEI header
Front
Main
ACTORVM NOMINA.
PROLOGVS.
PERIOCHA.
ACTVS I. SCENA I.
ACTVS I. SCENA II.
ACTVS I. SCENA III.
ACTVS I. SCENA IV.
ACTVS II. SCENA I.
ACTVS II. SCENA II.
ACTVS II. SCENA III.
ACTVS II. SCENA IV.
ACTVS II. SCENA V.
ACTVS III. SCENA I.
ACTVS III. SCENA II.
ACTVS III. SCENA III.
ACTVS III. SCENA IV.
ACTVS IV. SCENA I.
ACTVS IV. SCENA II.
ACTVS IV. SCENA III.
ACTVS IV. SCENA IV.
ACTVS V SCENA I.
ACTVS V. SCENA II.
ACTVS V. SCENA III.
ACTVS V. SCENA IV.
Back
29 div
TEI header
Front
Main
PROLOGUS AD SPECTATORES.
ARGUMENTUM.
ACTUS I. SCENA I.
ACTUS I. SCENA II.
ACTUS I. SCENA. III.
ACTUS II. SCENA I.
ACTUS II SCENA II.
ACTUS II. SCENA III.
ACTUS II. SCENA IIII.
ACTUS II. SCENA V.
ACTUS III. SCENA I.
ACTUS III. SCENA II.
ACTUS III. SCENA III.
ACTUS III. SCENA IIII.
ACTUS IIII. SCENA I.
ACTUS IIII. SCENA II.
ACTUS IIII. SCENA III.
ACTUS IIII. SCENA III.
ACTUS V. SCENA I.
ACTUS V. SCENA II.
ACTUS V. SCENA III.
ACTUS V. SCENA IIII.
ACTUS V. SCENA V.
ACTUS V. SCENA VI.
ACTUS V. SCENA VII.
ACTUS V. SCENA VIII.
EPILOGUS.
Back
TEI header
Front
Main
Personae.
Back
6 div
TEI header
Front
Main
PROLOGVS.
PERSONAE DRAMATIS
PERIOCHA.
Actus I. Scena I.
Scena II.
Scena III.
Scena IIII.
Actus II. Scena I.
Scena II.
Scena III.
Scena IIII.
Scena V.
Actus III. Scena I.
Scena II.
Scena III.
Scena IIII.
Scena V.
Scena VI.
Scena VII.
Actus IIII. Scena I.
Scena II.
Scena III.
Scena III.
Actus V. Scena I.
Scena II.
Scena III.
Scena IIII.
Scena V.
EPILOGVS.
Back
TEI header
Front
Main
PROLOGVS
INTERLOCUTORES.
ACTUS I. SCENA I.
ACTUS I. SCENA II.
ACTUS I. SCENA III.
ACTUS I. SCENA IIII.
ACTUS II. SCENA I.
ACTUS II. SCENA II.
ACTUS II. SCENA III.
ACTUS II. SCENA IIII.
ACTUS II. SCENA V.
ACTUS II. SCENA VI.
ACTUS III. SCENA I.
ACTUS III. SCENA II.
ACTUS III. SCENA III.
ACTUS III. SCENA IIII.
ACTUS III. SCENA V.
ACTUS IIII. SCENA I.
ACTUS IIII. SCENA II.
ACTUS IIII. SCENA III.
ACTUS IIII. SCENA IIII.
ACTUS IIII. SCENA V.
ACTUS V. SCENA I.
ACTUS V. SCENA II.
ACTUS V. SCENA III.
ACTUS V. SCENA IIII.
ACTUS V. SCENA V.
EPILOGUS
Errata singulorum tangunt, vitiaque,
Back
TEI header
Front
Main
Dramatis Personae.
ACTVS PRIMI
SCENA I.
SCENA II.
ACTVS SECVNDI.
SCENA I.
SCENA II.
SCENA III.
ACTVS TERTII
SCENA I.
ACTVS QVARTI
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
ACTVS QVINTI
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
Back
TEI header
Front
Main
ACTVS PRIMVS.
ACTVS SECVNDVS.
ACTVS TERTIVS.
ACTVS QVARTVS.
ACTVS QVINTVS.
Back
10 div
TEI header
Front
Main
Personae Tragaediae.
ACTVS PRIMVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
SCENA QVINTA.
SCENA SEXTA.
ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
SCENA QUINTA.
SCENA SEXTA.
ACTVS TERTIVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
SCENA QVINTA.
ACTVS QVARTVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QVINTA.
Back
TEI header
Front
Main
PERSONAE.
ACTVS PRIMVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
ACTVS SECVNDVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
ACTVS TERTIVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA TERTIA.
SCENA QUARTA.
ACTVS QVARTVS.
SCENA PRIMA.
SCENA SECUNDA:
SCENA TERTIA.
SCENA QUARTA.
SCENA QVINTA.
ACTVS QVINTVS.
SCENA PRIMA.
SCENA SECUNDA.
SCENA III.
SCENA IV.
Back
TEI header
Front
Main
PERSONAE TRAGOEDIAE.
ACTVS I. SCENA I.
SCENA II.
SCENA III.
SCENA IV.
ACTVS II. SCENA I.
SCENA II.
SCENA III.
SCENA IV
SCENA V.
ACTVS III. SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
ACTVS IV. SCENA I.
SCENA II.
SCENA III.
SCENA IV.
ACTVS V. SCENA I.
SCENA II.
SCENA III.
SCENA IV.
Back
TEI header
Front
Main
Personae Tragoediae
ACTVS PRIMVS.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
ACTVS SECVNDVS
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
SCENA VII.
ACTVS TERTIVS
SCENA I.
SCENA II.
SCENA III.
SCENA III.
SCENA V.
SCENA VI.
SCENA VII.
SCENA VIII.
ACTVS QVARTVS
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
SCENA VII.
SCENA VIII.
ACTVS QVINTVS.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
SCENA VII.
SCENA VIII.
SCENA IX.
SCENA X.
SCENA XI.
Back
TEI header
Front
Main
Personae Tragaediae.
ARGVMENTVM.
ACTVS PRIMVS.
Argumentum Actus primi.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
ACTVS SECVNDVS.
Argumentum Actus secundi.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
ACTVS TERTIVS.
Argumentum Actus Tertij.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
ACTVS QVARTVS.
Argumentum Actus Quarti.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
ACTVS QVINTVS.
Argumentum Actus Quinti.
SCENA I.
SCENA II.
SCENA III.
SCENA IV.
SCENA V.
SCENA VI.
Back
TEI header
Front
Main
Prologus
Dramatis personae
Personae mutae
Actus I. Scena I
Actus I. Scena II
Actus I. Scena III
Actus I. Scena IIII.
Actus I. Scena V.
Actus II. Scena I.
Actus II. Scena II.
Actus II. Scena III.
Actus II. Scena IIII.
Actus II. Scena V.
Actus II. Scena VI
Actus II. Scena VII.
Actus III. Scena I.
Actus III. Scena II.
Actus III. Scena III.
Actus III. Scena IIII.
Actus III. Scena V.
Actus IIl. Scena VI.
Actus III. Scena VII.
Actus III. Scena VIII.
Actus III. Scena IX.
Actus III. Scena X.
Actus III. Scena XI.
Actus IV. Scena I.
Actus IV. Scena II.
Actus IV. Scena III.
Actus IV. Scena IIII.
Actus IV. Scena V.
Actus IV. Scena VI.
Actus IV. Scena VII.
Actus IV. Scena VIII.
Actus IV. Scena IX.
Actus IV. Scena X.
Actus IV. Scena ultima (XI).
Actus V. Scena I.
Actus V. Scena II.
Actus V. Scena III.
Actus V. Scena IIII.
Actus V. Scena V.
Actus V. Scena VI.
Actus V. Scena VII.
Actus V. Scena VIII.
Epilogus
Back
TEI header
Front
Main
Personae
Prologus
Actus primus
Scena prima
Scena secunda
Scena tertia
Scena quarta
Scena quinta
Scena sexta
Scena septima
Actus secundus
Scena prima
Scena secunda
Scena tertia
Scena quarta
Scena quinta
Actus tertius
Scena prima
Scena secunda
Scena tertia
Scena quarta
Scena quinta
Scena sexta
Actus quartus
Scena prima
Scena secunda
Scena tertia
Scena quarta
Scena quinta
Actus quintus
Scena prima
Scena secunda
Scena tertia
Scena quarta
Scena quinta
Scena sexta
Scena septima
Scena octava
Back
TEI header
Front
Main
Prologus
Prima scena
SECUNDA SCENA
TERTIA SCENA
QUARTA SCENA
QUINTA SCENA
SEXTA SCENA
CONCLUSIO
Back
TEI header
Front
Main
PERSONAE
ACTVS PRIMVS.
ACTVS SECVNDVS
ACTVS TERTIVS
ACTVS QVARTVS
ACTVS QUINTVS
Back
TEI header
Front
Main
PROLOGVS.
PERIOCHA.
DRAMATIS PERSONAE
ACTVS I. SCAENA I.
ACTUS I. SCAENA II.
ACTUS II. SCAENA I.
ACTUS II. SCAENA II.
ACTUS II. SCAENA III.
ACTUS III. SCAENA I.
ACTUS III. SCAENA II.
ACTUS III. SCAENA III.
ACTUS IIII. SCAENA I.
ACTUS IIII. SCAENA II.
ACTUS IIII. SCAENA III.
ACTUS V. SCAENA I.
ACTUS V. SCAENA II.
ACTUS V. SCAENA III.
ACTUS V. SCAENA IIII.
ACTUS V. SCAENA V.
Back
TEI header
Front
Main
PROLOGVS
PERIOCHA.
ACTVS PRIMVS.
SCAENA SECVNDA.
ACTVS SECVNDUS
SCAENA SECVNDA.
SCAENA TERTIA.
SCAENA QVARTA.
ACTVS TERTIVS.
SCAENA SECVNDA.
SCAENA TERTIA.
SCAENA QVARTA.
SCAENA QVINTA.
ACTVS QVARTVS.
SCAENA SECVNDA.
SCAENA TERTIA.
SCAENA QVARTA.
SCAENA QVINTA.
SCAENA SEXTA.
SCAENA SEPTIMA.
SCAENA OCTAVA.
ACTVS QUINTVS.
SCAENA SECVNDA.
SCAENA TERTIA.
SCAENA QVARTA.
SCAENA QVINTA .
Back
