@node
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@conversionCode=tf
@conversionMethod=provided
@converter=Dirk Roorda (Text-Fabric)
@description=name of part
@descriptionTf=Edition
@editor=Jan Bloemendal
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@language=la
@schema=TEI + translatin
@sourceFormat=TEI
@teiVersion=not specified
@title=Translatin (drama, 1500-1750))
@valueType=str
@version=0.0.1
@writtenBy=Text-Fabric
@dateWritten=2025-02-19T13:25:30+00:00Z

2063027	TEI header
Front
Main
1. PERSONAE.
2. INCIPIT
3. ARGUMENTUM.
4. SCENA I.
5. SCENA II.
6. SCENA III.
7. SCENA IV.
8. SCENA V.
9. SCENA VI.
10. SCENA VII.
11. SCENA VIII.
12. SCENA IX.
13. SCENA X.
14. SCENA XI.
15. SCENA XII.
16. SCENA Xlll.
17. SCENA XIV.
18. SCENA XV.
19. SCENA XVI.
20. SCENA XVII.
21. SCENA XVIII.
22. SCENA XIX.
23. SCENA XX.
Back
TEI header
Front
Main
1. PERSONAE DRAMATIS.
2. ARGUMENTUM DRAMATIS.
3. ACTUS I
4. SCENA I.
5. Personae. Sigefridus cum Ducibus & Milite suo.
6. SCENA II.
7. Personae. Genovefa, & caelestes Genii.
8. SCENA III.
9. Personae. Benoni. Genovefa; Satyri, Personae mutae.
10. SCENA IV.
11. SCENA V.
12. Pars II*. Monomachia Achillis, & Hectoris   exhibetur.
13. ACTUS II.
14. SCENA I.
15. Personae. Sigefridus, Golo, Ephebus Genovefae.
16. SCENA II.
17. Personae. Sigefridus, Charilus, & Philindus   Ephebi.
18. SCENA III.
19. SCENA IV.
20. SCENA V.
21. Personae. Golo, Sigefridus, & duo Filii Golonis*.
22. Personae. Golo, Sigefridus,   Filii Golonis.
23. SCENA VI.
24. Personae. Lindus & Rinaldus Venatores.
25. SCENA VII.
26. Personae. Sigefridus   solus.
27. SCENA VIII.
28. Personae. Nuncius,   Chorus.
30. SCENA I.
32. SCENA II.
33. SCENA III.
34. Personae. Genovefa, &   Benoni Filius.
35. SCENA IV.
36. Personae. Sigefridus, Genovefa, Benoni, Venatores   &c.
Back
TEI header
Front
Main
1. PERSONAE.
2. ACTUS I.
3. SCENA I.
4. SCENA II.
8. Incipit a se nobilis esse,
9. ACTUS II.
10. SCENA I.
11. SCENA II.
12. SCENA III.
13. SCENA IV.
14. SCENA V.
15. SCENA VI.
16. SCENA VII.
29. ACTUS III.
30. SCENA I.
31. SCENA II.
32. SCENA III.
36. SCENA IV.
45. ACTUS IV.
46. SCENA I.
48. SCENA II.
54. SCENA III.
55. SCENA IV.
59. ACTUS V.
60. SCENA I.
61. SCENA II.
62. SCENA III.
63. SCENA IV.
Back
TEI header
Front
Main
Back
TEI header
Front
Main
1. PERSONAE.
3. PROLOGVS.
4. ACTVS PRIMVS.
6. ACTVS SECVNDVS.
8. ACTVS TERTIVS.
9. EPILOGVS.
Back
TEI header
Front
Main
1. PROLOGUS cum argumento in Euripum Tragoediam.
2. PERSONAE DRAMATIS.
13. PERORATIO
Back
TEI header
Front
Main
1. PERSONAE.
3. ARGVMENTVM HEROICO VERSV REDDITVM.
4. ACTVS PRIMVS.
6. ACTVS SECVNDI
7. ACTVS SECVNDVS.
10. ACTVS TERTII SYNOPSIS.
11. ACTVS TERTIVS.
13. ACTVS QVARTI
14. Incipit, & dulci sanctos affatur amore:
15. ACTVS QVARTVS.
19. ACTVS QVINTI PERIOCHE.
20. ACTVS QVINTVS.
Back
17 div
TEI header
Front
Main
1. PERSONAE.
2. PROLOGVS.
3. PARS PRIMA.
4. PARS II.
5. PARS III.
6. PARS IIII.
7. PARS V.
Back
TEI header
Front
Main
1. PERSONAE.
3. ACTVS PRIMVS.
5. ACTVS SECVNDVS.
7. ACTVS TERTIVS.
9. ACTVS QVARTVS.
11. ACTVS QVINTVS.
Back
11 div
TEI header
Front
Main
1. PERSONAE.
3. ACTVS PRIMVS.
5. ACTVS SECVNDVS.
6. ACTVS SECVNDVS.
8. ACTVS TERTIVS.
10. ACTVS QVARTVS.
13. ACTVS QVINTVS.
Back
12 div
TEI header
Front
Main
1. PERSONAE.
2. ACTVS PRIMVS.
4. ACTVS SECVNDVS.
6. ACTVS TERTIVS.
8. ACTVS QVARTVS.
11. ACTVS QVINTVS.
Back
TEI header
Front
Main
1. PERSONAE.
3. ACTVS PRIMVS.
4. SCENA PRIMA.
5. SCENA SECVNDA.
6.  SCENA TERTIA.
7. SCENA QVARTA.
8.  SCENA QVINTA.
10.  ACTVS SECVNDVS.
11. SCENA PRIMA.
12. SCENA SECVNDA.
13. SCENA TERTIA.
14. SCENA QVARTA.
15. SCENA QVINTA.
16. SCENA SEXTA.
17. SCENA SEPTIMA.
19. ACTVS TERTIVS.
20. SCENA PRIMA.
21.  SCENA SECVNDA.
22.  SCENA TERTIA.
23.  SCENA QVARTA.
24.  SCENA QVINTA.
25.  SCENA SEXTA.
26. SCENA SEPTIMA.
28. ACTVS QVARTVS.
29. SCENA PRIMA.
30.  SCENA SECVNDA.
31. SCENA TERTIA.
32. SCENA QVARTA.
33. SCENA QVINTA.
35. ACTVS QVINTVS.
36. SCENA PRIMA.
37.  SCENA SECVNDA.
38.  SCENA TERTIA.
39. SCENA QVARTA.
40.  SCENA QVINTA.
Back
40 div
TEI header
Front
Main
1.  PERSONAE.
3. ACTVS PRIMVS.
4. SCENA PRIMA.
5. SCENA SECVNDA.
6. SCENA TERTIA.
8. ACTVS SECVNDVS.
9. SCENA PRIMA.
10. SCENA SECVNDA.
12.  ACTVS TERTIVS
13. SCENA PRIMA.
15. SCENA SECVNDA.
19.  SCENA TERTIA.
20. SCENA QVARTA.
21.  SCENA QVINTA.
22.  SCENA SEXTA.
24. ACTVS QVARTVS.
25. SCENA PRIMA.
26.  SCENA SECVNDA.
27. SCENA TERTIA.
29. ACTVS QVINTVS.
30. SCENA PRIMA.
31. SCENA SECVNDA.
32.  SCENA TERTIA.
33. SCENA QVARTA.
34.  SCENA QVINTA.
35. SCENA SEXTA.
36. SCENA SEPTIMA.
37. SCENA OCTAVA.
38.  SCENA NONA.
39. SCENA DECIMA.
Back
35 div
TEI header
Front
Main
1. PERSONAE.
2. PROLOGVS.
3.  ACTVS PRIMVS.
4. SCENA PRIMA.
5.  SCENA SECVNDA.
6.  SCENA TERTIA.
7. SCENA QVARTA.
8. SCENA QVINTA.
9. SCENA SEXTA.
10.  ACTVS SECVNDVS.
11. SCENA PRIMA.
12. SCENA SECVNDA.
13.  SCENA TERTIA.
14.  SCENA QVARTA.
15. SCENA QVINTA.
16. SCENA SEXTA.
17. SCENA SEPTIMA.
18. SCENA OCTAVA.
19. SCENA NONA.
20. SCENA DECIMA.
21. SCENA VNDECIMA.
22. SCENA DVODECIMA.
23.  SCENA DECIMATERTIA.
24.  SCENA DECIMAQVARTA.
25. SCENA DECIMAQVINTA.
26. ACTVS TERTIVS.
27. SCENA PRIMA.
28. SCENA SECVNDA.
29. SCENA TERTIA.
30. SCENA QVARTA.
31.  SCENA QVINTA.
32. SCENA SEXTA.
33.  SCENA SEPTIMA.
34. SCENA OCTAVA.
35. SCENA NONA.
36.  ACTVS QVARTVS.
37. SCENA PRIMA.
38.  SCENA SECVNDA.
39. SCENA TERTIA.
40. SCENA QVARTA.
41.  SCENA QVARTA.
42.  SCENA SEXTA.
43. SCENA SEPTIMA.
44. SCENA OCTAVA.
45. SCENA NONA.
46. ACTVS QVINTVS.
47. SCENA PRIMA.
48. SCENA SECVNDA.
49. SCENA TERTIA.
50.  SCENA QVARTA.
51. SCENA QVINTA.
52.  SCENA SEXTA.
Back
57 div
TEI header
Front
Main
1.  PERSONAE.
3. ACTVS PRIMVS.
4. SCENA PRIMA.
5. SCENA SECVNDA.
6. SCENA TERTIA.
7.  SCENA QVARTA.
8. SCENA QVINTA.
10.  ACTVS SECVNDVS.
11. SCENA PRIMA.
12. SCENA SECVNDA.
13.  SCENA TERTIA.
14. SCENA QVARTA.
15. SCENA QVINTA.
16. SCENA SEXTA.
17. SCENA SEPTIMA.
18. SCENA OCTAVA.
19. SCENA NONA.
20. SCENA DECIMA.
22. ACTVS TERTIVS.
23. SCENA PRIMA.
24. SCENA SECVNDA.
25.  SCENA TERTIA.
26.  SCENA QVARTA.
27. SCENA QVINTA.
28.  SCENA SEXTA.
29. SCENA SEPTIMA.
30. SCENA OCTAVA.
31.  SCENA NONA.
33. ACTVS QVARTVS.
34. SCENA PRIMA.
35.  SCENA SECVNDA.
36. SCENA TERTIA.
37.  SCENA QVARTA.
38. SCENA QVINTA.
39.  SCENA SEXTA.
40. SCENA SEPTIMA.
41.  SCENA OCTAVA.
42. SCENA NONA.
43. SCENA DECIMA.
44. SCENA VNDECIMA.
45. SCENA DVODECIMA.
46.  SCENA DECIMATERTIA.
47.  SCENA DECIMAQVARTA.
48. SCENA DECIMAQVINTA.
50.  ACTVS QVINTVS.
51. SCENA PRIMA.
52. SCENA SECVNDA.
53. SCENA TERTIA.
54.  SCENA QVARTA.
55.  SCENA QVINTA.
56.  SCENA SEXTA.
57. SCENA SEPTIMA.
58. SCENA OCTAVA.
59. SCENA NONA.
60. SCENA DECIMA.
61. SCENA VNDECIMA.
62.  SCENA DVODECIMA.
Back
62 div
TEI header
Front
Main
1. ACTUS I.
2. ACTUS II.
3. ACTUS III.
4. ACTUS IV.
5. ACTUS V.
Back
TEI header
Front
Main
1. Personae.
2. Pars Prima.
3. Scena Prima.
4. Personae. Mopsus, Ganserellus*.
5. Scena Secunda.
6. Personae. Vulpulus, Mopsus, Ganserellus.*
7. Scena Tertia.
8. Personae. Accedunt Rosindus, et Cervinus*.
9. Scena Quarta.
10. Scena Quinta.
11. Scena Sexta.
12. Scena Septima.
13. Scena Octava.
14. Personae. Vulpulus, Ganserellus*.
15. Scena Nona.
16. Scena Decima.
17. Personae. Vulpulus, duo Pueri Itali*.
18. Scena Undecima.
19. Pars Secunda.
20. Scena Prima.
21. Scena Secunda.
22. Scena Tertia.
23. Personae. Vulpulus, Rosindus, Cervinus*.
24. Scena Quarta.
25. Personae. Vulpulus, Rosindus*.
26. Scena Quinta.
27. Scena Sexta.
28. Personae. Vulpulus, Ganserellus*
29. Scena Septima.
30. Pars Tertia.
31. Scena Prima.
32. Personae. Vulpulus, Ganserellus*.
33. Scena Secunda.
34. Scena Tertia.
35. Personae. Heribertus, Rosindus, Eustachius,   Vulpulus*.
36. Scena Quarta.
37. Scena Quinta.
Back
42 div
TEI header
Front
Main
1. Dramatis personae.
2. Prologus.
4. ACTVS PRIMI SCENA I.
5. ACTVS PRIMI SCENA II.
6. ACTVS PRIMI SCENA III.
7. ACTVS PRIMI SCENA IIII.
8. ACTVS PRIMI SCENA V.
9. ACTVS SECVNDI SCENA I.
10. ACTVS SECVNDI SCENA II.
11. ACTVS SECVNDI SCENA III.
13. ACTVS TERTII. SCENA I.
14. ACTVS TERTII SCENA II.
15. ACTVS QVARTI. SCENA I.
16. ACTVS QVARTI SCENA II.
17. ACTVS QVARTI SCENA III.
18. ACTVS QVINTI SCENA I.
19. ACTVS QVINTI SCENA II.
20. ACTVS QVINTI SCENA III.
Back
TEI header
Front
Main
1. PERSONAE (lb)
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGVS.
3. Tragoediae argumentum ob oculos subijciet.
4. Actus .I. Scena .I.
5. Scena .II.
6. Scena .III.
7. Scena. IIII.
9. Actus .II. Scena .I.
10. Scena .II.
11. Scena III.
12. Scena IIII.
14. Actus. III. Scena .1.
15. Scena .II.
16. Scena. III.
17. Scena IIII.
19. Actus. IIII. Scena. I.
20. Scena. II.
21. Scena. III.
22. Scena. IIII.
24. Actus. V. Scena .I.
25. Scena. II.
26. Scena. III.
Back
27 div
TEI header
Front
Main
1. PERSONAE DRAMATIS.
2. PROLOGVS.
3. ACTVS PRIMI
4. SCENA I.
5. SCENA II.
6. SCENA III.
7. SCENA IIII.
8. SCENA V.
9. ACTVS SECVNDI,
10. SCENA I.
11. SCENA II.
12. SCENA III.
13. SCENA IIII.
14. SCENA V.
15. ACTVS TERTII,
16. SCENA I.
18. SCENA II.
19. SCENA III.
20. SCENA IIII.
21. SCENA V.
22. SCENA VI.
23. ACTVS QVARTI,
24. SCENA I.
25. SCENA II.
26. SCENA III.
27. SCENA IIII.
28. SCENA V.
29. ACTVS QVINTI,
30. SCENA I.
31. SCENA II.
32. SCENA III.
33. SCENA IIII.
34. SCENA V.
35. Errata sint uobis. Ite ad parandum iter.
36. SCENA VI.
37. SCENA VII.
38. EPILOGVS.
Back
TEI header
Front
Main
Back
TEI header
Front
Main
1. Dramatis personae:
6. ACTUS PRIMUS.
8. ACTUS SECUNDUS.
10. ACTUS TERTIUS
12. ACTUS QUARTUS.
14. ACTUS QUINTUS.
Back
TEI header
Front
Main
1. PERSONAE.
2. ARGVMENTVM.
3. Actus. 1.
4. Scena. 1.
5. Actus 1. Scena 2.
6. Actus primi Scena   Tertia.
7. Actus primi: Scena   Quarta.
8. Actus secundus:
9. Scena Prima.
10. Actus secundus: Scena   Secunda.
11. Actus secundus. Scena   Tertia.
12. Actus secundus. Scena   Quarta.
13. Actus tertius.
14. Scena prima.
15. Actus Tertius. Scena   Secunda.
16. Actus Tertius.Scena   Tertia.
17. Actus tertius. Scena   Quarta.
18. Actus Tertius. Scena   Quinta.
19. Actus tertius. Scena   Sexta.
20. Actus Quarta.
21. Scena Prima.
22. Actus Quarta. Scena   Secunda.
23. Actus Quartus. Scena   Tertia.
24. Actus Quartus. Scena   Quarta.
25. Actus Quartus. Scena   Quinta.
26. Actus Quintus.
27. Scena Prima.
28. Actus Quintus. Scena   Secunda.
29. Actus Quintus. Scena   Tertia.
30. Actus Quintus. Scena   Quarta.
31. Actus Quintus. Scena   Quinta.
32. Actus Quintus. Scena   Sexta.
Back
TEI header
Front
Main
1. PROLOGVS.
3. PERIOCHA.
4. DRAMATIS PERSONAE.
6. Actus I. Scena I. Trimetri Iambici.
7. Actus I. Scena II. Trimetri.
8. Actus I. Scena III. Ejusdem rationis.
9. Actus I. Scena IV. Tetrametri Acatalectici.
10. Actus II. Scena I. Senarii.
11. Actus II. Scena II. Acatalectici.
12. Actus II. Scena III. Senarii.
13. Actus II. Scena IV. Trimetri Iambici.
14. Actus III. Scena I. Iamb. Trimetri.
15. Actus III. Scena II. Trochaici.
16. Actus III. Scena III. Iambici Acatalectici.
17. Actus III. Scena IV. Senarii.
18. Actus III. Scena V. Ejusdem rationis.
19. Actus III. Scena VI. Eadem cum superioribus.
20. Actus III. Scena VII. Quadrata, Anapaestica,   Catalectica.
21. Actus IV. Scena I. Trimetri.
22. Actus IV. Scena II. Octonarii, unus Senarius.
23. Actus IV. Scena III. Trimetri.
24. Actus IV. Scena IV. Trimetri.
25. Actus IV. Scena V. Catalectici Trochaioi.
26. Actus IV. Scena VI. Trimetri.
27. Actus IV. Scena VIII. Ejusdem rationis.
29. Actus V. Scena I. Senarii.
30. Actus V. Scena II. Trochaici Tetrametri Catalectici.
31. Actus V. Scena III. Iambici Trimetri,
32. Actus V. Scena IV. Scazontes Iambici.
33. Actus V. Scena V. Scazontes Iambici.
Back
TEI header
Front
Main
1. ACTORVM NOMINA
2. PROLOGVS
3. ARGVMENTVM COMOEDIAE
4. ACTVS PRIMI SCAENA PRIMA
5. ACTVS PRIMI SCAENA SECVNDA
6. ACTVS PRIMI SCAENA TERTIA
7. ACTVS PRIMI SCAENA QVARTA
8. ACTVS SECVNDA SCAENA PRIMA
9. ACTVS SECVNDI SCAENA SECVNDA
10. ACTVS SECVNDI SCAENA TERTIA
11. ACTVS SECVNDI SCAENA QVARTA
12. ACTVS SECVNDI SCAENA QVINTA
13. ACTVS TERTII SCAENA PRIMA
14. ACTVS TERTII SCAENA SECVNDA
15. ACTVS TERTII SCAENA TERTIA
16. ACTVS TERTII SCAENA QVARTA
17. ACTVS TERTII SCAENA QVINTA
18. ACTVS QVARTI {SCAENA PRIMA}
19. ACTVS QVARTI SCAENA SECVNDA
20. ACTVS QVARTI SCAENA TERTIA
21. ACTVS QVARTI SCAENA QVARTA
22. ACTVS QVARTI SCAENA QVINTA
23. ACTVS QVARTI SCAENA SEXTA
24. ACTVS QVARTI SCAENA SEPTIMA
25. ACTVS QVINTI [SCAENA PRIMA]
26. ACTVS QVINTI SCAENA SECVNDA
27. ACTVS QVINTI SCAENA TERTIA
28. ACTVS QVINTI SCAENA QVARTA
29. ACTVS QVINTI SCAENA QVINTA
30. PERORATIO
Back
TEI header
Front
Main
1. Argumentum Comoediae.
2. Prologus.
3. Actus primus. [scaena prima.]
4. Actus primi Scaena II.
5. Actus primi Scena III.
6. Actus primi Scaena IIII.
7. Actus secundus [Scena I]
8. Actus Secundi Scena II.
9. Actus secundi Scena III
10. Actus secundi scena IIII.
11. Actus tertii scena prima.
12. Actus tertii scena II.
13. Actus tertii scena III.
14. Actus tertii Scena IIII.
15. Actus quartus.
16. Actus quarti scena II.
17. Actus IIII scena III.
18. Actus IIII Scena IIII.
19. Actus IIII Scena V.
20. Actus IIII Scena VI.
21. Actus Quintus
22. Actus V Scena II.
23. Actus V Scena III.
24. Actus V Scena IIII.
25. Actus V Scena V.
26. Actus V Scena VI.
Back
TEI header
Front
Main
1. Prologus.
2. Argumentum.
3. Actus 1.
4. Personae.
5. Interlocutores.
6. Actus primi Scena prima.
7. Actus primi Scena secunda.
8. Actus primi Scena tertia.
9. Actus primi Scena quarta.
10. Actus primi Scena quinta.
11. Actus secundi Scena prima.
12. Actus secundi Scena secunda.
17. Actus secundi Scena tertia.
18. Actus secundi Scena quarta.
19. Actus tertii Scena prima.
20. Actus tertii Scena secunda.
21. Actus tertij Scena tertia.
24. Actus tertij Scena quarta.
25. Actus tertij Scena quinta.
26. Actus quarti Scena prima.
27. Actus quarti Scena secunda.
28. Actus quarti Scena tertia.
29. Actus quarti Scena quarta.
30. Actus quinti Scena prima.
31. Actus quinti Scena secunda.
32. Actus quinti Scena tertia.
33. Act. quinti Sce. quarta, & vltima.
38. Peroratio.
Back
TEI header
Front
Main
1. Prologus
2. Actus primi scena sexta.
3. Actus secundi, scena prima
Back
TEI header
Front
Main
1. Prologus
2. Actus primi scena secunda
Back
TEI header
Front
Main
1. PERSONAE
4. PROLOGVS.
5. ARGVMENTVM ACTVS I.
6. ACTVS I. SCENA I.
7. ACTVS I. SCENA II.
8. ARGVMENTVM ACTVS II.
9. ACTUS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS II. SCENA IIII.
13. ARGVMENTVM ACTVS III.
14. ACTVS III. SCENA I.
15. ACTVS III. SCENA II.
16. ACTVS III. SCENA III.
17. ACTVS III. SCENA iiii.
18. ACTVS III. SCENA V.
19. ACTUS III. SCENA VI.
20. ARGVMENTVM ACTVS IIII.
21. ACTVS IIII. SCENA I.
22. ACTVS IIII. SCENA II.
23. ACTVS IIII. SCENA III.
24. ACTVS IIII. SCENA IIII.
25. ACTVS IIII. SCENA V.
26. ACTVS IIII. SCENA VI.
27. ARGVMENTVM ACTVS V.
28. ACTVS V. SCENA I.
29. ACTVS V. SCENA II.
Back
32 div
TEI header
Front
Main
1. ACTUS PRIMUS.
3. ACTUS SECUNDUS.
5. ACTUS III.
7. ACTUS IIII.
9. ACTUS QUINTUS.
Back
TEI header
Front
Main
1. PERSONAE.
4. ACTUS PRIMUS.
6. ACTUS SECUNDUS.
8. ACTUS TERTIUS.
11. ACTUS QUARTUS.
16. ACTUS QUINTUS.
Back
TEI header
Front
Main
1. INTERLOCUTORES
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. Prologus
3. PERIOCHA
4. ACTUS I.
5. SCENA I.
6. ARGUMENTUM SCENAE.
7. ACTUS. I. SCENA II.
8. ARGUMENTUM.
9. ACTUS I. SCENA III.
10. ARGUMENTUM.
11. ACTUS I. SCENA IIII.
12. ARGUMENTUM.
13. ACTUS I. SCENA V.
14. ARGUMENTUM.
15. ACTUS II.
16. SCENA I.
17. ARGUMENTUM.
18. ACTUS II. SCENA II.
19. ARGUMENTUM.
20. ACTUS II. SCENA III.
21. ARGUMENTUM.
22. ACTUS II. SCENA IIII.
23. ARGUMENTUM.
24. ACTUS II. SCENA V.
25. ARGUMENTUM.
26. ACTUS III.
27. SCENA I.
28. ARGUMENTUM.
29. ACTUS III. SCENA II.
30. ARGUMENTUM.
31. ACTUS III. SCENA III.
32. ARGUMENTUM.
33. ACTUS III. SCENA IIII.
34. ARGUMENTUM.
35. ACTUS III. SCENA V.
36. ARGUMENTUM.
37. ACTUS IIII.
38. SCENA I.
39. ARGUMENTUM.
40. ACTUS IIII. SCENA II.
41. ARGUMENTUM.
42. ACTUS IIII. SCENA III.
43. ARGUMENTUM.
44. ACTUS IIII. SCENA IIII.
45. ARGUMENTUM.
46. ACTUS IIII. SCENA V.
47. ARGUMENTUM.
48. ACTUS V.
49. SCENA I.
50. ARGUMENTUM.
51. ACTUS V. SCENA II.
52. ARGUMENTUM.
53. ACTUS V. SCENA III.
54. ARGUMENTUM.
55. ACTUS V. SCENA IIII.
56. ARGUMENTUM.
57. ACTUS V. SCENA V.
58. ARGUMENTUM.
Back
TEI header
Front
Main
1. PERSONAE TRAGOEDIAE
3. ACTUS PRIMUS.
5. ACTUS II. SCENA I.
6. SCENA II.
8. ACTUS. III. SCENA. I.
9. SCENA. II.
11. ACTUS QUARTUS. SCENA I.
12. SCENA II.
13. SCENA. III.
16. ACTUS. V.
Back
15 div
TEI header
Front
Main
1.  PERSONAE. 
2.  ACTUS PRIMUS. 
4. ACTUS SECUNDUS.
6. ACTUS TERTIUS.
8. ACTUS QUARTUS. 
10. ACTUS QUINTUS.
Back
TEI header
Front
Main
1. PROLOGVS IN CATHARINAM.
2. ARGVMENTVM.
3. Personae Tragoediae.
5. ACTVS PRIMI
6. SCENA .I.
7. ACTVS PRIMI,
8. SCENA .II.
9. ACTVS. I. SCENA. III.
10. ACTVS. I. SCENA. IIII.
11. ACTVS. I. SCENA. V.
12. ACTVS PRIMI,
13. SCENA. VI.
15. ACTVS SECVNDI
16. SCENA PRIMA.
17. ACTVS. II. SCENA. II.
18. ACTVS. II. SCENA. III.
19. ACTVS. II. SCENA. IIII.
20. ACTVS II. SCENA.V.
22. ACTVS TERTII
23. SCENA PRIMA.
24. ACTVS. III. SCENA. II.
25. ACTVS. III. SCENA. III.
26. ACTVS. III. SCENA. IIII.
28. ACTVS QVARTI
29. SCENA PRIMA.
30. ACTVS QVARTI,
31. SCENA. II.
32. ACTVS. IIII. SCENA. III.
38. ACTVS. IIII. SCENA. IIII.
40. ACTVS. IIII. SCENA. V.
42. ACTVS QVINTI
43. SCENA PRIMA.
44. ACTVS. V. SCENA. II.
45. ACTVS. V. SCENA. III.
46. ACTVS. V. SCENA. IIII.
47. ACTVS. V. SCENA. V.
48. ACTVS. V. SCENA. VI.
49. ACTVS. V. SCENA. VII.
50. ACTVS QVINTI
51. SCENA. VIII.
Back
TEI header
Front
Main
1. PROLOGVS
2. ARGVMENTVM.
3. Personae actionis.
5. ACTVS. I. SCENA. II.
6. ACTVS. I. SCENA. III.
7. ACTVS. I. SCENA. IIII.
8. ACTVS. I. SCENA. V.
9. ACTVS.I. SCENA. VI.
11. ACTVS SECVNDI.
12. SCENA PRIMA.
13. ACTVS. II. SCENA. II.
14. ACTVS. II. SCENA. III.
15. ACTVS. II. SCENA. IIII.
16. ACTVS II. SCENA. V.
17. ACTVS. II. SCENA. VI.
18. ACTVS. II. SCENA. VII.
20. ACTVS TERTII, SCENA I.
21. ACTVS. III. SCENA. II.
22. ACTVS. III. SCENA. III.
23. ACTVS. III. SCENA. IIII.
24. ACTVS. III. SCENA. V.
25. ACTVS. III. SCENA. VI.
26. ACTVS. III. SCENA.VII.
27. ACTVS TERTII SCENA. VIII.
29. ACTVS QVARTI SCENA PRIMA.
30. ACTVS. IIII. SCENA. II.
31. ACTVS. IIII. SCENA. III.
32. ACTVS. IIII. SCENA. IIII.
33. ACTVS. IIII. SCENA. V.
34. ACTVS IIII. SCENA.VI.
36. ACTVS QVINTI SCENA PRIMA.
37. ACTVS QVINTI SCENA. II.
38. ACTVS QVINTI SCENA. III.
39. ACTVS. V. SCENA. IIII.
40. ACTVS. V. SCENA. V.
41. ACTVS. V. SCENA. VI.
42. ACTVS. V. SCENA. VII.
43. ACTVS QVINTI, SCENA. VIII.
44. ACTVS QVINTI, SCENA. IX.
45. ACTVS. V. SCENA VLTIMA.
Back
TEI header
Front
Main
1. PERSONAE.
3. SCENA PRIMA. ACTVS PRIMVS.
4. SCENA SECVNDA.
6. ACTVS SECVNDVS.
7. Errata sic condonat, & scelerum pius
9. ACT. TERT. SCENA. PRIMA.
12. SCENA SECVNDA.
13. SCENA TERTIA.
15. ACT. QVART. SCEN. PRIM.
17. ACT. V. SCEN. I.
Back
TEI header
Front
Main
2. PROLOGVS.
3. Argumentum.
4. Actus secundus.
5. Conclusio.
6. (2230) Errata siqua sint tolerate aut mungite.
Back
TEI header
Front
Main
3. PROLOGVS
4. ACTVS PRIMI.
5. SCENA PRIMA.
6. Actus primi. Scena secunda.
7. Actus primi. Scena tertia.
8. Actus primi. Scena quarta.
10. Actus secundus. Scena prima.
11. Actus secundi. Scena secunda.
12. Actus secundi. Scena tertia.
14. Actus tertij. Scena prima.
15. Actus tertij. Scena secunda.
16. Actus tertij. Scena tertia.
17. Actus tertij. Scena quarta.
19. Actus quarti. Scena prima.
20. Actus quarti. Scena secunda.
21. Actus quarti. Scena tertia
23. Actus quinti. Scena prima.
24. Actus quinti. Scena secunda.
25. Actus quinti: Scena tertia.
26. Actus quinti. Scena quarta.
27. Actus quinti: Scena quinta.
Back
26 div
TEI header
Front
Main
1. INTERLOQVVTORES
2. PROLOGVS
3. ACTVS I.
4. SCENA I.
5. SCENA II.
6. SCENA III.
7. SCENA IIII.
8. ACTVS II.
9. SCENA I.
10. SCENA II.
11. SCENA III.
12. SCENA IIII.
13.  SCENA V.
14. ACTVS III.
15. SCENA I.
16. SCENA II.
17. SCENA III.
18. SCENA IIII.
19. ACTVS IIII.
20. SCENA I.
21. SCENA II
22. ACTUS V
23. SCENA I.
24. SCENA II.
25. SCENA III.
26. SCENA IIII.
27. SCENA V.
28. SCENA VI.
29. SCENA VII.
Back
34 div
TEI header
Front
Main
1. Prologus in Codrum feliciter incipit.
2. Argumentum.
Back
TEI header
Front
Main
Back
TEI header
Front
Main
1. Actorum nomina.
3. Epilogus. Populus Aegyptius. Demus.
4. PROLOGVS.
8. Actus primi Scena prima.
14. Actus secundi Scena prima.
15. Scena 2. Septenarii & Octonarii.
16. Scena 4. Scazontes.
21. Actus 3. Scena 1a Senarii.
23. Scena tertia Senarii.
28. Scena 7. Scazontes.
29. Scena 8. Trochaici Trimetri.
31. Actus 4. Scena I. Senarii Iamb.
32. Scena 2. Trochaici Senarii.
34. Scena 3. Trimetri Iambici.
36. Scena 4. Septenarii.
38. Scena 5. Trimetri.
40. Scena 6. Eiusdem generis cum superioribus
41. Scena 7. Trimetri Iamb.
42. Scena 8. Similis farinae vsus.
43. Scena 9. Octonarii admistis Septe¬
45. Scena 10. Trimetri Iambici.
47. Scena II. Vt superiores.
49. Scena XII.
51. Scena XIII. Eiusdem generis vt sup.
53. Actus 5. Scena I.
54. Scena 2. Trimetri, vt superiores.
55. Scena 4. Trimetri.
57. Scena 5. Senarii Iamb.
59. Scena 6. Eiusdem generis.
61. Scena 7. Trimetri.
63. Scena 8. Similis farinae.
64. Scena 9.
65. Scena 10. Octonarii vt supra.
66. Epilogus, seu Peroratio.
Back
39 div
TEI header
Front
Main
1. Personae Dramatis.
3. ARGVMENTVM COMOEDIAE.
4. Prologus in Militem.
5. ACTVS PRIMI, SCENA PRIMA.
6. ARGVMENTVM.
7. ACTVS PRIMI, SCENA SECVNDA.
8. ARGVMENTVM.
9. ACTVS I. SCENA III.
10. ARGVMENTVM.
11. ACTVS PRIMI, SCENA QYARTA
12. ARGVMENTVM.
13. ACTVS PRIMI, SCENA QVINTA,
14. ARGVMENTVM.
16. ACTVS SECVNDI, SCENA PRIMA.
17. ARGVMENTVM.
18. ACTVS SECVNDI, SCENA SECVNDA.
19. ARGVMENTVM.
20. ACTVS SECVNDI, SCENA TERTIA.
21. ARGVMENTVM.
22. ACTVS SECVNDI, SCENA QVARTA.
23. ARGVMENTVM.
24. ACTVS SECVNDI, SCENA QVINTA
25. ARGVMENTVM.
26. ACTVS SECVNDI, SCENA SEXTA.
27. ARGVMENTVM.
29. ACTVS TERTII, SCENA PRIMA.
30. ARGVMENTVM.
31. ACTVS TERTII, SCENA SECVNDA.
32. ARGVMENTVM.
33. ACTVS TERTII, SCENA TERTIA.
34. ARGVMENTVM.
35. ACTVS TERTII, SCENA QVARTA.
36. ARGVMENTVM.
37. ACTVS TERTII, SCENA QVINTA.
38. ACTVS TERTII, SCENA SEXTA,
39. ARGVMENTVM.
41. ACTVS QVARTI, SCENA PRIMA.
42. ACTVS IIII, SCENA SECVNDA.
43. ACTVS QVARTI, SCENA TERTIA.
44. ACTVS IIII, SCENA QVARTA
46. ACTVS QVINTI, SCENA PRIMA.
47. ACTVS V SCENA SECVNDA
48. ACTVS V. SCENA III. ET VLTIMA.
49. Epilogus.
Back
49 div
TEI header
Front
Main
2. Prologus silentium a spectatoribus precatur.
3. ACTVS SECVNDVS.
4. ACTVS QVARTVS.
Back
8 div
TEI header
Front
Main
2. ACTVS PRIMVS.
4. ACTVS SECVNDVS
6. ACTVS TERTIVS.
8. ACTVS QVARTVS.
10. ACTVS QVINTVS
Back
TEI header
Front
Main
1. ACTVS PRIMI
2. Scena Prima.
4. ACTVS II.
6. ACTVS III.
8. ACTVS IIII.
10. ACTVS V.
Back
TEI header
Front
Main
2. ACTVS PRIMVS
4. ACTVS SECVNDVS
6. ACTVS TERTIVS.
8. ACTVS QVARTVS.
10. ACTVS QVINTVS.
Back
TEI header
Front
Main
3. Actus primi. Scena Ia.
5. ACTVS 2. 
7. ACTVS 3.
9. ACTVS 4.
12. ACTVS 5.
Back
TEI header
Front
Main
1. ACTVS PRIMVS
3. ACTVS SECVNDVS
4. ACTVS TERTIVS.
6. ACTVS QVARTVS.
8. ACTVS QVINTVS
Back
TEI header
Front
Main
1. ACTVS PRIMVS
3. ACTVS SECVNDVS.
5. ACTVS TERTIVS
7. ACTVS QVARTVS.
9. ACTVS QVINTVS.
Back
TEI header
Front
Main
2. ACTVS PRIMVS.
4. ACTVS SECVNDVS.
6. ACTVS TERTIVS.
8. ACTVS QVARTVS.
10. ACTVS QVINTVS
Back
TEI header
Front
Main
1. PROLOGUS.
2. PERSONAE dramatis seu diverbii Actus primi
3. ACTUS I. SCAENA I.
4. ACTUS I. SCAENA II.
5. ACTUS I. SCAENA III.
6. ACTUS I. SCAENA IV.
7. ACTUS I. SCAENA V.
8. ACTUS I. SCAENA VI.
9. ACTUS I. SCAENA VII.
11. PERSONAE dramatis in secundo Actu.
12. ACTUS II. SCAENA I.
13. ACTUS II. SCAENA II.
14. ACTUS II. SCAENA III.
15. ACTUS II. SCAENA interiectitia.
16. ACTUS II. Residuum SCAENAE III.
17. ACTUS II. SCAENA IV.
18. ACTUS II. SCAENA V.
20. PERSONAE dramatis Actus tertii.
21. ACTUS III. SCAENA I.
22. ACTUS III. SCAENA interiectitia.
23. ACTUS III. Residuum SCAENAE I.
24. ACTUS III. SCAENA II.
25. ACTUS III. SCAENA III.
26. ACTUS III. SCAENA IV.
27. ACTUS III. SCAENA V.
28. ACTUS III. SCAENA VI.
29. ACTUS III. SCAENA VII.
30. ACTUS III. SCAENA VIII.
31. ACTUS III. SCAENA Interiectitia
32. ACTUS III. SCAENA altera Interiectitia.
33. ACTUS III. Residuum SCAENAE VIII.
34. ACTUS III. SCAENA IX.
35. ACTUS III. SCAENA X.
36. ACTUS III. SCAENA XI.
38. PERSONAE dramatis Actus quarti.
39. ACTUS IV. SCAENA I.
40. ACTUS IV. SCAENA II.
41. ACTUS IV. SCAENA III.
42. ACTUS IV. SCAENA IV.
43. ACTUS IV. SCAENA V.
45. ACTUS IV. SCAENA VI.
47. Dramatis PERSONAE in quinto Actu.
48. ACTUS V. SCAENA I.
49. ACTUS V. SCAENA II.
50. ACTUS V. SCAENA III.
51. ACTUS V. SCAENA IV.
52. ACTUS V. SCAENA V.
53. ACTUS V. SCANEA VI.
54. ACTUS V. SCAENA VII.
55. ACTUS V. SCAENA VIII.
56. ACTUS V. SCAENA IX.
57. ACTUS V. SCAENA X.
58. ACTUS V. SCAENA XI.
59. ACTUS V. SCAENA XII.
60. ACTUS V. SCAENA XIII.
61. ACTUS V. SCAENA XIV.
62. ACTUS V. SCAENA XV.
63. ACTUS V. SCAENA XVI.
64. ACTUS V. SCAENA XVII.
65. EPILOGUS, per quemlibet dicendus aut canendus.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGUS IN ALUTAM cum MORO.
3. ACTUS I. SCAENA I.
4. ACTUS I. SCAENA II.
5. ACTUS I. SCAENA III.
6. ACTUS I. SCAENA IV.
7. ACTUS I. SCAENA V.
8. ACTUS I. SCAENA VI.
10. ACTUS II. SCAENA I.
11. ACTUS II. SCAENA II.
12. ACTUS II. SCAENA III.
14. ACTUS III. SCAENA I.
15. ACTUS III. SCAENA II.
17. ACTUS IV. SCAENA I.
18. ACTUS IV. SCAENA II.
19. ACTUS IV. SCAENA III.
20. ACTUS IV. SCAENA IV.
22. ACTUS V. SCAENA I.
23. ACTUS V. SCAENA II.
24. ACTUS V. SCAENA III.
25. ACTUS V. SCAENA IV.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. Prologus.
5. Actus primi. Scena prima.
6. ACTUS I. SCENA II.
7. Actus primi Scena tertia.
8. Actus primi. Scena quarta.
10. Actus II. Scena I.
11. Actus secundi. Scena secunda.
12. Actus secundi. Scena tertia.
13. Actus secundi. Scena quarta.
15. Actus III Scena I.
16. Actus tertij scena secunda.
17. Actus tertij Scena tertia.
18. Actus tertij Scena quarta.
20. ACTUS IIII. SCENA I.
21. Actus quarti. Scena secunda.
22. ACTUS IIII. SCENA III.
23. Scena quarta. Actus quarti.
24. Actus quarti Scena quinta.
26. Actus quinti. Scena prima.
27. Actus quinti Scena secunda.
28. Actus V. Scena tertia.
29. Actus quinti Scena quarta.
30. Actus quinti Scena quinta.
31. Actus quinti Scena sexta.
32. Actus quinti Scena septima.
33. Actus quinti Scena octava.
34. Actus quinti Scena nona.
35. ACTUS quinti. SCAENA decima.
36. ACTUS quinti. SCAENA undecima.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGUS.
3. ACTUS I. SCAENA I.
4. ACTUS I. SCAENA II.
5. ACTUS I. SCAENA III.
6. ACTUS I. SCAENA IV.
8. ACTUS II. SCAENA I.
9. ACTUS II. SCAENA II.
10. ACTUS II. SCAENA III.
11. ACTUS II. SCAENA IV.
12. ACTUS II. SCAENA V.
14. ACTUS III. SCAENA I.
15. ACTUS III. SCAENA II.
16. ACTUS III. SCAENA III.
17. ACTUS III. SCAENA IV.
18. ACTUS III. SCAENA V.
19. ACTUS III. SCAENA VI.
20. ACTUS III. SCAENA VII.
21. ACTUS III. SCAENA VIII.
22. ACTUS III. SCAENA IX.
23. ACTUS III. SCAENA X.
24. ACTUS III. SCAENA XI.
26. ACTUS IV. SCAENA I.
27. ACTUS IV. SCAENA II.
28. ACTUS IV. SCAENA III.
29. ACTUS IV. SCAENA IV.
30. ACTUS IV. SCAENA V.
31. ACTUS IV. SCAENA VI.
32. ACTUS IV. SCAENA VII.
33. ACTUS IV. SCAENA VIII.
35. ACTUS V. SCAENA I.
36. ACTUS V. SCAENA II.
37. ACTUS V. SCAENA III.
38. ACTUS V. SCAENA IV.
39. ACTUS V. SCAENA V.
40. ACTUS V. SCAENA VI.
41. ACTUS V. SCAENA VII.
42. ACTUS V. SCAENA VIII.
43. ACTUS V. SCAENA ULTIMA.
Back
TEI header
Front
Main
1. ACTORES FABULAE.
2. PROLOGUS.
3. ACTUS I. SCAENA I.
4. ACTUS I. SCAENA II.
5. ACTUS I. SCAENA III.
6. ACTUS I. SCAENA IV.
8. ACTUS II. SCAENA I.
9. ACTUS II. SCAENA II.
10. ACTUS II. SCAENA III.
11. ACTUS II. SCAENA IV.
13. ACTUS III. SCAENA I.
14. ACTUS III. SCAENA II.
15. ACTUS III. SCAENA III.
16. ACTUS III. SCAENA IV.
17. ACTUS III. SCAENA V.
18. ACTUS III. SCAENA VI.
19. ACTUS III. SCAENA VII.
21. ACTUS IV. SCAENA I.
22. ACTUS IV. SCAENA II.
23. ACTUS IV. SCAENA III.
24. ACTUS IV. SCAENA IV.
25. ACTUS IV. SCAENA V.
26. ACTUS IV. SCAENA VI.
27. ACTUS IV. SCAENA VII.
28. ACTUS IV. SCAENA VIII.
30. ACTUS V. SCAENA I.
31. ACTUS V. SCAENA II.
32. ACTUS V. SCAENA III.
33. ACTUS V. SCAENA IV.
Back
TEI header
Front
Main
1. PERSONAE DRAMATIS,
2. PROLOGUS in Hecastum.
4. ACTUS I. SCAENA I.
5. ACTUS I. SCAENA II.
6. ACTUS I. SCAENA III.
7. ACTUS I. SCAENA IV.
9. ACTUS II. SCAENA I.
10. ACTUS II. SCAENA II.
11. ACTUS II. SCAENA III.
12. ACTUS II. SCAENA IV.
13. ACTUS II. SCAENA V.
14. ACTUS II. SCAENA VI.
15. ACTUS II. SCAENA VII.
16. ACTUS II. SCAENA VIII.
17. ACTUS II. SCAENA IX.
18. ACTUS II. SCAENA X.
20. ACTUS III. SCAENA I.
21. ACTUS III. SCAENA II.
22. ACTUS III. SCAENA III.
23. ACTUS III. SCAENA IV.
24. ACTUS III. SCAENA V.
25. ACTUS III. SCAENA VI.
26. ACTUS III. SCAENA VII.
28. ACTUS IV. SCAENA I.
29. ACTUS IV. SCAENA II.
30. ACTUS IV. SCAENA III.
31. ACTUS IV. SCAENA IV.
33. ACTUS V. SCAENA I.
34. ACTUS V. SCAENA II.
35. ACTUS V. SCAENA IV.
36. ACTUS V. SCAENA V.
37. ACTUS V. SCAENA VI.
38. ACTUS V. SCAENA VII.
39. ACTUS V. SCAENA VIII.
40. ACTUS V. SCAENA IX.
41. ACTUS V. SCAENA X.
42. ACTUS V. SCAENA XI.
43. ACTUS V. SCAENA XII, INTERIECTITIA.
44. ACTUS V. SCAENA XIII.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. ACTUS I. SCAENA I.
3. ACTUS I. SCAENA II.
4. ACTUS I. SCAENA III.
5. ACTUS I. SCAENA IV.
7. ACTUS II. SCAENA I.
8. ACTUS II. SCAENA II.
9. ACTUS II. SCAENA III.
10. ACTUS II. SCAENA IV.
11. ACTUS II. SCAENA V.
12. ACTUS II. SCAENA VI.
14. ACTUS III. SCAENA I.
15. ACTUS III. SCAENA II.
17. ACTUS IV. SCAENA I.
18. ACTUS IV. SCAENA II.
19. ACTUS IV. SCAENA III.
20. ACTUS IV. SCAENA IV.
22. ACTUS V. SCAENA I.
23. ACTUS V. SCAENA II.
24. ACTUS V. SCAENA III.
25. ACTUS V. SCAENA IV.
26. ACTUS V. SCAENA V.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGUS.
3. Personae erunt tristemque habebunt exitum.
4. ACTUS I. SCAENA I.
5. ACTUS I. SCAENA II.
6. ACTUS I. SCAENA III.
7. ACTUS I. SCAENA IV.
9. ACTUS II. SCAENA I.
10. ACTUS II. SCAENA II.
11. ACTUS II. SCAENA III.
12. ACTUS II. SCAENA IV.
13. ACTUS II. SCAENA V.
14. ACTUS II. SCAENA VI.
15. ACTUS II. SCAENA VII.
16. ACTUS II. SCAENA VIII.
17. ACTUS II. SCAENA IX.
18. ACTUS II. SCAENA X.
20. ACTUS III. SCAENA I.
21. ACTUS III. SCAENA II.
22. ACTUS III. SCAENA III.
23. ACTUS III. SCAENA IV.
24. ACTUS III. SCAENA V.
25. ACTUS III. SCAENA VI.
26. ACTUS III. SCAENA VII.
28. ACTUS IV. SCAENA I.
29. ACTUS IV. SCAENA II.
30. ACTUS IV. SCAENA III.
31. ACTUS IV. SCAENA IV.
32. ACTUS IV. SCAENA V.
33. ACTUS IV. SCAENA VI.
34. ACTUS IV. SCAENA VII.
35. ACTUS IV. SCAENA VIII
36. ACTUS IV. SCAENA IX.
38. ACTUS V. SCAENA I.
39. ACTUS V. SCAENA II.
40. ACTUS V. SCAENA III.
41. ACTUS V. SCAENA IV.
42. ACTUS V. SCAENA V.
43. ACTUS V. SCAENA VI.
44. ACTUS V. SCAENA VII.
45. ACTUS V. SCAENA VIII.
46. ACTUS V. SCAENA IX.
47. EPILOGUS.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGUS.
4. ACTUS I. SCAENA I.
5. ACTUS I. SCAENA II.
6. ACTUS I. SCAENA III.
7. ACTUS I. SCAENA IV.
9. ACTUS II. SCAENA I.
10. ACTUS II. SCAENA II.
11. ACTUS II. SCAENA III.
12. ACTUS II. SCAENA IV.
13. ACTUS II. SCAENA V.
14. ACTUS II. SCAENA VI.
15. ACTUS II. SCAENA VII.
16. ACTUS II. SCAENA VIII.
17. ACTUS II. SCAENA IX.
19. ACTUS III. SCAENA I.
20. ACTUS III. SCAENA II.
21. ACTUS III. SCAENA III.
22. ACTUS III. SCAENA IV.
23. ACTUS III. SCAENA V.
24. ACTUS III. SCAENA VI.
26. ACTUS IV. SCAENA I.
27. ACTUS IV. SCAENA II.
28. ACTUS IV. SCAENA III.
29. ACTUS IV. SCAENA IV.
30. ACTUS IV. SCAENA V.
31. ACTUS IV. SCAENA VI.
32. ACTUS IV. SCAENA VII.
34. ACTUS V. SCAENA I.
35. ACTUS V. SCAENA II.
36. ACTUS V. SCAENA III.
37. ACTUS V. SCAENA IV.
38. ACTUS V. SCAENA V.
39. ACTUS V. SCAENA VI.
40. ACTUS V. SCAENA VII.
41. ACTUS V. SCAENA VIII.
42. ACTUS V. SCAENA IX.
43. ACTUS V. SCAENA X.
44. ACTUS V. SCAENA XI.
45. ACTUS V. SCAENA XII.
46. ACTUS V. SCAENA XIII.
47. ACTUS V. SCAENA XIIII.
48. ACTUS V. SCAENA XV.
Back
TEI header
Front
Main
1. PERSONAE DRAMATIS.
2. PROLOGUS
3. (60) Errata quamvis minima, non defenderit.
5. ACTUS I. SCAENA I.
6. ACTUS I. SCAENA II.
7. ACTUS I. SCAENA III.
8. ACTUS I. SCAENA IV.
9. ACTUS I. SCAENA V
10. ACTUS I. SCAENA VI.
11. ACTUS I. SCAENA VII.
12. ACTUS I. SCAENA VIII.
14. ACTUS II. SCAENA I.
15. ACTUS II. SCAENA II.
16. ACTUS II. SCAENA III.
17. ACTUS II. SCAENA IV.
19. ACTUS III. SCAENA I.
20. ACTUS III. SCAENA II.
21. ACTUS III. SCAENA III.
22. ACTUS III. SCAENA IV.
23. ACTUS III. SCAENA V.
25. ACTUS IV. SCAENA I.
26. ACTUS IV. SCAENA II.
27. ACTUS IV. SCAENA III.
28. ACTUS IV. SCAENA IV.
29. ACTUS IV. SCAENA V.
30. ACTUS IV. SCAENA VI.
31. ACTUS IV. SCAENA VII.
32. ACTUS IV. SCAENA VIII.
34. ACTUS V. SCAENA I.
35. ACTUS V. SCAENA II.
36. ACTUS V. SCAENA III.
37. ACTUS V. SCAENA IV.
38. ACTUS V. SCAENA V.
39. ACTUS V. SCAENA VI.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
2. PROLOGUS.
3. ACTUS I. SCAENA I.
4. ACTUS I. SCAENA II.
5. ACTUS I. SCAENA III.
6. ACTUS I. SCAENA IV.
8. ACTUS II. SCAENA I.
9. ACTUS II. SCAENA II.
10. ACTUS II. SCAENA III.
11. ACTUS II. SCAENA IV.
12. ACTUS II. SCAENA V.
13. ACTUS II. SCAENA VI.
15. ACTUS III. SCAENA I.
16. ACTUS III. SCAENA II.
17. ACTUS III. SCAENA III.
18. ACTUS III. SCAENA IV.
20. ACTUS IV. SCAENA I.
21. ACTUS IV. SCAENA II.
22. ACTUS IV. SCAENA III.
23. ACTUS IV. SCAENA IV.
24. ACTUS IV. SCAENA V.
25. ACTUS IV. SCAENA VI.
26. ACTUS IV. SCAENA VII.
27. ACTUS IV. SCAENA VIII.
28. ACTUS IV. SCAENA IX.
29. ACTUS IV. SCAENA X.
30. ACTUS IV. SCAENA XI.
31. ACTUS IV. SCAENA XII.
33. ACTUS V. SCAENA I.
34. ACTUS V. SCAENA II.
35. ACTUS V. SCAENA III.
36. ACTUS V. SCAENA IV.
37. ACTUS V. SCAENA V.
38. ACTUS V. SCAENA VI.
39. ACTUS V. SCAENA VII.
40. ACTUS V. SCAENA VIII.
41. ACTUS V. SCAENA IX.
42. ACTUS V. SCAENA ULTIMA.
43. EPILOGUS per GREGEM.
Back
TEI header
Front
Main
1. DRAMATIS PERSONAE.
3. PROLOGUS cum MORIONE.
4. ACTUS I. SCAENA I.
5. ACTUS I. SCAENA II.
6. ACTUS I. SCAENA III.
7. ACTUS I. SCAENA IV.
8. ACTUS I. SCAENA V.
10. ACTUS II. SCAENA I.
11. ACTUS II. SCAENA II.
12. ACTUS II. SCAENA III.
14. ACTUS III. SCAENA I.
15. ACTUS III. SCAENA II.
16. ACTUS III. SCAENA III.
17. ACTUS III. SCAENA IV.
18. ACTUS III. SCAENA V.
20. ACTUS IV. SCAENA I.
21. ACTUS IV. SCAENA II.
22. ACTUS IV. SCAENA III.
23. ACTUS IV. SCAENA IV.
24. ACTUS IV. SCAENA V.
25. ACTUS IV. SCAENA VI.
26. ACTUS IV. SCAENA VII.
27. ACTUS IV. SCAENA VIII.
28. ACTUS IV. SCAENA IX.
29. ACTUS IV. SCAENA X.
31. ACTUS V. SCAENA I.
32. ACTUS V. SCAENA II.
33. ACTUS V. SCAENA III.
34. ACTUS V. SCAENA IV.
35. ACTUS V. SCAENA V.
36. ACTUS V. SCAENA VI.
37. ACTUS V. SCAENA VII.
38. ACTUS V. SCAENA VIII.
39. ACTUS V. SCAENA IX.
40. ACTUS V. SCAENA X.
41. ACTUS V. SCAENA XI.
42. ACTUS V. SCAENA XII.
43. ACTUS V. SCAENA XIII.
44. ACTUS V. SCAENA XIV.
Back
TEI header
Front
Main
1. PERSONAE.
3. ACTVS PRIMVS.
5. ACTVS SECVNDVS.
7. ACTVS TERTIVS.
9. ACTVS QVARTVS.
12. ACTVS QVINTVS.
Back
TEI header
Front
Main
1. Personae dramatis.
3. Actus Primus
5. Actus secundus.
7. Actus tertius.
9. Actus quartus.
11. Actus quintus.
Back
TEI header
Front
Main
2. ACTUS I
3. Scena I
4. Scena II
6. ACTVS II
7. SCENA I
11. ACTVS III
12. SCENA I
13. Scena II
14. Scena III
15. Scena IV
17. ACTVS IV
18. Scena I
19. Scena II
21. ACTVS V
Back
TEI header
Front
Main
1.  Personae tragoediae.
3. Actus primus.
5.  Actus secundus.
7. Actus tertius.
9.  Actus quartus.
12. Actus quintus.
Back
TEI header
Front
Main
1. Prologus
2. Actus primi scaena prima
3. Actus primi scaena secunda
4. Actus primi scaena tertia
5. Actus primi scaena quarta
6. Actus secundi scaena prima
7. Actus secundi scaena secunda
8. Actus secundi scaena tertia
9. Actus secundi scaena quarta
10. Actus tertii scaena prima
11. Actus tertii scaena secunda
12. Actus tertii scaena tertia
13. Argumentum est mali importuna celeritas.
14. Actus tertii scaena quarta
15. Actus tertii scaena quinta
16. Actus quarti scaena prima
17. Actus quarti scaena secunda
18. Actus quarti scaena tertia
19. Actus quarti scaena quarta
20. Actus quinti scaena prima
21. Actus quinti scaena secunda
22. Actus quinti scaena tertia
23. Actus quinti scaena quarta
24. Actus quinti scaena quinta
25. Actus quinti scaena sexta
26. Actus quinti scaena septima
27. Peroratio
Back
TEI header
Front
Main
1. Personae sive interloquutores huius dramatis.
4. Actus primus
7. Actus secundus
12. Actus tertius
17. Actus quartus
22. Actus quintus*
27. Peroratio
Back
12 div
TEI header
Front
Main
1. INTERLOQVVTORES.
2. ACTVS PRIMI
3. SCENA PRIMA.
4. SCENA SECVNDA.
5. SCENA TERTIA.
6. SCENA QVARTA.
7. ACTVS SECVNDVS.
8. SCENA PRIMA.
9. SCENA SECVNDA.
10. SCENA TERTIA.
11. SCENA QVARTA.
12. ACTVS TERTII
13. SCENA PRIMA.
14. SCENA SECVNDA.
15. SCENA TERTIA.
16. SCENA QVARTA.
17. Errata dones plurima?
18. ACTVS QVARTI
19. SCENA PRIMA.
20. SCENA SECVNDA.
21. SCENA TERTIA.
22. SCENA QVARTA.
23. ACTVS QVINTVS.
24. SCENA PRIMA.
25. SCENA SECVNDA.
26. SCENA TERTIA.
27. SCENA QVARTA.
28. SCENA QVINTA.
29. PERORATIO.
Back
TEI header
Front
Main
Back
5 div
TEI header
Front
Main
1. PERORATIO
Back
TEI header
Front
Main
1. Interlocutores
2. Argumentum sub iambis   hyponactiis
3. ACTUS PRIMUS
4. ACTUS SECUNDUS
Back
TEI header
Front
Main
1. PERSONAE
3. PROLOGUS
4. ACTVS SECVNDVS
5. ACTVS TERTIVS
6. ACTVS QVARTVS
7. ACTVS QVINTVS
Back
11 div
TEI header
Front
Main
1. PERSONAE.
2. PROLOGVS.
3. ACTVS PRIMVS.
4. ACTVS SECVNDVS.
5. ACTVS TERTIVS.
6. EPILOGVS.
Back
TEI header
Front
Main
1. Dramatis personae.
2. PROLOGVS.
3. Actus I. Scaena I.
4. Actus I. Scena II.
5. Actus I. Scena III.
6. Actus I. Scena IV.
7. Actus I. Scena V.
8. Actus II. Scena I.
9. Actus II. Scena II.
10. Actus II. Scena III.
11. Actus II. Scena IV.
12. Actus II. Scena V.
13. Actus II. Scena VI.
14. Actus II. Scena VII.
15. Actus II. Scena VIII.
16. Actus III. Scena I.
17. Actus III. Scena II.
18. Actus III. Scena III.
19. Actus III. Scena IV.
20. Actus III. Scena V.
21. Actus III. Scena VI.
22. Actus III. Scena VII.
23. Actus IV. Scena I.
24. Actus IV. Scena II.
25. Actus IV. Scena III.
26. Actus IV. Scena IIII.
27. Actus IV. Scena V.
28. Actus V. Scena I.
29. Actus V. Scena II.
30. Actus V. Scena Ill
31. Errata quaedam sic corrigantur.
Back
TEI header
Front
Main
1. TRAGOEDIAE INTERLOCVTORES.
3. ACTVS PRIMVS.
5. ACTVS SECVNDVS.
7. ACTVS TERTIVS.
9. ACTVS QVARTVS.
15. ACTVS QVINTVS.
Back
TEI header
Front
Main
1. PROLOGUS PRIOR |
3. argumentum.
4. PROLOGUS POSTERIOR
5. DRAMATIS PERSONAE
6. personae mutae
7. ACTUS I, SCAENA i
8. ACTUS I, SCAENA ii
9. ACTUS I, SCAENA iii
10. ACTUS I, SCAENA iv
11. ACTUS I, SCAENA v
12. ACTUS I, SCAENA vi
13. ACT I, SCAENA vii
14. ACTUS I, SCAENA viii
15. ACTUS II, SCAENA i
16. ACTUS II, SCAENA ii
17. ACTUS II, SCAENA iii
18. ACT II, SCAENA iv
19. ACTUS II, SCAENA v
20. ACTUS II, SCAENA vi
21. ACTUS II, SCAENA vii
22. ACTUS II, SCAENA viii
23. ACTUS III, SCAENA i
24. ACTUS III, SCAENA ii
25. ACTUS III, SCAENA iii
26. ACT III, SCAENA iv
27. ACTUS III, SCAENA v
28. ACTUS III, SCAENA vi
29. ACTUS III, SCAENA vii
30. ACTUS III, SCAENA viii
31. ACTUS III, SCAENA ix
32. ACTUS III, SCAENA x
33. ACT III, SCAENA xi
34. ACTUS III, SCAENA xii
35. ACTUS III, SCAENA xiii
36. ACTUS IV, SCAENA i
37. ACTUS IV, SCAENA ii
38. ACTUS IV, SCAENA iii
39. ACTUS IV, SCAENA iv
40. ACTUS IV, SCAENA v
41. ACTUS IV, SCAENA vi
42. ACTUS IV, SCAENA vii
43. ACTUS IV, SCAENA viii
44. ACTUS IV, SCAENA ix
45. ACTUS IV, SCAENA x
46. ACTUS IV, SCAENA xi
47. ACTUS IV, SCAENA xii
48. ACTUS V, SCAENA i
49. ACTUS V, SCAENA ii
50. ACTUS V, SCAENA iii
51. ACTUS V, SCENA iv
52. ACTUS V, SCAENA v
53. ACTUS V, SCAENA vi
54. ACTUS V, SCAENA vii
55. ACTUS V, SCAENA viii
56. ACTUS V, SCAENA ix |
57. ACTUS V, SCAENA x
58. ACTUS V, SCAENA xi
59. ACTUS V, SCAENA xii
60. EPILOGUS
Back
TEI header
Front
Main
1. Dramatis Personae
3. ACTUS PRIMUS.
5. ACTUS SECUNDUS.
7. ACTUS TERTIUS.
9. ACTUS QUARTUS.
11. ACTUS QUINTUS.
Back
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS II. SCENA IV.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS IV SCENA I
18. ACTVS IV. SCENA II.
19. ACTVS IV. SCENA III.
20. ACTVS IV. SCENA IV.
21. ACTVS IV. SCENA V.
22. ACTVS V. SCENA I.
23. ACTVS V. SCENA II.
24. ACTVS V. SCENA III.
25. ACTVS V. SCENA IV.
Back
30 div
TEI header
Front
Main
1. Dramatis personae.
2. ARGVMENTVM IN BAPTIsten, Carmine heroico redditum.
3. PROLOGVS.
4. PERIOCHA.
5. ACTVS I. SCENA I.
6. ACTVS I. SCENA II.
7. ACTVS I. SCENA III.
8. ACTVS I. SCENA IV.
9. ACTVS I. SCENA V.
10. ACTVS II. SCENA I.
11. ACTVS II. SCENA II.
12. ACTVS II. SCENA III.
13. ACTVS II. SCENA IV.
14. ACTVS II. SCENA V.
15. ACTVS III. SCENA I.
16. ACTVS III. SCENA II.
17. ACTVS III. SCENA III.
18. ACTVS III. SCENA IV.
19. ACTVS IV. SCENA I.
20. ACTVS IV SCENA II.
21. ACTVS IV. SCENA III.
22. ACTVS IV SCENA IV. [< II]
23. ACTVS V SCENA I.
24. ACTVS V. SCENA II.
25. ACTVS V. SCENA III.
26. ACTVS V. SCENA IV.
27. ACTVS V. SCENA V.
28. ACTVS V. SCENA VI.
29. ACTVS V. SCENA VII.
Back
34 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS. [= PERIOCHA]
3. ACTVS I. SCENA I.
4. ACTVS I. SCENA II.
5. ACTVS I. SCENA III. [< II]
6. ACTVS I. SCENA V.
7. ACTVS II. SCENA I.
8. ACTVS II. SCENA II.
9. ACTVS II. SCENA III.
10. ACTVS II. SCENA V. [<III]
11. ACTVS III. SCENA I.
12. ACTVS III. SCENA II.
13. ACTVS III. SCENA III.
14. ACTVS IV. SCENA I.
15. ACTVS IV. SCENA II.
16. ACTVS IV. SCENA III.
17. ACTVS V SCENA I.
18. ACTVS V. SCENA II.
19. ACTVS V. SCENA III.
Back
24 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. COMOEDIAE PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENA I.
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS II. SCENA IV.
12. ACTVS III. SCENA I.
13. ACTVS III. SCENA II.
14. ACTVS III. SCENA III.
15. ACTVS III. SCENA IV.
16. ACTVS IV. SCENA I.
17. ACTVS IV SCENA II.
18. ACTVS IV. SCENA III.
19. ACTVS IV SCENA IV.
20. ACTVS V. SCENA I.
21. ACTVS V. SCENA II.
22. ACTVS V. SCENA III.
23. ACTVS V. SCENA IIII.
24. ACTVS V. SCENA V.
25. PERORATIO.
Back
30 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS III. SCENA I.
13. ACTVS III. SCENA II.
14. ACTVS III. SCENA III.
15. ACTVS III. SCENA IV.
16. ACTVS IV SCENA I.
17. ACTVS IV. SCENA II.
18. ACTVS IV. SCENA III.
19. ACTVS IV. SCENA IV.
20. ACTVS V. SCENA I.
21. ACTVS V SCENA II.
22. ACTVS V. SCENA III.
23. ACTVS V. [< IV] SCENA IV.
Back
28 div
TEI header
Front
Main
1.  Actorum Nomina.
2. Actus 1. Scena 1.
3. Actus 1. Scena 2.
4. Actus 1. Scena 3.
5. Actus 1. Scena 4.
6. Actus 2. Scena 1.
7. Actus 2. Scena 2.
8. Actus 2. Scena 3.
9. Actus 3. Scena 1.
10.  Actus 3. Scena 2.
11. Actus 3. Scena 3.
12. Actus 4. Scena 1.
13.  Actus 4. Scena 2.
14. Actus 4. Scena 3.
15. Actus 5. Scena 1.
16. Actus 5. Scena 2.
17. Actus 5. Scena 3.
18. Actus 5. Scena 4.
20. Actus 1.
21. Actus 2.
22. Actus 3.
23. Actus 4.
Back
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS II. SCENA IV.
13. ACTVS II. SCENA V. POTIPHAR.
14. ACTVS II. SCENA VI.
15. ACTVS II. SCENA VII.
16. ACTVS III. SCENA I.
17. ACTVS III. SCENA II.
18. ACTVS III. SCENA III.
19. ACTVS III. SCENA. IV.
20. ACTVS IV. SCENA I.
21. ACTVS IV. SCENA II.
22. ACTVS IV. SCENA III.
23. ACTVS IV. SCENA IV.
24. ACTVS IV. SCENA V.
25. ACTVS IV. SCENA VI.
26. ACTVS V. SCENA I.
27. ACTVS V. SCENA II.
28. ACTVS V. SCENA III.
29. ACTVS V. SCENA IV.
30. ACTVS V. SCENA V.
31. ACTVS V. SCENA VI.
32. ACTVS V. SCENA VII.
33. ACTVS V. SCENA VIII.
34. PERORATIO.
Back
39 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. Comoediae Periocha.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENA I.
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS II. SCENA IV.
12. ACTVS III. SCENA I.
13. ACTVS III. SCENA II.
14. ACTVS III. SCENA III.
15. ACTVS III. SCENA IV.
16. ACTVS IV. SCENA I.
17. ACTVS IV. SCENA II.
18. ACTVS IV SCENA III.
19. ACTVS IV. SCENA IV.
20. ACTVS IV. SCENA V.
21. ACTVS V SCENA I.
22. ACTVS V SCENA II.
23. ACTVS V. SCENA III.
24. ACTVS V. SCENA IV.
25. ACTVS V. SCENA V.
26. ACTVS V SCENA VI.
27. ACTVS V. SCENA VII.
28. ACTVS V. SCENA VIII.
29. PERORATIO.
30. PERORATIO. 64
Back
35 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. COMOEDIAE ARGVMENTVM.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IIII.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS III. SCENA I.
13. ACTVS III. SCENA II.
14. ACTVS III. SCENA III.
15. ACTVS III. SCENA IV.
16. ACTVS III. SCENA V.
17. ACTVS III. SCENA VI.
18. ACTVS IV. SCENA I.
19. ACTVS IV. SCENA II.
20. ACTVS IV. SCENA III.
21. ACTVS IV SCENA IV.
22. ACTVS IV. SCENA V.
23. ACTVS V. SCENA I.
24. ACTVS V. SCENA II.
25. ACTVS V. SCENA III.
26. ACTVS V. SCENA IV.
27. ACTVS V. SCENA V.
28. ACTVS V. SCENA VI.
29. ACTVS V. SCENA VII.
30. PERORATIO.
Back
35 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. Comoediae argumentum.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS II. SCENA IV.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS III. SCENA. V.
18. ACTVS IV. SCENA I.
19. ACTVS IV. SCENA II.
20. ACTVS IV. SCENA III.
21. ACTVS IV SCENAIV.
22. ACTVS IV SCENA V.
23. ACTVS IV. SCENA VI.
24. ACTVS V SCENA I.
25. ACTVS V. SCENA II.
26. ACTVS V. SCENA III.
27. ACTVS V SCENA IV.
28. ACTVS V. SCENA V.
29. ACTVS V. SCENA VI.
30. PERORATIO.
Back
35 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS II. SCENA I.
8. ACTVS II. SCENA II.
9. ACTVS II. SCENA III.
10. ACTVS II. SCENA IV.
11. ACTVS III. SCENA I.
12. ACTVS III. SCENA II.
13. ACTVS III. SCENA III.
14. ACTVS III. SCENA IV.
15. ACTVS IV. SCENA I.
16. ACTVS IV. SCENA II.
17. ACTVS IV. SCENA III.
18. ACTVS IV. SCENA IV.
19. ACTVS V. SCENA I.
20. ACTVS V. SCENA II.
21. ACTVS V. SCENA III.
22. ACTVS V. SCENA IV.
23. ACTVS V SCENAV.
Back
28 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENA I.
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS II. SCENA IV.
12. ACTVS II. SCENA V.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS III. SCENA V.
18. ACTVS IV. SCENA I
19. ACTVS IV. SCENA II. [< ACTV]
20. ACTVS V. SCENA I.
21. ACTVS V. SCENA II.
22. ACTVS V. SCENA III.
23. ACTVS V. SCENA IV.
Back
28 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. ACTVS I. SCENA I.
4. ACTVS I. SCENA II.
5. ACTVS I. SCENA III.
6. ACTVS I. SCENA IV.
7. ACTVS I. SCENA V.
8. ACTVS I. SCENA VI.
9. ACTVS I. SCENA VII.
10. ACTVS II. SCENA I.
11. ACTVS II. SCENA II.
12. ACTVS II. SCENA III.
13. ACTVS II. SCENA IV.
14. ACTVS III. SCENA I.
15. ACTVS III. SCENA II.
16. ACTVS III. SCENA III.
17. ACTVS III. SCENA IV.
18. ACTVS IV. SCENA I.
19. ACTVS IV. SCENA II.
20. ACTVS IV. SCENA III.
21. ACTVS IV. SCENA IV.
22. ACTVS V SCENA I.
23. ACTVS V. SCENA II.
24. ACTVS V. SCENA III.
25. ACTVS V. SCENA IV.
26. ACTVS V. SCENA V.
27. ACTVS V. SCENA VI.
28. ACTVS V. SCENA VII.
29. PERORATIO.
Back
34 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENA I.
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS II. SCENA IV.
12. ACTVS II. SCENA V.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS IV. SCENA I.
18. ACTVS IV. SCENA II.
19. ACTVS IV. SCENA III.
20. ACTVS IV. SCENA IV.
21. ACTVS V. SCENA I.
22. ACTVS V SCENA II.
23. ACTVS V. SCENA III.
24. ACTVS V. SCENA IV.
25. ACTVS V. SCENA V.
26. PERORATIO.
Back
31 div
TEI header
Front
Main
1. Actorum nomina.
2. PROLOGVS
3. COMOEDIAE PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS I. SCENA VI.
10. ACTVS I. SCENA VII.
11. ACTVS II. SCENA I.
12. ACTVS II. SCENA II.
13. ACTVS II. SCENA III.
14. ACTVS II. SCENA IV.
15. ACTVS II. SCENA V.
16. ACTVS II. SCENA VI.
17. ACTVS II. SCENA VII.
18. ACTVS II. SCENA VIII.
19. ACTVS III. SCENA I.
20. ACTVS III. SCENA. II.
21. ACTVS III. SCENA III.
22. ACTVS III. SCENA IV.
23. ACTVS III. SCENA V.
24. ACTVS III. SCENA VII.
25. ACTVS IV. SCENA I.
26. ACTVS IV. SCENA II.
27. ACTVS IV. SCENA III.
28. ACTVS IV. SCENA IV
29. ACTVS IV. SCENA V.
30. ACTVS IV. SCENA VI.
31. ACTVS IV. SCENA VII.
32. ACTVS IV. SCENA VIII.
33. ACTVS V. SCENA I.
34. ACTVS V. SCENA II.
35. ACTVS V. SCENA III.
36. ACTVS V. SCENA IV.
37. ACTVS V. SCENA V.
38. ACTVS V. SCENA VI.
39. PERORATIO
Back
44 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. COMOEDIAE PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENAI
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS III. SCENA I.
12. ACTVS III. SCENA II.
13. ACTVS IV. SCENA I.
14. ACTVS IV. SCENA II.
15. ACTVS IV. SCENA III.
16. Argumentum vitae meae, atque corporis
17. ACTVS V. SCENA I.
18. ACTVS V. SCENA II.
19. ACTVS V. SCENA III.
20. PERORATIO.
Back
25 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS I. SCENA V.
9. ACTVS II. SCENA I.
10. ACTVS II. SCENA II.
11. ACTVS II. SCENA III.
12. ACTVS II. SCENA IV.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS IV. SCENA I.
18. ACTVS IV. SCENA II.
19. ACTVS IV. SCENA III.
20. ACTVS IV. SCENA IV.
21. ACTVS V. SCENA I.
22. ACTVS V. SCENA II.
23. ACTVS V. SCENA III.
24. ACTVS V. SCENA IIII.
Back
29 div
TEI header
Front
Main
1. ACTORVM NOMINA.
2. PROLOGVS.
3. PERIOCHA.
4. ACTVS I. SCENA I.
5. ACTVS I. SCENA II.
6. ACTVS I. SCENA III.
7. ACTVS I. SCENA IV.
8. ACTVS II. SCENA I.
9. ACTVS II. SCENA II.
10. ACTVS II. SCENA III.
11. ACTVS II. SCENA IV.
12. ACTVS II. SCENA V.
13. ACTVS III. SCENA I.
14. ACTVS III. SCENA II.
15. ACTVS III. SCENA III.
16. ACTVS III. SCENA IV.
17. ACTVS IV. SCENA I.
18. ACTVS IV. SCENA II.
19. ACTVS IV. SCENA III.
20. ACTVS IV. SCENA IV.
21. ACTVS V SCENA I.
22. ACTVS V. SCENA II.
23. ACTVS V. SCENA III.
24. ACTVS V. SCENA IV.
Back
29 div
TEI header
Front
Main
1. PROLOGUS AD SPECTATORES.
2. ARGUMENTUM.
3. ACTUS I. SCENA I.
4. ACTUS I. SCENA II.
5. ACTUS I. SCENA. III.
7. ACTUS II. SCENA I.
8. ACTUS II SCENA II.
9. ACTUS II. SCENA III.
10. ACTUS II. SCENA IIII.
11. ACTUS II. SCENA V.
13. ACTUS III. SCENA I.
14. ACTUS III. SCENA II.
15. ACTUS III. SCENA III.
16. ACTUS III. SCENA IIII.
18. ACTUS IIII. SCENA I.
19. ACTUS IIII. SCENA II.
20. ACTUS IIII. SCENA III.
21. ACTUS IIII. SCENA III.
23. ACTUS V. SCENA I.
24. ACTUS V. SCENA II.
25. ACTUS V. SCENA III.
26. ACTUS V. SCENA IIII.
27. ACTUS V. SCENA V.
28. ACTUS V. SCENA VI.
29. ACTUS V. SCENA VII.
30. ACTUS V. SCENA VIII.
32. EPILOGUS.
Back
TEI header
Front
Main
1. Personae.
Back
6 div
TEI header
Front
Main
1. PROLOGVS.
2. PERSONAE DRAMATIS
3. PERIOCHA.
4. Actus I. Scena I.
5. Scena II.
6. Scena III.
8. Scena IIII.
10. Actus II. Scena I.
11. Scena II.
12. Scena III.
13. Scena IIII.
14. Scena V.
16. Actus III. Scena I.
17. Scena II.
18. Scena III.
19. Scena IIII.
20. Scena V.
21. Scena VI.
22. Scena VII.
24. Actus IIII. Scena I.
25. Scena II.
26. Scena III.
27. Scena III.
29. Actus V. Scena I.
30. Scena II.
31. Scena III.
32. Scena IIII.
33. Scena V.
35. EPILOGVS.
Back
TEI header
Front
Main
1. PROLOGVS
2. INTERLOCUTORES.
3. ACTUS I. SCENA I.
4. ACTUS I. SCENA II.
5. ACTUS I. SCENA III.
6. ACTUS I. SCENA IIII.
8. ACTUS II. SCENA I.
9. ACTUS II. SCENA II.
10. ACTUS II. SCENA III.
11. ACTUS II. SCENA IIII.
12. ACTUS II. SCENA V.
13. ACTUS II. SCENA VI.
15. ACTUS III. SCENA I.
16. ACTUS III. SCENA II.
17. ACTUS III. SCENA III.
18. ACTUS III. SCENA IIII.
19. ACTUS III. SCENA V.
21. ACTUS IIII. SCENA I.
22. ACTUS IIII. SCENA II.
23. ACTUS IIII. SCENA III.
24. ACTUS IIII. SCENA IIII.
25. ACTUS IIII. SCENA V.
27. ACTUS V. SCENA I.
28. ACTUS V. SCENA II.
29. ACTUS V. SCENA III.
30. ACTUS V. SCENA IIII.
31. ACTUS V. SCENA V.
33. EPILOGUS
35. Errata singulorum tangunt, vitiaque,
Back
TEI header
Front
Main
1. Dramatis Personae.
2. ACTVS PRIMI
3. SCENA I.
4. SCENA II.
5. ACTVS SECVNDI.
6. SCENA I.
7. SCENA II.
8. SCENA III.
9. ACTVS TERTII
10. SCENA I.
11. ACTVS QVARTI
12. SCENA I.
13. SCENA II.
14. SCENA III.
15. SCENA IV.
16. ACTVS QVINTI
17. SCENA I.
18. SCENA II.
19. SCENA III.
20. SCENA IV.
Back
TEI header
Front
Main
2. ACTVS PRIMVS.
4. ACTVS SECVNDVS.
9. ACTVS TERTIVS.
12. ACTVS QVARTVS.
14. ACTVS QVINTVS.
Back
10 div
TEI header
Front
Main
1. Personae Tragaediae.
3. ACTVS PRIMVS.
4. SCENA PRIMA.
5. SCENA SECUNDA.
6. SCENA TERTIA.
7. SCENA QUARTA.
8. SCENA QVINTA.
9. SCENA SEXTA.
11. ACTVS SECVNDVS.
12. SCENA PRIMA.
13. SCENA SECUNDA.
14. SCENA TERTIA.
15. SCENA QUARTA.
16. SCENA QUINTA.
17. SCENA SEXTA.
19. ACTVS TERTIVS.
20. SCENA PRIMA.
21. SCENA SECUNDA.
22. SCENA TERTIA.
23. SCENA QUARTA.
24. SCENA QVINTA.
26. ACTVS QVARTVS.
27. SCENA PRIMA.
28. SCENA SECUNDA.
29. SCENA TERTIA.
30. SCENA QUARTA.
32. ACTVS QVINTVS.
33. SCENA PRIMA.
34. SCENA SECUNDA.
35. SCENA TERTIA.
36. SCENA QVINTA.
Back
TEI header
Front
Main
1. PERSONAE.
2. ACTVS PRIMVS.
3. SCENA PRIMA.
4. SCENA SECUNDA.
5. SCENA TERTIA.
6. SCENA QUARTA.
8. ACTVS SECVNDVS.
9. SCENA PRIMA.
10. SCENA SECUNDA.
11. SCENA TERTIA.
12. SCENA QUARTA.
15. ACTVS TERTIVS.
16. SCENA PRIMA.
17. SCENA SECUNDA.
18. SCENA TERTIA.
19. SCENA QUARTA.
21. ACTVS QVARTVS.
22. SCENA PRIMA.
23. SCENA SECUNDA:
24. SCENA TERTIA.
25. SCENA QUARTA.
26. SCENA QVINTA.
28. ACTVS QVINTVS.
29. SCENA PRIMA.
30. SCENA SECUNDA.
31. SCENA III.
32. SCENA IV.
Back
TEI header
Front
Main
1. PERSONAE TRAGOEDIAE.
3. ACTVS I. SCENA I.
4. SCENA II.
5. SCENA III.
6. SCENA IV.
8. ACTVS II. SCENA I.
9. SCENA II.
10. SCENA III.
11. SCENA IV
12. SCENA V.
14. ACTVS III. SCENA I.
15. SCENA II.
16. SCENA III.
17. SCENA IV.
19. SCENA V.
20. SCENA VI.
22. ACTVS IV. SCENA I.
23. SCENA II.
24. SCENA III.
25. SCENA IV.
27. ACTVS V. SCENA I.
30. SCENA II.
33. SCENA III.
35. SCENA IV.
Back
TEI header
Front
Main
1. Personae Tragoediae
4. ACTVS PRIMVS.
5. SCENA I.
6. SCENA II.
7. SCENA III.
8. SCENA IV.
9. SCENA V.
10. SCENA VI.
12. ACTVS SECVNDVS
13. SCENA I.
14. SCENA II.
15. SCENA III.
16. SCENA IV.
17. SCENA V.
18. SCENA VI.
19. SCENA VII.
21. ACTVS TERTIVS
22. SCENA I.
23. SCENA II.
24. SCENA III.
25. SCENA III.
26. SCENA V.
27. SCENA VI.
28. SCENA VII.
29. SCENA VIII.
31. ACTVS QVARTVS
32. SCENA I.
33. SCENA II.
34. SCENA III.
35. SCENA IV.
36. SCENA V.
37. SCENA VI.
38. SCENA VII.
39. SCENA VIII.
41. ACTVS QVINTVS.
42. SCENA I.
43. SCENA II.
44. SCENA III.
45. SCENA IV.
46. SCENA V.
47. SCENA VI.
48. SCENA VII.
49. SCENA VIII.
50. SCENA IX.
51. SCENA X.
52. SCENA XI.
Back
TEI header
Front
Main
1. Personae Tragaediae.
3. ARGVMENTVM.
4. ACTVS PRIMVS.
5. Argumentum Actus primi.
6. SCENA I.
7. SCENA II.
8. SCENA III.
9. SCENA IV.
10. SCENA V.
11. SCENA VI.
15. ACTVS SECVNDVS.
16. Argumentum Actus secundi.
17. SCENA I.
18. SCENA II.
19. SCENA III.
20. SCENA IV.
21. SCENA V.
22. SCENA VI.
25. ACTVS TERTIVS.
26. Argumentum Actus Tertij.
27. SCENA I.
28. SCENA II.
29. SCENA III.
30. SCENA IV.
31. SCENA V.
36. ACTVS QVARTVS.
37. Argumentum Actus Quarti.
38. SCENA I.
39. SCENA II.
41. SCENA III.
42. SCENA IV.
43. SCENA V.
44. SCENA VI.
47. ACTVS QVINTVS.
48. Argumentum Actus Quinti.
49. SCENA I.
50. SCENA II.
51. SCENA III.
52. SCENA IV.
53. SCENA V.
54. SCENA VI.
Back
TEI header
Front
Main
1. Prologus
2. Dramatis personae
3. Personae mutae
4. Actus I. Scena I
5. Actus I. Scena II
6. Actus I. Scena III
7. Actus I. Scena IIII.
8. Actus I. Scena V.
10. Actus II. Scena I.
11. Actus II. Scena II.
12. Actus II. Scena III.
13. Actus II. Scena IIII.
14. Actus II. Scena V.
15. Actus II. Scena VI
16. Actus II. Scena VII.
18. Actus III. Scena I.
19. Actus III. Scena II.
20. Actus III. Scena III.
21. Actus III. Scena IIII.
22. Actus III. Scena V.
23. Actus IIl. Scena VI.
24. Actus III. Scena VII.
25. Actus III. Scena VIII.
29. Actus III. Scena IX.
30. Actus III. Scena X.
31. Actus III. Scena XI.
33. Actus IV. Scena I.
34. Actus IV. Scena II.
37. Actus IV. Scena III.
38. Actus IV. Scena IIII.
39. Actus IV. Scena V.
40. Actus IV. Scena VI.
41. Actus IV. Scena VII.
42. Actus IV. Scena VIII.
43. Actus IV. Scena IX.
44. Actus IV. Scena X.
45. Actus IV. Scena ultima (XI).
46. Actus V. Scena I.
47. Actus V. Scena II.
48. Actus V. Scena III.
49. Actus V. Scena IIII.
50. Actus V. Scena V.
51. Actus V. Scena VI.
52. Actus V. Scena VII.
53. Actus V. Scena VIII.
54. Epilogus
Back
TEI header
Front
Main
1. Personae
3. Prologus
9. Actus primus
10. Scena prima
11. Scena secunda
12. Scena tertia
13. Scena quarta
14. Scena quinta
15. Scena sexta
16. Scena septima
18. Actus secundus
19. Scena prima
20. Scena secunda
21. Scena tertia
22. Scena quarta
23. Scena quinta
24. Actus tertius
25. Scena prima
26. Scena secunda
27. Scena tertia
28. Scena quarta
29. Scena quinta
30. Scena sexta
31. Actus quartus
32. Scena prima
33. Scena secunda
34. Scena tertia
35. Scena quarta
36. Scena quinta
38. Actus quintus
39. Scena prima
40. Scena secunda
41. Scena tertia
42. Scena quarta
43. Scena quinta
44. Scena sexta
45. Scena septima
46. Scena octava
Back
TEI header
Front
Main
7. Prologus
8. CONCLUSIO
Back
TEI header
Front
Main
1. PERSONAE
2. ACTVS PRIMVS.
4. ACTVS SECVNDVS
6. ACTVS TERTIVS
8. ACTVS QVARTVS
10. ACTVS QUINTVS
Back
TEI header
Front
Main
1. PROLOGVS.
2. PERIOCHA.
3. DRAMATIS PERSONAE
4. ACTVS I. SCAENA I.
5. ACTUS I. SCAENA II.
6. ACTUS II. SCAENA I.
7. ACTUS II. SCAENA II.
8. ACTUS II. SCAENA III.
9. ACTUS III. SCAENA I.
10. ACTUS III. SCAENA II.
11. ACTUS III. SCAENA III.
12. ACTUS IIII. SCAENA I.
13. ACTUS IIII. SCAENA II.
14. ACTUS IIII. SCAENA III.
15. ACTUS V. SCAENA I.
16. ACTUS V. SCAENA II.
17. ACTUS V. SCAENA III.
18. ACTUS V. SCAENA IIII.
19. ACTUS V. SCAENA V.
Back
TEI header
Front
Main
2. PROLOGVS
3. PERIOCHA.
4. ACTVS PRIMVS.
5. SCAENA SECVNDA.
6. ACTVS SECVNDUS
7. SCAENA SECVNDA.
8. SCAENA TERTIA.
9. SCAENA QVARTA.
10. ACTVS TERTIVS.
11. SCAENA SECVNDA.
12. SCAENA TERTIA.
13. SCAENA QVARTA.
14. SCAENA QVINTA.
15. ACTVS QVARTVS.
16. SCAENA SECVNDA.
17. SCAENA TERTIA.
18. SCAENA QVARTA.
19. SCAENA QVINTA.
20. SCAENA SEXTA.
21. SCAENA SEPTIMA.
22. SCAENA OCTAVA.
23. ACTVS QUINTVS.
24. SCAENA SECVNDA.
25. SCAENA TERTIA.
26. SCAENA QVARTA.
27. SCAENA QVINTA .
Back
