@node
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@conversionCode=tt
@conversionMethod=derived
@converter=Dirk Roorda (Text-Fabric)
@description=Link to description of the work
@descriptionTf=Edition
@editor=Jan Bloemendal
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@language=la
@schema=TEI + translatin
@sourceFormat=TEI
@teiVersion=not specified
@title=Translatin (drama, 1500-1750))
@valueType=str
@version=0.0.1
@writtenBy=Text-Fabric
@dateWritten=2025-02-19T13:25:30+00:00Z

2071730	https://books.google.nl/books?id=CApZAAAAYAAJ
https://play.google.com/books/reader?id=CtBEAAAAcAAJ
mateo.uni-mannheim.de/camena/bald4/baldepoemata4.html
https://nl.wikipedia.org/wiki/Adrianus_Barlandus
https://books.google.nl/books?id=maxlAAAAcAAJ
https://books.google.nl/books?id=Nua_TBRwCikC
https://play.google.com/books/reader?id=RG4UAAAAQAAJ
https://play.google.com/books/reader?id=RG4UAAAAQAAJ
https://play.google.com/books/reader?id=RG4UAAAAQAAJ
https://play.google.com/books/reader?id=RG4UAAAAQAAJ
https://play.google.com/books/reader?id=RG4UAAAAQAAJ
https://books.google.fr/books?id=ZLNxonJ82gcC
https://books.google.fr/books?id=ZLNxonJ82gcC
https://books.google.fr/books?id=ZLNxonJ82gcC
https://books.google.fr/books?id=ZLNxonJ82gcC
http://diglib.hab.de/inkunabeln/69-2-quod-12/start.htm
2071747	https://books.google.nl/books?id=XP3Z8pc5P_MC / https://books.google.nl/books?id=4vok_qjjSJwC
https://en.wikipedia.org/wiki/Petrus_Cunaeus
https://www.dbnl.org/tekst/aa__001biog05_01/aa__001biog05_01_0030.php
http://mateo.uni-mannheim.de/camena/drama/
http://www.let.leidenuniv.nl/Dutch/Ceneton/ProgrammaPhiledonius1657.html
http://reader.digitale-sammlungen.de/de/fs1/object/display/bsb10181680_00005.html
https://philological.cal.bham.ac.uk/forsett/
https://quod.lib.umich.edu/e/eebo/A40366.0001.001/1:7.1?rgn=div2;view=fulltext
https://www.dbnl.org/tekst/gnap001pmin01_01/gnap001pmin01_01_0005.php
https://digital.onb.ac.at/OnbViewer/viewer.faces?doc=ABO_%2BZ175237401
https://books.google.be/books?vid=GENT900000105791
https://humanistica-helvetica.unifr.ch/fr/works/129
https://humanistica-helvetica.unifr.ch/fr/works/136
https://books.google.nl/books?id=wnVodHpysZcC
http://www.let.leidenuniv.nl/Dutch/Latijn/Facsimiles/GrotiusAdamusExul1601/index.htm
https://www.let.leidenuniv.nl/Dutch/Ceneton/GrotiusChristusPatiens1608.html
https://books.google.nl/books?id=g5C7Hg_dvlUC&dq=%22contra+quam+Sophocles+Oedipode%22&hl=nl&source=gbs_navlinks_s
https://mateo.uni-mannheim.de/camena/gwalt2/gualtherusnabal-toc.html
https://www.let.leidenuniv.nl/Dutch/Ceneton/HeinsiusAuriacus1602.html
https://www.let.leidenuniv.nl/Dutch/Ceneton/HeinsiusHerodes1632.html
http://daten.digitale-sammlungen.de/~db/0001/bsb00016452/images/
http://daten.digitale-sammlungen.de/~db/0001/bsb00016450/images/
https://books.google.nl/books?id=eXQ603cHK6MC
https://books.google.be/books?vid=GENT900000083758
https://books.google.nl/books?id=YWFPAAAAcAAJ
https://reader.digitale-sammlungen.de/resolve/display/bsb11377619.html
https://wiki.muenster.org/index.php/Johannes_Kerckmeister
https://www.deutsche-biographie.de/sfz80434.html#adbcontent
https://books.google.nl/books?id=Kp76rQEACAAJ
https://books.google.nl/books?id=Kp76rQEACAAJ
http://daten.digitale-sammlungen.de/~db/bsb00004866/images/
https://books.google.nl/books?id=3Wg-AAAAcAAJ
https://books.google.nl/books?id=jTCaKMTHN2AC
https://books.google.nl/books?id=3Wg-AAAAcAAJ
https://books.google.nl/books?id=Te4UAAAAQAAJ
https://books.google.nl/books?id=3Wg-AAAAcAAJ
https://books.google.nl/books?id=3Wg-AAAAcAAJ
https://books.google.nl/books?id=3Wg-AAAAcAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://www.let.leidenuniv.nl/Dutch/Ceneton/MacropediusAndrisca1545.html
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://hum2.leidenuniv.nl/Dutch/Ceneton/Facsimiles/MacropediusJesus1556/index.htm
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=e2ATAAAAQAAJ
https://books.google.nl/books?id=1HqjB9FfrcEC
https://www.let.leidenuniv.nl/Dutch/Latijn/MURE01.html
https://ia801303.us.archive.org/35/items/ecerinidetragedi00mussuoft/ecerinidetragedi00mussuoft.pdf
https://en.wikipedia.org/wiki/Johannes_Narssius#cite_note-ADB-4
https://books.google.nl/books?id=sFtYAAAAcAAJ
https://books.google.nl/books?id=EvKb5td3QvcC
https://books.google.nl/books?id=Vp1vVu211sYC
https://books.google.nl/books?id=nmZPAAAAcAAJ
https://books.google.nl/books?id=VD44U0886h0C
https://books.google.nl/books?id=VD44U0886h0C
http://diglib.hab.de/inkunabeln/53-quod-2/start.htm
https://dhb.thulb.uni-jena.de/receive/ufb_cbu_00013805
https://books.google.nl/books?id=3ARXAAAAcAAJ
http://www.philological.bham.ac.uk/roulers/
https://philological.cal.bham.ac.uk/ruggle/contents.html
https://gallica.bnf.fr/ark:/12148/bpt6k134076p
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=-PYvx8JL4DAC
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://books.google.nl/books?id=r-ZIAAAAcAAJ
https://mateo.uni-mannheim.de/camena/schopjac1/te01.html
https://jbc.bj.uj.edu.pl/dlibra/publication/102244/edition/95250/content?ref=desc&format_id=2
https://play.google.com/books/reader?id=9gg8AAAAcAAJ
https://mateo.uni-mannheim.de/camena/stummel1/te01.html
https://books.google.nl/books?id=Ad4TAAAAQAAJ
https://books.google.nl/books?id=DfrUk8iyKG0C&printsec=frontcover&hl=nl&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false
https://books.google.nl/books?id=hgDowgEACAAJ
https://books.google.nl/books?id=hgDowgEACAAJ
https://books.google.nl/books?id=fHETAAAAQAAJ
https://books.google.nl/books/about/Henricus_Octavus_seu_Schisma_Anglicanum.html?id=XnquPgAACAAJ
https://books.google.nl/books?id=hgDowgEACAAJ
https://nl.wikipedia.org/wiki/Petrus_Vladeraccus
https://mateo.uni-mannheim.de/camena/weit1/te01.html
https://portail.biblissima.fr/ark:/43093/edata7dd4814e1d6f7570449dbbd5d49465ebe9c71e27
https://books.google.nl/books?id=X70TAAAAQAAJ
http://daten.digitale-sammlungen.de/~db/0003/bsb00037704/images/
https://mateo.uni-mannheim.de/camena/drama/jpg/s0448.html
