@node
@contributors1=Hennie Brugman, Hayco de Jong, Bram Buitendijk, Sebastiaan van Daalen, Dirk Roorda
@conversionCode=tei
@conversionMethod=literal
@converter=Dirk Roorda (Text-Fabric)
@description=this is TEI attribute drama
@descriptionTf=Edition
@editor=Jan Bloemendal
@institute1=HuC (Humanities Cluster) Amsterdam
@institute2=Huygens Instituut Amsterdam
@language=la
@schema=TEI + translatin
@sourceFormat=TEI
@teiVersion=not specified
@title=Translatin (drama, 1500-1750))
@valueType=str
@version=0.0.3
@writtenBy=Text-Fabric
@dateWritten=2025-02-25T13:49:06+00:00Z

1668792	Alberti-Philodoxus
Aler-Innocentia
Balde-Iephtias
Barlandus-Dialogus
Beza-Abrahamus
Brechtus-Euripus
Caussin-Felicitas
Caussin-Hermenigildus
Caussin-Nabuchodonosor
Caussin-Solyma
Caussin-Theodoricus
Cellotius-Adrianus
Cellotius-Chosroes
Cellotius-Reviviscentes
Cellotius-Sapor
Celtis-Ludus
Claus-Vulpanser
Crocus-Ioseph
Cunaeus-Dido
Dalanthus-Dido
Diether-Ioseph
Enden-Philedonius
Ens-Auriacus
Forsett-Pedantius
Foxe-Christus
Gnapheus-Acolastus
Gnapheus-Morosophus
Goethals-Soter
Gretser-Timon
Gretser-Underwaldius
Grimald-Christus
Grotius-Adamus
Grotius-Christus
Grotius-Phoenissae
Gwalther-Nabal
Heinsius-Auriacus
Heinsius-Herodes
Holonius-Catharina
Holonius-Laurentias
Honerdus-Thamara
Houcharius-Grisellis
Houthem-Gedeon
Ischyrius-Homulus
Kerckmeister-Codrus
Knuyt-Scornetta
Laurimanus-Exodus
Laurimanus-Miles
Locher-Iudicium
Lummenaeus-Abimelech
Lummenaeus-Amnon
Lummenaeus-Bustum
Lummenaeus-Carcer
Lummenaeus-Iephte
Lummenaeus-Sampson
Lummenaeus-Saul
Macropedius-Adamus
Macropedius-Aluta
Macropedius-Andrisca
Macropedius-Asotus
Macropedius-Bassarus
Macropedius-Hecastus
Macropedius-Hypomone
Macropedius-Iesus
Macropedius-Iosephus
Macropedius-Lazarus
Macropedius-Petriscus
Macropedius-Rebelles
Malapertius-Sedecias
Muretus-Caesar
Mussato-Ecerinis
Narssius-Gustavus
Papaeus-Samarites
Philicinus-Esther
Philicinus-Magdalena
Placentius-Clericus
Placentius-Plausus
Placentius-Susanna
Reuchlin-Henno
Reuchlin-Sergius
Rosefeldus-Moschus
Roulerius-Stuarta
Ruggle-Ignoramus
Salius-Nassovius
Schonaeus-Ananias
Schonaeus-Baptistes
Schonaeus-Cunae
Schonaeus-Daniel
Schonaeus-Dyscoli
Schonaeus-Fabula
Schonaeus-Iosephus
Schonaeus-Iuditha
Schonaeus-Naaman
Schonaeus-Nehemias
Schonaeus-Pentecoste
Schonaeus-Pseudostratiotae
Schonaeus-Saulus
Schonaeus-Susanna
Schonaeus-Tobaeus
Schonaeus-Triumphus
Schonaeus-Typhlus
Schonaeus-Vitulus
Schopper-Ectrachelistes
Simonides-Castus
Stymmelius-Isaac
Stymmelius-Studentes
Susius-Pendularia
Telesio-Imber
Vernulaeus-Conradinus
Vernulaeus-Crispus
Vernulaeus-Gorcomienses
Vernulaeus-Henricus
Vernulaeus-Theodoricus
Vladeraccus-Tobias
Weitenauer-Annibal
Wimpheling-Stylpho
Zevecotius-Rosimunda
Zovitius-Didascalus
Zovitius-Ruth
